### ISSUE TITLE
Demande features : Modification des stats personnages

### ISSUE THREAD

**Issue by mioteck** [RMEx/RME#1]
Salut !

Je trouve que cela serai pas mal d'avoir un script pour pouvoir modifier directement les stats (stats primaire comme les HP, atk, etc... et secondaire comme l'agressivité, la précision, coup critique, etc... ) des héros/monstres par exemple avec :
actor[1].set_hp_max(2000)

**Comment by xvw** [comment]
Coucou, merci de ton intérêt pour le projet :) 

**Joke à dit**
> Bonjour,
> Pour les stats primaires, on peut déjà les modifier en événement... avec la possibilité de mettre une variable à la place de la valeur. Je préfère qu'on ne fasse pas sans raison une commande qui existe > déjà.
> Pour les stats secondaires... c'est sensé rester dépendant de l'équipement et de la classe.

De mon point de vue, je pense que c'est une *mauvaise chose*. Car ça mélange la notion statique, tel que défini dans la base de données et la notion dynamique (ce qui est sauvegardé, en gros). 

N'hésite pas à nous suggerer d'autre chose, ne va pas croire qu'on esquive ta proposition. 
Merci !
Nuki.

**Comment by mioteck** [comment]
Merci de votre réponse rapide.
Vu que l'on peut les changer directement en événement, y a t'il un moyen d'appeler d'en appeler un directement dans un script?
