### ISSUE TITLE
Nouvelle commande: Fresh_event + Erase_event ?

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#101]
Serait t'il possible d'ajouter une commande qui nous renvois le plus petit id d'event supprimé qui se trouve sur la map ? (Et qui envoi nil si aucun est présent).

Merci!

**Comment by xvw** [comment]
http://rmex.github.io/RMEDoc/#fresh_event_id

**Comment by xvw** [comment]
(elle renvoie le "max_event_id + 1 si aucun événement n'a été supprimé)
