### ISSUE TITLE
Nouvelle commande: Once_Event de proximité

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#102]
Serait t'il possible d'ajouter une commande dans le style de once_event, mais qui au mieux de sélectionner l'id le plus petit, sélectionne : 
-Le plus prêt de lui
-Le plus loin de lui
-Un event au hasard 

Merci!

**Comment by xvw** [comment]
Yo, je peux te conseiller ça : 

-  `get_events{|id| le selecteur}.min_by{|id| square_between(id_source, id)}`
-  `get_events{|id| le selecteur}.max_by{|id| square_between(id_source, id)}`
-  ``get_events{|id| le selecteur}.sample`
