### ISSUE TITLE
Demande de nouvelle commande : se_play?(name),  me_play?(name) 

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#103]
Bonjour, 

J'aimerai savoir si il était possible d'ajouter des commandes ayant pour but de détecter si certains sons (comme les SE ou les ME) son en train d'être jouer.

**Comment by acs-l** [comment]
**Nope**, l' *A.P.I.* du module `Audio` présent dans le `RGSS` ne permet même pas de savoir si un son est actuellement en train d'être joué ou non :S.

Même si on se place en interception sur les appels visant à lancer un son {`SE`, `ME`, `BGS`, `BGM`} pour les mémoriser (***memento***), on ne dispose d'aucun moyen propre pour déterminer la durée de la musique jouée : il faudrait déjà détecter le temps nominal de l'enregistrement audio, puis calculer son temps effectif en se basant sur la fréquence programmée.

---
Si tu avais pour idée d'utiliser ce type de commande pour vérifier que l'utilisateur réalise une action tant que la musique est toujours en train d'être jouée, je pense qu'il faut plutôt voir ça comme "*une action à réaliser dans une fenêtre de temps donnée*". Tu arrêtes le son brutalement ([`se_stop`](http://rmex.github.io/RMEDoc/#se_stop)) ou en fondu ([`me_fade`](http://rmex.github.io/RMEDoc/#me_fade)) une fois la plage de temps écoulée.
