### ISSUE TITLE
Bug ITextProfile : Size limité a 96 ?

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#104]
Hello, 

Petit soucis avec les profils du ITextProfile, en effet des que la valeur "Size" atteint 97 (ou plus), un message d’erreur apparaît : "Bad value for size".

**Comment by Spyrojojo** [comment]
Le bug semble être aussi présent pour les taille égal ou inférieur a 6.

**Comment by xvw** [comment]
Oui, il faudrait ajouter dans la documentation que la taille minimum est 7 et maximum 96 (Limite de RPGMaker)

**Comment by xvw** [comment]
Je l'ai ajouté au Wiki. Merci !
