### ISSUE TITLE
Proposition de commande : Picture_move_stop()

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#108]
Salut,

Je viens vous proposer une idée de commande qui stopperait tous les déplacements d'images en cours (ou juste les déplacements de(s) image(s) que l'ont souhaite).

**Comment by xvw** [comment]
Je pense que cette commande (bien que potentiellement confortable) est faisable à la main, et donc qu'il est inutile d'alourdir les commandes de Pictures (déjà un des plus gros module). 
Désolé.
