### ISSUE TITLE
[Commands-02/06/15] map_id, event_id

### ISSUE THREAD

**Issue by Celestiel** [RMEx/RME#11]
map_id, event_id/me vaux 0 dans trigger, micro_event

**Comment by Grimimi** [comment]
Il me semble que le soucis lié à event_id est corrigé. Il suffit d'utiliser trigger{|id| ... } à la place de trigger{} et la variable id devient effective. 
Pour map_id, tu as raison, je regardai bientôt. Merci :)

**Comment by xvw** [comment]
Dans un micro_event (ou trigger personnalisé). Utiliser @id ou me n'a pas beaucoup de sens car le trigger et l'action prennent en argument une variables "id" qui défini l'événement courant. 
Concernant map_id c'est un problème de portée. On recommande donc d'utiliser c(:map_id) à la place :)
