### ISSUE TITLE
Bug avec la commande : cursor_system(flag)

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#110]
Salut, 

Petit soucis avec la commande cursor_system(flag). quand cette dernière est utilisé dans le projet et que la touche F1 est utilisé, le curseur reste invisible pour la petite fenêtre de propriété, ce qui est assez gênant.

**Comment by xvw** [comment]
Je comprend bien le problème, malheureusement, c'est insolutionnable :)

**Comment by xvw** [comment]
je vais tenter quelque chose !)

**Comment by xvw** [comment]
Non en fait, ce n'est pas possible :'( désolé

**Comment by acs-l** [comment]
#### Actuellement, il n'y pas de solution purement *Ruby* depuis le projet qui permette de résoudre ton problème.

L'appui sur la touche `F1` -- comme `Alt + Enter` (*affichage en plein écran*) et `F12` (*retour à l'écran-titre*) d'ailleurs -- est directement intercepté par l'applicatif qui lance le projet.

On peut éventuellement écrire une petite bibliothèque dynamique (`.dll`) en `C`/`C++` (à appeler depuis le projet) pour désactiver leurs interceptions. Tu peux en voir une illustration ici :
 [*Chainsawkitten/RGSSDisableF1AltEnterF12*](https://github.com/Chainsawkitten/RGSSDisableF1AltEnterF12).

Néanmoins ça reviendrait à **contrevenir à la charte d'utilisation de *RPG Maker VX Ace*** (puisqu'on modifie le logiciel), et on ne peut donc pas l'incorporer à [*RME*](https://github.com/RMEx/RME). Désolé.

---

Dans tous les cas, merci d'avoir poser le doigt sur cette _commande_ :) ! Ça nous a permis de détecter une étourderie dans l'implémentation de celle-ci (#148).

Tu devrais maintenant être capable de réafficher le curseur quand tu le souhaites via `cursor_system(true)`.
