### ISSUE TITLE
Camera_move et déplacement en diago' ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#116]
Salut !

Quand on utilise la commande RME pour déplacer la caméra sur un point... elle ne se déplace qu'en lignes droites (à moins que ça ait été corrigé depuis ?). C'est un peu cheum. :/

Merci d'avance pour une éventuelle réponse. o/

**Comment by Grimimi** [comment]
Je ne comprend pas comment doit se comporter la caméra pour les déplacements en diagonale... 
Ca ne peut marcher que si la caméra doit effectuer un mouvement à 45deg non?

**Comment by Zer0zer0x** [comment]
C'est surtout qu'on gagne du temps quand on la déplace sur une certaine distance, et que le mouvement est plus fluide.

Ce script-là le gère et est compatible avec RME, du coup je n'utilise jamais les commandes de caméra qui sont fournies, c'est dommage. :(
http://www.rpg-maker.fr/scripts-446-cam-control.html

Grosso modo, ça donne ça (à vitesse lente) : 
http://image.noelshack.com/fichiers/2017/33/6/1503150347-cap.gif

La caméra s'aligne d'abord avec le point qu'elle a à chercher, en diagonale, puis finit sa trajectoire en allant tout droit. Plus le mouvement est rapide, plus ça le fait. (Alors qu'une caméra qui fait un gros "coude" ça passe difficilement mieux je trouve...)

Peut-être que c'est un peu plus complexe que ça. Pour être franc je n'ai jamais lu le code du script de Galv...
