### ISSUE TITLE
Teleport

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#117]
Salut !

La commande pour gérer les téléportations dans RME est un peu... brutale, je crois.
Serait-il possible de ne pas avoir besoin de spécifier la direction à chaque nouvelle téléportation utilisant cette commande, par exemple ? D'avoir des valeurs qui se définissent d'elles-mêmes quand elles sont laissées vides ?

Merci. o/

**Comment by xvw** [comment]
http://rmex.github.io/RMEDoc/#player_teleport
