### ISSUE TITLE
[BUG:RME-02/06/15] Trigger{}

### ISSUE THREAD

**Issue by Celestiel** [RMEx/RME#12]
Je ne sais pas vraiment ce que je dois dire. ça a l'air de fonctioner avec des variables globales. Mais une fois qu'on passe en  locale, ça fait n'importe quoi.

**Comment by Grimimi** [comment]
Pourrais tu être "plus explicite"? 
ça veut dire quoi "faire n'importe quoi"? 
Merci :)

**Comment by Jauke** [comment]
Trigger évalue en faisant un binding sur $game_map.interpreter, il ne peut à priori pas faire un binding dans le contexte de l'événement lui-même qui n'est instancié qu'après la validation du trigger (donc de la page).

Du coup, en effet, @event_id et me ne peuvent être utilisés, ce qui entrave le fonctionnement d'une variable locale lorsqu'on ne spécifie pas l'ID de l'événement.

Pour l'instant, la solution c'est de faire, par exemple, `trigger{|id| SV[id, 5] = 10}`

Mais je doute encore de la nécessité du |id|, peut-être qu'une solution nous a échappée dans l'implémentation du trigger.

**Comment by Jauke** [comment]
Ah, et si `map_id` ne fonctionne pas, je crains que ça soit plus le bordel que ça.

**Comment by xvw** [comment]
Pour map_id il suffit d'utiliser `c(:map_id)`. 
Concernant les triggers. La proposition de Joke est la bonne.
