### ISSUE TITLE
[ Bug RME, 19/06/2015, Chute FPS ] Help me.....

### ISSUE THREAD

**Issue by Dylou** [RMEx/RME#13]
Bonjour /soir, je viens vous expliquer mon souci, depuis plusieurs moments avec quelques personnes, nous avons découvert une chute importante ( Fall) de FPS, nous passons de 60 FPS sur le menu à 5 voir moins FPS sur une map vierge, en supprimant les scripts RME du projet et de retour sur cette map nous gardons un ratio de 50 voire 60 FPS ( variation due à la connexion d'appel de Skype) .

J'espère que vous trouverez rapidement ( dans la mesure du possible ) une solution à ce problème récurrent, car j'ai du mal à travailler avec cela, en vous remerciant.

           Cordialement Dylan / Waikiki.

**Comment by xvw** [comment]
Malheureusement, cette semaine ça va être dur de m'en occuper. Peut être quelqu'un d'autre ? 
@Jauke @Grimimi  @mspawn  @hyperaho  ?

**Comment by xvw** [comment]
(merci pour ton retour)

**Comment by Dylou** [comment]
Pas de souci ;)
