### ISSUE TITLE
Lives/Vidéos : Systèmes

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#142]
> Cette issue sera mise à jours en fonction des lives :) 

### Idées de systèmes

- [ ] Un système de grappin 
- [ ] Le rats de Wild Arms 1 
- [ ] Les bombes de Wild Arms 1
- [ ] Des coffres de stockage
- [ ] Un système de quêtes minimaliste

**Comment by xvw** [comment]
A fermer pour le moment (on reparlera de la comm plus tard)

**Comment by Zer0zer0x** [comment]
Système de traces de pas ; héros comme événements compris.
(Je poste ça parce que j'ai envie. :D)
