### ISSUE TITLE
Le move_to va mieux mais.....

### ISSUE THREAD

**Issue by Dylou** [RMEx/RME#143]
La commande move_to a bien été amélioré mais il reste un tout petit soucis que je vous illustre en GIF : 
https://media.giphy.com/media/l1J3pn9RnPPk6q5na/giphy.gif
Donc voilà en gros le soucis : Quand apparemment le Héros est dans l'angle de la carte je dois cliquer sur la souris entre 2 à 3 fois pour que le héros se décide à aller dans la bonne direction ;)

                                     Cordialement Dylan/Bliaxx

**Comment by xvw** [comment]
C'est étrange :D

**Comment by Dylou** [comment]
Oui :D

**Comment by xvw** [comment]
le move_to est fini (et corrigé !) ENFIN ENFIN !
