### ISSUE TITLE
Dépasser la limite de 999 maps ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#147]
Bonjour !
Peu importe le moyen, mais... serait-il facile de pouvoir dépasser la limite des 999 maps ?

Courage. :F

**Comment by xvw** [comment]
Ce n'est pas au programme. 
(d'ailleurs, y'a tellement peu de jeux qui arrivent à avoir une démo... 999maps, n'en parlons pas)

**Comment by xvw** [comment]
http://www.rpgmakercentral.com/topic/12880-solutions-to-the-999-map-limit/
