### ISSUE TITLE
Risque de SegmentationFault

### ISSUE THREAD

**Issue by NuriYuri** [RMEx/RME#15]
https://github.com/RMEx/RME/blob/master/src/Incubator.rb#L191

Sur cette ligne on présuppose que le RGSS3 se trouvera à l'adresse 10000000 sauf que ce n'est pas le cas sur toutes les machines. Parfois certains drivers ou outils exotiques viennent squatter ici pour des raisons x ou y et le RGSS va se placer ailleurs.

Si jamais quelqu'un a un RGSS3 Player a cessé de fonctionner avec le script de résolution. Je conseille de mettre un appel de LoadLibrary (avec le nom de la DLL du RGSS3) à la place 268435456. 

Comme vous pouvez le voir, LoadLibrary retournera toujours le pointeur de base d'un PE en mémoire : http://puu.sh/jcM58/341a1ee838.png
(Sauf échec :p)

**Comment by hyperaho** [comment]
Merci beaucoup. Comme c'était "dans l'incubateur" je ne m'étais pas réellement soucié de l'implémenter correctement, c'était juste un "petit essai" fait pour le fun et il n'avait jamais été question (pour ma part) de l'intégrer à RME. Mais je suis ton conseil ;) merci : 
C'est fixé : https://github.com/RMEx/RME/commit/dcbebcb6b7aa4327a600501e5341040196445629
