### ISSUE TITLE
Bloquer la caméra

### ISSUE THREAD

**Issue by Lunri** [RMEx/RME#156]
Bonjour, serait-il possible d'avoir une commande pour bloquer la caméra sur l'axe Y mais pas sur l'axe X et inversement ?

Merci !

**Comment by xvw** [comment]
- camera_lock_x 
- camera_lock_y 

tu peux, @BastienDuplessier, t'inspirer de http://rmex.github.io/RMEDoc/#camera_lock

**Comment by BastienDuplessier** [comment]
Yep, j'ai déjà un peu étudié la question :)

**Comment by BastienDuplessier** [comment]
Le développement a été effectué et a été mergé ici par cette PullRequest #171.
Ce sera disponible dans la version 1.1.0 de RME.
