### ISSUE TITLE
... il le fallait :) 

### ISSUE THREAD

**Issue by Grimimi** [RMEx/RME#158]
[A lire avec cette musique](https://www.youtube.com/watch?v=PuGOTIUVB7U)

> Où sont partits tous les bon scripteurs ? 
> Où sont tous les dieux de RPGMaker VXAce ? 
> Il n'y a plus de Zeus81, plus de Avygeil :'( 
> Il y aurait-il un magicien du Ruby ici ?
> La nuit en codant en Coq (oui, je suis loin), 
> Je rêve de ce dont RME a besoin 
> Pendant que @Jauke fait du dessin !

> IL FAUT UN RAHO, 
> JE CHERCHE @hyperaho pour coder toute la nuit ! 
> Il faut qu'il code bien ! 
> Il faut qu'il code vite ! 
> Il faut qu'il faut qu'il fixe ce qu'il manque enfin !
> J'AI BESOIN D'UN RAHO ! 
> JE SPAMMERAI RAHO JUSQU'AU BOUT DE LA NUIT ! 
> Je veux revoir son code random ! 
> Je veux le revoir au plus vite ! 
> Je veux le voir coder plus vite que son ombre ! 
> Plus vite que son ombre ! 

> Nuki fait du Caml, S4suk3 du Haskell
> Seul Zangther essaie de fixer ce qu'il faut, 
> RME risque de mourir, 
> C'est rigolo et triste à en mourir ! 
> KingKadelfek utilise Unity, Roys utilise Geex, 
> Berka ne fait plus d'API, Ashka est resté sur VX, 
> Où sont les `udaptes`, qu'elle est la roadMap ? 
> N'ayons pas peur ! 
> Il reste des contributeurs !

> IL FAUT UN RAHO, 
> JE CHERCHE @hyperaho pour coder toute la nuit ! 
> Il faut qu'il code bien ! 
> Il faut qu'il code vite ! 
> Il faut qu'il faut qu'il fixe ce qu'il manque enfin !
> J'AI BESOIN D'UN RAHO ! 
> JE SPAMMERAI RAHO JUSQU'AU BOUT DE LA NUIT ! 
> Je veux revoir son code random ! 
> Je veux le revoir au plus vite ! 
> Je veux le voir coder plus vite que son ombre ! 
> Plus vite que son ombre ! 

> IL FAUT UN RAHO, 
> JE CHERCHE @hyperaho pour coder toute la nuit ! 
> Il faut qu'il code bien ! 
> Il faut qu'il code vite ! 
> Il faut qu'il faut qu'il fixe ce qu'il manque enfin !
> J'AI BESOIN D'UN RAHO ! 
> JE SPAMMERAI RAHO JUSQU'AU BOUT DE LA NUIT ! 
> Je veux revoir son code random ! 
> Je veux le revoir au plus vite ! 
> Je veux le voir coder plus vite que son ombre ! 
> Plus vite que son ombre !

**Comment by hyperaho** [comment]
Arrête la drogue.

**Comment by Grimimi** [comment]
![Un singe qui dance](https://media.tenor.com/images/cad68737a9df59d2a73ed2745359d652/tenor.gif)

**Comment by xvw** [comment]
Je clos, mais cette issue restera pour la postérité ;)
