### ISSUE TITLE
Informer un event commun de l'objet qui l'a appelé

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#161]
Bonjour !
Avec RM, on peut appeler un événement commun à l'utilisation d'un objet... le problème est qu'il n'y a aucun moyen de créer un événement commun qui réagit en fonction de l'objet qui l'a appelé. :'(

Obligé de créer un événement commun par objet différent...

Une commande à mettre en début de l'événement commun appelé par des objets serait-elle envisageable ? Afin de récupérer l'ID de l'objet qui a appelé l'événement, dans une variable...

Merci d'avance pour vos réponses ! \o

**Comment by xvw** [comment]
Hum tu ne pourrais pas juste faire un evenement commun par objet qui "attribue une variable" avec l'ID de 'lobjet et ensuite un événement commun générique ?

**Comment by Hinola** [comment]
peut être une commande "last_used_item" serait possible
Avec un enregistrement de l'id de l'objet utilisé dans la methode "Game_Action.evaluate_item"

J'ai pas trop encore regardé l'utilisation d'objet, mais ça me semble être la méthode qui gère tout ça

**Comment by Zer0zer0x** [comment]
> Hum tu ne pourrais pas juste faire un evenement commun par objet qui "attribue une variable" avec l'ID de 'lobjet et ensuite un événement commun générique ?

Oé mais c'est un peu cheum. :(

**Comment by xvw** [comment]
C'est prévu pour la prochaine version de RME

**Comment by Hinola** [comment]
En attendant tu peux coller ce script sous materials :
`class Game_Battler < Game_BattlerBase
  alias_method :old_use_item, :use_item
  def use_item(item)
    $game_temp.last_used_item = item.id
    old_use_item(item)
  end
end

class Game_Temp
  attr_accessor :last_used_item
end

module RMECommands
  def last_used_item()
    return $game_temp.last_used_item
  end
end`

Et utiliser la commande last_used_item dans l'assignation d'une variable dans l’évènement commun.

**Comment by Zer0zer0x** [comment]
Super !
