### ISSUE TITLE
Neige sans assombrir l'écran

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#162]
Salut !

Quand on utilise la neige dans VX Ace, il assombrit l'écran.
Le pire, c'est qu'il l'assombrit avec du NOIR, opacité je sais pas combien.

Ce n'est donc pas gérable, même avec les tons de l'écran, puisque ça brise l'équilibrage Rouge/Vert/Bleu.

Serait-il possible de tout simplement créer une commande pour avoir de la neige, ainsi que le reste de la météo, SANS ces effets indésirables ?

Merci. o/

**Comment by BastienDuplessier** [comment]
Petite précision, vu que j'ai trouvé le code qui change la teinte de l'écran.
En fait, la teinte change selon la "force" que tu indique dans ta commande.

En tout cas, une PR est en cours pour ajouter une commande pour activer/désactiver ce changement lors de l'utilisation des commandes de météo.
