### ISSUE TITLE
Chute massive de FPS avec invoke_event

### ISSUE THREAD

**Issue by Ibiky** [RMEx/RME#165]
Tout es dans le titre ^^, Bonjour/Soir à vous, voila ma demande est quelque peut particulière vue que c'est pour mon projet de Tower Defense, seul souci que j'ai en ce moment ce sont les FPS qui chute brutalement, (le code est très complexe je me doute qu'il ne dois pas aider RM (pauvre logiciel que je torture), la chose est simple, une invasion de petit soldat qui ce font mitrailler par des tourelles, au début tout vas bien, mais à un moment tout bascule trop de FPS en chute jusqu’à plus pouvoir jouer, cela s'explique surement car il y à trop d'evenement en jeu, donc la question est peut ont faire quelque chose pour limiter la chute de FPS ?

**Comment by BastienDuplessier** [comment]
Salut !
Nous allons effectuer quelques benchmarks pour voir la performance de cette commande au niveau de RPG Maker.
De ton coté, si tu pouvais nous fournir ton projet, cela nous aiderait à analyser d'où vient exactement le soucis.
Merci à toi.

**Comment by Ibiky** [comment]
Pas de souci, je viens de tester avec RME à jour et mon projet ne fonctionne plus, il plante à un moment, surement une confrontation avec mon ancien code, j'ai mis le projet deux fois mon projet un à jour et l'autre non dans le .rar

https://www.dropbox.com/s/ka58f81jgm99p39/projet%20RME.rar?dl=0

**Comment by xvw** [comment]
Salut, désolé pour le temps de réponse. 
Le fichier n'existe plus :/ et depuis, beaucoup d'amélioration sur l'invocation d'événements ont étés mis en place ! 
Cordialement !
