### ISSUE TITLE
Comment utiliser use_reflection?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#169]
Bonjour !

J'ai testé la commande use_reflection... et je dois vraiment faire n'importe quoi, puisque je n'ai aucun résultat avec (ni message d'erreur, ni reflet).

J'ai, dans un événement en processus parallèle, entrer ce script (sur ma map concernée) :
p @use_reflection
p @reflection_properties

retour : "nil".
(Je sais pas trop à quoi servent ces variables globales, lol.)

En tout cas, j'ai 0 résultat. Comme si un truc dans les scripts de RME passait au-dessus du script de map_onload...

Je trouve aussi dommage que l'on doive tapisser d'événements pour se servir de maps_onload + use_reflection. :<
J'ai peur de rapidement affronter du lag...

Bon courage ! o/

**Comment by xvw** [comment]
```
p @use_reflection
p @reflection_properties
```
ne fonctionnera pas. Je dois écrire un tutoriel pour expliquer comment ça fonctionne. 


> Je trouve aussi dommage que l'on doive tapisser d'événements pour se servir de maps_onload. :<
> J'ai peur de rapidement affronter du lag...
Je ne comprend pas de quoi tu parles ?

**Comment by xvw** [comment]
Peut être que tu pourrais me donner ton code "map_onload" ?

**Comment by Zer0zer0x** [comment]
Oh... bien sûr.

map_onload(24) do
  use_reflection(
  excluded: [1,2],
  wave_amp: 2,
  opacity: 120,
regions: {
1 => { wave_amp: 5, opacity: 150},
}
)
end

Pardon.

**Comment by xvw** [comment]
Hmmm je regarde ça AU plus vite :)

**Comment by Zer0zer0x** [comment]
Merci à toi.

**Comment by xvw** [comment]
> Et pour ce qui est de tapisser d'events, dans le cas de use_reflection, c'est parce que j'avais fantasmé à 
>l'idée que l'on puisse directement définir l'autotile ou la zone où l'on reflète tout ce qui est en couche
> B, C, D ainsi que les events ; alors qu'en fait il faut faire un événement par arbre ou autre élément du 
> tileset qui a un reflet, etc (sauf si j'ai mal compris). x)

Enfait, il y a trop de cas particuliers a gerer (... par exemple, avec les arbres de 4 cases, ceux de 2 etc) donc ce n'est pas possible. Par contre, tu peux utiliser un panorama. 

Concernant ton soucis, je pense que c'est parce que ton tileset d'eau (ou de glace) n'est pas transparent ;) tu devrais essayer avec des "trous" noirs à la place d'eau par exemple.

**Comment by Zer0zer0x** [comment]
J'ai effectivement testé sur du transparent, et ça marche bien !
L'erreur venait de moi, je ne savais pas utiliser la commande. :>
