### ISSUE TITLE
Element_rate and co

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#17]
Revoir toutes les commandes 'element_rate'

*     [x] actor_element_rate
*     [ ] armor_element_rate
*     [ ] weapon_element_rate
*     [ ] item_element_rate
*     [ ] monster_element_rate

**Comment by mspawn** [comment]
les element's_rate dépendent des états (qui changent durant le combat), on ne peut donc pas en proposer une implémentation propre telle qu'elle a été initialement pensée. Il faut les revoir en "commande" in_battle. Mais je pense que ce serait plus le rôle du BattleContext de faire ça étant donné que les commandes "in_battle" ne servent qu'a faire de l'extension visuelle; 
Je ferme donc cette issue. Toutes les commandes ont étés commentées et dédocumentées. 
Ciao.
