### ISSUE TITLE
Commande activer/desactiver la course

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#172]
### Edit de @xvw
> Cette issue doit être modifiée pour pouvoir activer et désactiver la course à la demande. 
> Une fois la commande faite, avec les micros événements.

Bonjour !

Je trouve dommage que l'on ne puisse désactiver la course que sur la totalité d'une map...
Serait-il possible de créer une commande qui permette d'aussi pouvoir la désactiver sur certaines zones ?

Merci et bon courage ! o/

**Comment by xvw** [comment]
- [ ] Commande pour savoir si la course est activée ou non 
- [ ] Activer et desactiver la course à la demande.
