### ISSUE TITLE
Choix dans les messages : + de 4 possibilités ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#173]
Bonjour !
J'imagine que le titre de l'issue est déjà plutôt clair... ^^'

Serait-il envisageable de créer une commande RME pour des choix qui dépassent les 4 possibilités ?

Bon courage ! o/

**Comment by Hinola** [comment]
Comme create_commands_window ?

**Comment by BastienDuplessier** [comment]
Y'a moyen de d'en sortir avec create_commands_window. Le soucis c'est qu'actuellement la commande n'est pas documentée.
Il faut qu'on résolve ce soucis.
