### ISSUE TITLE
Commandes pour "utiliser" les objets

### ISSUE THREAD

**Issue by BastienDuplessier** [RMEx/RME#182]
Il manque des commandes pour utiliser les objets sur les personnages.
Il s'agit des commandes pour :
- Tester l'utilisation d'un objet sur un personnage
- Utiliser un objet sur un personnage

**Comment by xvw** [comment]
Ce n'était pas déjà fait ?

**Comment by BastienDuplessier** [comment]
Non pas encore, je ne m'en suis pas occupé.

**Comment by xvw** [comment]
oké, np, j'étais persuadé que ça avait déjà été fait :)
