### ISSUE TITLE
Transitions de téléportation comme dans 2k3 ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#183]
Salut !
C'était un truc que j'aimais bien avec 2k3... La possibilité de varier les transitions de téléportation en téléportation (scrolling, et autres.)

Serait-il possible d'également reproduire la transition de téléportation d'RPG Maker XP ?

Merci d'avance. o/
Bon courage !

**Comment by xvw** [comment]
Tu as regardé ces deux fonctionnalités ? 

- http://rmex.github.io/RMEDoc/#perform_transition
- http://rmex.github.io/RMEDoc/#player_teleport_with_transition

**Comment by Zer0zer0x** [comment]
Ca tue !
Mais je parlais de l'effet de fondu en jouant sur l'opacité... La "Transition" par défaut d'RMXP, quoi. :)

**Comment by Zer0zer0x** [comment]
Je n'ai pas été assez clair ! :c

Je parlais de toutes les transitions super chouettes qu'il y a dans RPG Maker 2003, comme celles-ci, par exemple : 
https://www.youtube.com/watch?v=p39pvF78T4U&feature=youtu.be&t=15
(De 00:15 à 00:28.)

https://youtu.be/asT-x0_x958?t=287
Ou celle-ci.

Et surtout, ce qui m'intéresserait, ce sont les transitions "À la Zelda" (ce qui n'est pas réalisable en événements. :( )
https://youtu.be/Wg6r1t1l_ZE?t=492

Merci ! o/

**Comment by BastienDuplessier** [comment]
Ahah, oui et non pour les transitions à la Zelda.
J'avais réussi à le faire avec une astuce simple : téléportation sans transition. (A l'époque, réalisée à la mano via les scripts, mais toi tu peux utiliser ça : http://rmex.github.io/RMEDoc/#player_teleport)
L'astuce est simple : Au lieu de faire juste ta map, tu fais la valeur d'un écran de mapping en plus sur tous les endroits ou tu veux faire une transition.
L'event de téléportation aura pour role de faire scroller l'écran comme c'est indiqué, puis de faire la téléportation sans transition (instantanée quoi). Le tour est joué.
Bon expliquer ça dans une issue Github c'est pas top, du coup j'vais faire un tuto en plus de ça.

**Comment by Zer0zer0x** [comment]
Bastien : ne te fatigue pas, c'est ce que j'avais déjà fait. :3 
Sauf que je trouvais ça chiant, et que la caméra lock pas forcément parfaitement dans le coin en fonction de la résolution du jeu (surtout quand on la rabaisse, en fait)... des fois la cam se lock, mais on voit des "milieux" de tiles sur les bords. Bref, c'est pas toujours aligné au Tile (avec un "Pas" de 32, si je ne dis pas de bêtise...).

Bref, je l'ai déjà fait comme ça sur un prototype. ^^'

**Comment by xvw** [comment]
On peut fermer l'issue ?

**Comment by Zer0zer0x** [comment]
Oé, en sachant que je risque de créer un plugin pour RME pour faire les transitions à la Zelda... :x 
Désolé...
