### ISSUE TITLE
Reférencer les touches dans la documentation

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#184]
@UlisKore via ce thread http://rmex.forumactif.org/t81-attributs-dans-mouse_triggerkey, me rappelait qu'on ne peut pas savoir quelle est la liste des touches utilisable. Il faudrait donc faire une modification dans la liste des commandes pour l'exprimer !

**Comment by acs-l** [comment]
Sera documenté avec : #264.

(Je laisse l'*issue* ouverte pour ne pas l'oublier)
