### ISSUE TITLE
Nouvelle commande : Pause

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#187]
Ce serais possible d'ajouter une commande qui met le jeu en pause (de la même façon que le menu de base)mais que les événement commun continu de fonctionner ?
En d'autre terme, facilité la création de menu custom.

Merci d'avance.

**Comment by BastienDuplessier** [comment]
Je vais essayer de voir ce que je peux faire, mais je n'assure pas de résultat.

**Comment by acs-l** [comment]
On l'inclut dans #258 (qui ne va pas arriver avant un peu de temps), ou tu veux faire une commande pour répondre rapidement à ce besoin @BastienDuplessier ?

**Comment by BastienDuplessier** [comment]
C'est exactement #258 .
Je close cette issue, c'est presque un doublon.
