### ISSUE TITLE
Commande qui renvoie directement la largeur et/ou la hauteur d'une picture, en pixels

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#189]
Bonjour !
Je songeais à une commande qui renverrait directement la largeur et/ou la hauteur **en pixels** qu'occupe une picture à l'écran, quel que soit son redimensionnement.

Merci d'avance pour une réponse. :)

Bon courage.

**Comment by xvw** [comment]
Salut @Zer0zer0x 
- http://rmex.github.io/RMEDoc/#picture_width
- http://rmex.github.io/RMEDoc/#picture_height

**Comment by Zer0zer0x** [comment]
Je me suis probablement mal expliqué. :)

Par exemple, je voudrais pouvoir faire
SV[1] = picture_pixels_width(ID)

Pour que SV[1] soit égale au nombre de pixels de large de la picture ID. (Soit 200 pour une picture de 200 pixels de large).

**Comment by Zer0zer0x** [comment]
SV[1] = picture_width(100) #100 est l'ID de la picture dont j'aimerais connaître la largeur en pixels
p SV[1]

Marche pas. :(

**Comment by BastienDuplessier** [comment]
Tu peux indiquer ce qui ne marche pas ?
Tu as une erreur ? Tu as un 0 ?

**Comment by Zer0zer0x** [comment]
Script '-EvEx.rb' line 4011: NoMethodError occured
undefined method 'swap_cache' for nil:NilClass

**Comment by xvw** [comment]
tu es sur que tu as bien  l'erreur sur "la dernière version stable de RME" ?
