### ISSUE TITLE
Projet qui crash sur une map un peu lourde

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#190]
"RGSS3 Player a cessé de fonctionner".

Un pur crash en bonne et due forme, quoi...
Ca me le fait dans la forêt, sur la map dont l'ID est 45 ("Foret_1").

Je précise que j'ai un PC pourri qui laggue (13 FPS). Je le dis tout au cas où.

Lien du projet ici.
https://www.dropbox.com/sh/piglt41b8rtudux/AAAOn9_iEcty8McbjdQGfAuja?dl=0

C'est peut-être lié à d'autres scripts ?
Il semblerait que l'antilag de Moghunter ne soit pas toujours apprécié (d'RME ?)...
C'est dommage parce qu'il retire vraiment du lag, pour le coup.

Merci d'avance de checker ! o/

EDIT : 
Et voilà ! J'ai ajouté des invokes sur la MAP 45... et depuis rien ne va plus...
Maintenant, quand on se télép' de la MAP 18, nommée : "Foret_3 [PURSUIT]" à la
MAP 45, nommée : "Foret_1", on est sûr à 100% du crash.

Ca ne me le faisait pas avant que je fasse la Maj d'RME pour pouvoir utiliser use_reflection.

**Comment by xvw** [comment]
Grande map + utilisation de réflexion ? En quelle résolution ?

**Comment by Zer0zer0x** [comment]
Map en 25 * 20.
Résolution 544 * 416.

PC avec un Celeron N2840.

**Comment by Zer0zer0x** [comment]
J'ai beau avoir fait
excluded: [17, 75, 60, 5, 15, 83, 58, 56, 55, 19, 59, 81, 1, 63, 30, 28, 64, 61, 52, 54],

L'invoke "De trop" fait toujours CRASH RM. Ce qui n'est pas le cas sur d'autres maps !
Il semble que use_reflection n'aime pas du tout la présence d'une 30aine (à vue de nez) d'events sur une map en 25 * 20...

**Comment by Zer0zer0x** [comment]
Je viens de tester avec un bon PC où tout tourne à 60 FPS...
Le jeu crash d'un coup sur cette map-là, quand même. :/
C'est sûrement use_reflection qui a du mal, oui. Je n'ai pas trouvé comment désactiver la commande pour cette map...

**Comment by Zer0zer0x** [comment]
Un "Surplus" d'événements (je trouvais pas non plus avoir complètement abusé mais use_reflection a pas l'air de kiffer au-delà de 30... un truc comme ça).
J'ai retiré quelques papillons et ça va mieux. Snif, mes papillons...

**Comment by xvw** [comment]
C'est uniquement lié à use-reflection ? Si tu n'as pas de reflets du tout ça ne plante pas ?

**Comment by Zer0zer0x** [comment]
oé. Sans reflet ça crash pas.
