### ISSUE TITLE
Pouvoir forcer une direction avec invoke_event

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#191]
Salut !
Serait-il possible de rajouter un petit champ "Direction" dans la commande invoke_event ?

Bon courage. o/

**Comment by xvw** [comment]
Il existe une commande pour changer la direction d'un événement. Ca devrait suffire.

**Comment by Zer0zer0x** [comment]
J'ai contourné le pb avec, oui.
Ca prend juste quelques lignes en plus, snif ! :'(
