### ISSUE TITLE
Commande choice qui se laisse abuser...

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#192]
Salut !
Quand on rentre "Trop" de choix, la fenêtre de choix finit par sortir de l'écran de jeu...

http://img110.xooimage.com/files/5/8/4/grosrelou-5388630.gif

Serait-il possible d'envisager cette commande autrement ?
Qu'elle génère un menu à plusieurs colonnes quand on "Abuse"... ou fixer un maximum en fonction de la résolution d'écran du jeu ?

Bon courage. o/

**Comment by xvw** [comment]
J'ai pas du tout envie de passer pour un mec ennuyant, mais je pense que tu peux le faire très facilement à la main...
Je ne vois pas de bug, mais de l'abus... (ce n'est pas une critique hein, mais on ne peut pas anticiper toutes les conneries potentielles des utilisateurs)

**Comment by Zer0zer0x** [comment]
Lol !
À voir si quelqu'un serait assez fou pour éditer cette commande quand même...

C'est loin d'être une urgence, certes. C'est juste la première idée qui m'est venue à la découverte d'une commande "choice".
