### ISSUE TITLE
Square_passable et hauts de murs ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#195]
Bonjoir !
Sur ce gif, j'affiche en vert toutes les cases passables dans la direction bas_droite.
La case "Rouge" est en quelque sorte la "Limite", là où il y a un tile infranchissable...

http://image.noelshack.com/fichiers/2017/51/2/1513688021-boubouboubouboubou.gif
Curieusement, sur les hauts de mur, nous n'avons pas le même comportement...

Je suis étonné puisque mon tileset est géré comme suit : 
http://image.noelshack.com/fichiers/2017/51/2/1513688086-boubouboubouboubou2.gif

J'utilise bien la commande : 
square_passable?(x, y)
Zut. :(

Merci d'avance pour vos réponses. ! :D 

EDIT : un "Exemple" encore plus NRV... : 
http://image.noelshack.com/fichiers/2017/51/2/1513689041-vnr.png

**Comment by BastienDuplessier** [comment]
Visiblement on se base sur la commande `passable?` dans Game_Map. Il faudrait qu'on regarde si y'a pas une spécificité dedans.
Je vais m'en occuper.

**Comment by BastienDuplessier** [comment]
En fait, c'est assez spécifique. Ces tiles là sont considérés comme passables malgré ce que tu mets dans ton éditeur de tileset. Si tu positionne ton perso dessus, il va pouvoir se déplacer. C'est pas un bug de RME mais une "feature" de RPG maker du coup, je doute qu'on corrige ce "problème".
Si tu veux tu peux "hacker" en utilisant un carreau invisible impassable sur toutes les zones ou ton personnage n'est pas censé passer. Ca permettra à ton système de marcher.
Sinon faut voir si y'a pas moyen de faire quelque chose avec les numéro de terrain.
