### ISSUE TITLE
Petite coquille dans la doc ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#198]
http://rmex.github.io/RMEDoc/#player_direction
Six jeunes m'abusent, je crois que c'est 8 **POUR LE HAUT** et 2 **POUR LE BAS**.

Donc que "Haut" et "Bas" ont été inversés dans la description de la commande : 

> "Renvoie (ou change) la direction (2 pour le haut, 8, pour le bas, 4 pour la gauche , 6 pour la droite ) du joueur"

À vérifier. :/
Bisous !

**Comment by Zer0zer0x** [comment]
("up")
J'ai édité le post, il était pas clair. :v

**Comment by BastienDuplessier** [comment]
Du coup, s'il y a coquille, ne pas oublier de changer aussi celle là : http://rmex.github.io/RMEDoc/#event_direction
