### ISSUE TITLE
[Nv Commande] Conditions basées sur l'apparence d'un event et autres

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#199]
( Voir aussi #200 )

Salut !
Hier, seul dans mon lit...
Bref, j'ai pensé à l'ajout de nouvelles commandes concernant la gestion de l'apparence d'un héros.

Pouvoir directement obtenir le nom du sprite utilisé pour un event, par exemple

> player_appear

qui renvoie "Actor1"

Et

> event_appear(id)

qui renverrait "People1", ou "Monster"...

Ce qui permettrait de faire des conditions en fonction de l'apparence de l'event... par exemple...

zoubis

**Comment by BastienDuplessier** [comment]
Proposition résumée dans l'issue #201
