### ISSUE TITLE
Demande features : Détection de lvl up

### ISSUE THREAD

**Issue by mioteck** [RMEx/RME#2]
Re-bonjour c'est encore moi !

Cette fois ça serai une fonction qui détecte si un héro monte d'un niveau et renverrai son id.

Merci

**Comment by Grimimi** [comment]
Peut être une commande "last_level_up" qui renverrait le dernier personnage à avoir monté de niveau ?

**Comment by Jauke** [comment]
Peut-être qu'une telle commande empêcherait l'utilisateur de raisonner sur un problème aussi basique, ce qui n'est pas vraiment la philosophie de RME.

N'hésite pas à rejoindre le forum rmex et demander comment faire ce genre de choses. : )

**Comment by xvw** [comment]
Yep. Il existe des fonctions naïve. Mais elles font office de wrapper pour des systèmes plus complexe. 
Je t'expliquerais avec joie comment faire ça ici : http://rmex.github.io/ (clique sur community), mais une commande aussi spécifique n'a pas sa place dans RME...
