### ISSUE TITLE
[Nv Commande] Modif' de l'apparence rapide, simple et flexible

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#200]
( Voir aussi #199 )

Yo !
J'ai pensé à une commande qui serait rigolote (pour moi en tout cas).

Pouvoir faire : 
SV[1] = player_appear
change_player_appearence(SV[1]+"[isometrie]"), par exemple, pour directement passer au nom du sprite utilisé pour le joueur à, par exemple, "Actor1[isometrie]" pour un déplacement en diagonale...

Tout en pouvant faire pareil avec les events...

GL

EDIT : 
À noter que je parle de l'apparence... sur la carte. :)
(Un peu comme quand on utilise "Modifier l'apparence" dans les déplacements d'événement. ^^)

**Comment by BastienDuplessier** [comment]
Hello !

C'est déjà possible avec les héros :
http://rmex.github.io/RMEDoc/#actor_change_appear
http://rmex.github.io/RMEDoc/#actor_character_name
http://rmex.github.io/RMEDoc/#actor_character_index
http://rmex.github.io/RMEDoc/#actor_face_name
http://rmex.github.io/RMEDoc/#actor_face_index

Après, pourquoi pas faire aussi le char pour les évents.

**Comment by Zer0zer0x** [comment]
Je ne savais pas, super cool ! :)
Ca me tranquillise déjà pour un moment...

Merci !

**Comment by BastienDuplessier** [comment]
Tu as besoin de la commande pour les events ? Si oui, on pourrait la faire dans la prochaine release.
Sinon, j'ferme cette issue.

**Comment by Zer0zer0x** [comment]
J'en aurais aussi besoin, pour pouvoir leur faire avoir les mêmes possibilités que le héros et que ça reste cohérent, oui. :)
Désolé d'en demander tant ! :<

**Comment by BastienDuplessier** [comment]
Pour le charset, aucun soucis, on va prévoir ça (j'vais juste créer une issue annexe pour que ce soit plus clair)
Par contre, le faceset c'est quelque chose de défini dans les messages, donc du coup, c'est pas à changer au niveau de l'event.

**Comment by Zer0zer0x** [comment]
J'osef du Faceset, perso' ! ^^
Au pire y'aura toujours moyen de mettre une condition en fonction de l'apparence de l'event et de gérer la boite de dialogue selon. :)

Merci !

**Comment by BastienDuplessier** [comment]
Parfait, je ferme cette issue et j'en ouvre une autre avec juste l'histoire du charset.
