### ISSUE TITLE
Proposer au joueur de modifier le layout du clavier

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#202]
Salut !
Je pense que ce serait sympa d'intégrer à RME la possibilité de modifier le Layout du clavier...
Un peu comme c'était fait dans The Ark Of Gladoria.

http://img110.xooimage.com/files/d/3/8/zgueg-53a43c3.gif

Merci d'avance. c:

**Comment by xvw** [comment]
Salut, c'est le rôle de la touche `F1`

**Comment by Zer0zer0x** [comment]
C'est hyper abrupt et cheum via la touche F1. :(

**Comment by BastienDuplessier** [comment]
Je ne pense pas que ce soit le rôle de RME de gérer ce genre de chose.
Je pense qu'il existe plein de scripts qui vont permettre de gérer ça.
Si tu as besoin d'une "interface" entre un script de keyboard layout et RME (pour pouvoir utiliser les touches via RME) on pourra peut être t'écrire un plugin (qui sera dispo via RMEBuilder).
