### ISSUE TITLE
Koman on fé ? Stocker une touche de clavier dans une variable

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#203]
Salut !
Quand je fais L[:key] = "A"

puis dans une condition : 
key_press?(:L[:key])

Il me retourne un message d'erreur. :(
'Game_Interpreter' line 450 : TypeError occured
can't convert Symbol into Integer

Snif...

Comment on fait ? :(
Bisous !

**Comment by BastienDuplessier** [comment]
C'est normal. Le soucis se trouve au niveau de `:L[:key]`, ici on note l'utilisation de `[:key]` qui est un raccourci pour cette écriture `.[](:key)`. Donc si on prend ça dans l'ordre ça fait d'abord `:L` puis le `[:key]`. Donc ça essaye de faire un [] sur un symbol (:L) et comme tu passe un symbol et pas un int, il est pas content.

Du coup pour résoudre ton soucis, il faut faire ça `L[:key].to_sym`.

**Comment by Zer0zer0x** [comment]
Je n'ai sûrement pas bien compris...
J'ai tenté key_press?(:L[:run_key].to_sym) et ai le même message d'erreur. :x

**Comment by Zer0zer0x** [comment]
Merci !
J'ai tenté key_press?(L[:run_key].to_sym), ça fonctionne. ^^

**Comment by BastienDuplessier** [comment]
Le soucis vient du `:` que tu mets devant le `L`.
En gros tu demandes à chercher quelque chose dans un Symbol (:L)

**Comment by BastienDuplessier** [comment]
Parfait. Je ferme donc cette issue.
