### ISSUE TITLE
Commande pour connaître la position et la direction des followers ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#204]
Salut !
Existe-t-il une commande pour connaître la position des followers, ainsi que la direction dans laquelle ils regardent ?
Il me semble que ça avait été géré par un illustre inconnu (MetaOwl, je crois ?), mais j'ai oublié le nom de la commande ! :(

Merci. :)

**Comment by xvw** [comment]
Je crois que tu peux te servir des commandes d'événements, mais à la place d'un event-id, tu peux mettre `follower(n°)` à la place

**Comment by Zer0zer0x** [comment]
Super ! :)
Ca fonctionne pour la direction, et pour les coordonnées X et Y !
En espérant qu'il n'y aura pas de souci avec ce qui est prévu dans l'issue #201 , ce serait trop cool de pouvoir totalement gérer l'apparence des followers (vu que je me cogne un système 8 directions). :)

**Comment by BastienDuplessier** [comment]
J'vais noter de faire des tests dessus.
Je ferme étant donné que la réponse a été donnée.

**Comment by BastienDuplessier** [comment]
Mais je suis en train de me demander si modifier l'apparence des héros qui sont followers ne marchait pas aussi @Zer0zer0x

**Comment by Zer0zer0x** [comment]
> Mais je suis en train de me demander si modifier l'apparence des héros qui sont followers ne marchait pas aussi @Zer0zer0x

J'y avais même pas pensé, haha !
