### ISSUE TITLE
Une démo de create_commands_window ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#205]
Salut !
http://rmex.github.io/RMEDoc/#create_commands_window

Je ne comprends pas la partie "hash". :(
Quelqu'un pour m'expliquer ? (: 

Merci ! ^^

**Comment by xvw** [comment]
Très bonne idée ! 
@BastienDuplessier tu n'avais pas commencé un "menu custom" justement ? 
(Ce n'est pas une mise sous pression hein, c'est de la curiosité)

**Comment by BastienDuplessier** [comment]
Yo.
Je suis en train d'écrire une réponse.
Pour le menu custom, c'était un inventaire. Le soucis étant que les fenêtres ne sont pas du tout adaptées à ce genre de chose. Donc j'ai laissé tombé l'inventaire complet.

**Comment by xvw** [comment]
Ok :) 
Je tâcherai de faire un exemple pour la démonstration :)

**Comment by Zer0zer0x** [comment]
Erf...
Ca tombe mal, j'espérais pouvoir justement faire un inventaire ainsi qu'un menu custom de choix des attaques.
J'attends la démo avec impatience ! ^^'

Merci. :)

**Comment by BastienDuplessier** [comment]
Voici un exemple ici : http://rmex.forumactif.org/t28-coffre-de-stockage

Il s'agit d'un hash qui se présente sous la forme suivante : `{"Commande" => options}`, options étant soit une action qui représente ce qui sera effectué lors du choix, soit un autre hash qui représente la configuration de la commande (avec les clés `:action` pour ce qui sera réalisé lors de la validation du choix et `:enabled?` qui permet de définir si l'action est sélectionnable ou pas)

Exemple :
```ruby
create_commands_window(1, 0, 0, 200,  
"Déposer un objet" => {
     enabled?:(SV[3] < SV[1] && length(items_possessed) > 0),
     action: action{
              SS["Z"] = true
              SS["A"] = true
            }
     },  
"Retirer un objet" => {
     enabled?:(SV[3] > 0),
     action: action{
              SS["Z"] = false
              SS["A"] = true
             }
     }
)
```

**Comment by Zer0zer0x** [comment]
Intéressant !
Je vais me pencher dessus. ^^
