### ISSUE TITLE
Create_commands_window ne verrouille pas les déplacements ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#206]
Salut !
Je viens d'utiliser la commande create_commands_window.

Malheureusement, elle ne bloque pas les déplacements du héros, ni ceux des autres événements... Bref, elle ne se comporte pas comme une commande de choix par défaut RM. :(
(Je l'exécute dans un processus parallèle.)

J'aimerais savoir s'il serait possible de rajouter un argument à la commande create_commands_window afin de choisir de garder ce mode "N'interrompt pas le jeu" ou de faire le contraire.

Ou alors... de créer la commande de l'issue #187 ? :)

Merci d'avance pour votre réponse ! ^^

**Comment by Zer0zer0x** [comment]
Je remarque aussi que ces fenêtres de commande ne se ferment pas lorsque l'on appuie sur la touche Echap/X/... :(
Serait-il possible de spécifier dans un argument si l'on veut ou non pouvoir quitter la fenêtre par la touche Echap/X/... ainsi que le choix qui est fait en cas "D'annulation" (du coup) ?

GL. o/

**Comment by BastienDuplessier** [comment]
En fait, il faut que tu utilise les évents de base pour gérer l'attente. Faut que tu lances un Démarrage Auto quand tu lances la création de ta fenêtre.
T'as pas trop d'autres choix.

Pour fermer la fenêtre de choix, il faut implémenter la commande manuellement. J'ai pas de Windows sous la main. J'essaye de te montrer ça ce soir.

**Comment by Zer0zer0x** [comment]
J'ai tout fait manuellement en attendant... je trouve dommage que la commande ne propose pas de faire ça nativement. :x 
Ne t'embête pas, j'ai déjà fait ce qu'il faut pour que ça fonctionne tout de même. ^^

**Comment by BastienDuplessier** [comment]
Parfait. Je ferme l'issue alors :)

**Comment by Zer0zer0x** [comment]
Arf !
Quand on utilise un autre événement en Automatique, avec des boucles dedans, ça déconne... :/

Deux événements en "Automatique" lancés en même temps "S'attendent" mutuellement (donc si y'en a un qui boucle, l'autre ne se lance pas avant que l'autre soit sorti de sa boucle, etc.). Je crois... En tout cas ça, ça a changé depuis XP... :/

Du coup je peux pas cumuler certaines mécaniques de Gameplay sur la map avec le menu créé par create_commands_window... ou alors il faudrait dédier une page à l'autre événement Automatique en question, exprès, pour qu'il passe alors en processus parallèle avec le même code... ? (solution d'event maker peu consciencieux...)

**Comment by BastienDuplessier** [comment]
Je pense que c'est plutôt logique, si tous les évents en automatique s'exécutaient en même temps, ça serait le foin.

T'as essayé de mettre tous tes traitements dans des events communs et de les appeler tous à la suite dans un évent en Démarrage Auto ? C'est ce que j'avais fait pour mon inventaire et ça marchait bien.
En gros, ne pas avoir N évents en démarrage auto mais un seul qui pilote tout le reste.
