### ISSUE TITLE
Condition S[4988..4999] == false ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#207]
Bonjour !
Via une condition event, j'ai inséré le code suivant : 
S[4988..4999] == false

et essayé également : 
not S[4988..4999]

La condition n'est jamais remplie. Où ai-je fait une erreur ? :( 
Merci d'avance. :3

**Comment by BastienDuplessier** [comment]
Tu ne peux pas utiliser des ranges dans les S, SV, SS, V etc.
Si ton but est de vérifier l'état de tes variables utilise donc les méthodes all? et any? des ranges.
```ruby
# Pour le test, je remplis les variables avec true
(4988..4999).each { |i| S[i] = true }
# Utilisation des méthodes #all? et #any?
(4988..4999).any? { |i| S[i] }
# => true
(4988..4999).all? { |i| S[i] }
# => true
# Modification d'une des variables
S[4988] = false
# Utilisation des méthodes #all? et #any?
(4988..4999).any? { |i| S[i] }
# => true
(4988..4999).all? { |i| S[i] }
=> false
```

**Comment by Zer0zer0x** [comment]
Ca fonctionne, merci. ^^

**Comment by Zer0zer0x** [comment]
Et dans le cas des SV ? ^^'

**Comment by BastienDuplessier** [comment]
Le code que j'ai mis au dessus est valable pour tous S, SS, V et SV.
Il n'y a pas de moyen de faire une assignation en masse pour le moment.
@xvw est ce que ça vaut le coup d'après toi ?

**Comment by Zer0zer0x** [comment]
Si je puis me permettre...
https://github.com/RMEx/RME/wiki/Variables-et-interrupteurs#jutsus-compl%C3%A9mentaires

**Comment by BastienDuplessier** [comment]
En effet, je me suis trompé.
Je modifie mon code.
Le range marche pour les S, mais pas pour les V.
J'vais faire une update pour régler ce soucis.

**Comment by xvw** [comment]
ça fonctionne pour les variables aussi. 
Mais pas pour les variables locales.
