### ISSUE TITLE
Problème avec la commande in_area?

### ISSUE THREAD

**Issue by MrBSmith** [RMEx/RME#210]
Hello,

je voulais tester les créations de zones avec RME pour faire un système de brouillard de guerre.
Du coup j'ai crée une zone autour du héros que j'ai stockée dans V[1], mais quand je fais:
`Condition: Script: in_area?(V[1], event_x(@event_id), event_y(@event_id))`

RMvxAce me renvoie l'erreur suivante:
![sans titre](https://user-images.githubusercontent.com/34774144/34303403-6bbe8acc-e735-11e7-871b-fc06b99b39d3.png)

Le tout dans un projet vierge.

Une idée d’où vient le problème?

Merccciii

**Comment by BastienDuplessier** [comment]
Tu peux nous donner le code que tu as utilisé pour créer la zone stp ?

**Comment by BastienDuplessier** [comment]
Ok, je vais de faire un test simple et j'ai la même erreur que toi.
Je corrige ça.

**Comment by BastienDuplessier** [comment]
Après, une rapide étude de la fonction in_area? il se trouve qu'en fait cette commande ne peut pas être utilisée avec les zones de RPG maker.
Si tu veux utiliser les area, il faut utiliser les commandes de création d'aires telles que : http://rmex.github.io/RMEDoc/#create_rect_area

Exemple :
```ruby
area = create_rect_area(0, 0, 100, 200)
in_area?(area, 50, 50) # => true
in_area?(area, 800, 0) # => false
```
