### ISSUE TITLE
Nouvelle commande : dash_inprogress?

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#211]
Hello ! 
Il existe différentes commandes pour gérer le dash, mais aucune pour détecter si le dash est en train d'être utilisé. 
Ce serait possible de l'ajouter et qu'en toute logique, elle s'active uniquement lorsque l'on appuie sur la touche du dash ET que l'on se déplace ?

Merci d'avance :)

**Comment by BastienDuplessier** [comment]
Je pense que tu peux t'en sortir avec les commandes de détection de touches.
Genre pour savoir si le personnage est en train de courir tu vérifie si la touche Shift est appuyée.
Pour savoir si le joueur bouge tu peux utiliser cette commande : http://rmex.github.io/RMEDoc/#player_moving?
