### ISSUE TITLE
is_menu_enabled?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#212]
Joyeux Noël ! :)
Je n'ai pas trouvé de commande dans la doc' permettant de savoir si l'accès au menu est autorisé ou non...

Existe-t-elle ? Serait-elle ajoutée à la prochaine version ? :)

Merci d'avance pour votre réponse. ^^

**Comment by BastienDuplessier** [comment]
Ca pourrait être une bonne idée. Je ne sais pas si on peut l'inclure dans la prochaine release cependant.
En attendant, tu peux utiliser la commande script pour avoir cette info : `$game_system.menu_disabled`
