### ISSUE TITLE
Killer de menu par défaut

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#213]
Salut ! :)
Serait-il possible de créer un killer du menu par défaut RM ? :)

Quelque chose qui permettrait de remplacer l'appel du menu par un événement commun, par exemple ? :3 
Merci d'avance ! o/

**Comment by BastienDuplessier** [comment]
Je ne pense pas que ce soit quelque chose d'utile.
Tu peux tout simplement Désactiver l'accès au menu et ensuite mettre un évent commun qui guette l'appui sur la touche du menu pour activer ton propre menu.

**Comment by Zer0zer0x** [comment]
Le problème est que tu dois remettre en place les conditions qui sont déjà gérées par RM pour que le menu ne s'ouvre pas à n'importe quel moment... :(

**Comment by BastienDuplessier** [comment]
Limite, le mieux serait de le faire en script.
Mais ça ne devrait pas faire partie de RME.
Peut être limite un petit plugin.

**Comment by xvw** [comment]
Tu peux le faire facilement avec un événement map_onload sur toutes les cartes
