### ISSUE TITLE
J'ai update RME à l'instant...

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#214]
Script -EvEx.rb line 631: 
NoMethodError occured undefined method '<=' for nil:NilClass

:(

Des bisous.

**Comment by BastienDuplessier** [comment]
C'est bizarre. Je regarde ça sur un projet vierge.

**Comment by BastienDuplessier** [comment]
Je viens de regarder sur un projet vierge. Aucun soucis.
Tu es sur de ne pas avoir modifié des scripts ?

**Comment by Zer0zer0x** [comment]
Je n'ai pas testé sur un projet vierge.
Ce que je vois, c'est que le projet fonctionne et se lance, avec son contenu, ses scripts, etc, mais que quand je mets à jour RME, il crash tout juste au moment d'afficher l'écran titre...

**Comment by BastienDuplessier** [comment]
Envoie ton projet stp. J'vais faire des tests dessus.

**Comment by Zer0zer0x** [comment]
Sure.
https://www.dropbox.com/sh/5x7few4vqjbman9/AACNOcdpwMGniCRA9ZWbXkzUa?dl=0

**Comment by BastienDuplessier** [comment]
Aucun soucis.
J'update RME via RMEBuilder :
```ruby
update RME
build
```

**Comment by Zer0zer0x** [comment]
Je viens de faire pareil et j'ai un message d'erreur...
Etrange...

Je re-télécharge RME Builder.

**Comment by Zer0zer0x** [comment]
C'est un mystère... ;_;
J'ai toujours ce message d'erreur après les splashs screens...

Je pense que nous verrons ça quand la prochaine release d'RME sera terminée. ^^'

**Comment by BastienDuplessier** [comment]
Ok, je viens de le trouver. Je regarde ce qui pose soucis.

**Comment by BastienDuplessier** [comment]
Ok, le soucis est lié à un script que t'as ajouté à coté et qui écrase comme un sagouin les modifications de RME.
Déplace le `OPACITY_Window` au dessus des scripts RME.
De manière générale mets les scripts des autres scripteurs au dessus de RME. Ils s'amusent généralement à écraser les autres scripts (même ceux de base) sans essayer de garantir la compatibilité avec le reste.

**Comment by Zer0zer0x** [comment]
Super ! ^^
Oki. :)

**Comment by Zer0zer0x** [comment]
Justement, ce serait possible de se débarrasser d'Opacity_Window en créant une commande "Opacity_Windowskin(integer)" qui permettrait de changer l'opacité des fenêtres ? :)
(Dois-je ouvrir une issue à ce sujet ?)

**Comment by BastienDuplessier** [comment]
Oui, ouvre une nouvelle issue stp.
On verra si on réalise cette demande. On verra avec @xvw

**Comment by xvw** [comment]
elle est déjà prévue (je crois)
