### ISSUE TITLE
Condition avec actor_character_index

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#216]
Hello !
J'ai fait le test sur un projet vierge.
Une condition : actor_character_index(0) == 1

Renvoie un message d'erreur.
http://img110.xooimage.com/files/0/a/d/testrmeprojetvierge-53ad0af.png

J'ai peut-être fait l'autiste ? xD
Merci d'avance pour vos réponses. :3

**Comment by xvw** [comment]
Il me semble que l'index est celui dans la base de données. Donc ça commence à 1.
