### ISSUE TITLE
Improve Chenille

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#22]
En voulant créer une petite mise en scène ou même d'autres petits systèmes, la chenille de base d'RMVX Ace m'a parfois limité... impossible de jouer une émoticône ou de faire sautiller un follower, c'est plutôt relou. Et lorsque l'on fait sauter le héros par-dessus un obstacle, les persos de la chenille ne vont pas sauter et faire de même, mais vont trouver ça esthétique de juste tout défoncer en marchant et en traversant les murs. Enfin bref, c'est pas très très cool. :D

**Comment by metahowl** [comment]
Bonjour, je suis un novice dans les contributions à RME, et même si je comprend les premiers points de ta requête. Je comprend mal comment il serait possible de faire aussi sauter les personnages en chenille, il faudrait trouver les cases adjacentes vides et ça risquerait de créer des ennuis (par exemple une case proche infranchissable).

**Comment by Grimimi** [comment]
Coucou, @metahowl à implémenté un contrôle des followers, visible ici  : https://github.com/RMEx/RME/pull/25 je pense que c'est une bonne piste pour ce que tu veux faire ?

**Comment by Grimimi** [comment]
Est-ce que cette issue peut être fermée ou alors selon toi il manque des choses ? @Zer0zer0x

**Comment by Zer0zer0x** [comment]
Justement, je viens de revenir et je me demandais pourquoi elle n'était pas encore fermée. :)
Merci pour tout, Metahowl et Grim ! :)
