### ISSUE TITLE
call_title_screen et SkipTitle ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#220]
Salut !

J'utilise la commande call_title_screen dans un événement en processus parallèle, et cette commande me renvoie à l'écran titre par défaut malgré le fait que j'utilise le SkipTitle de RME (avec le fichier CSV convenablement édité).

Merci d'avance pour vos réponses. :3 

Bonne année !

**Comment by xvw** [comment]
Ce n'est pas un bogue. Le but du "skip title" c'est de pouvoir "éviter l'écran titre". (Pour faire des splash screen ou un écran titre personnalisé en utilisant la commande `start_new_game` par exemple).
Pour "repartir" à ton écran titre "custom", il suffit de faire une téléportation vers ta map de démarrage.

**Comment by Zer0zer0x** [comment]
Oki ! :)
