### ISSUE TITLE
Je n'arrive pas à utiliser event_priority

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#221]
Bonjoir !

Je n'arrive pas à utiliser event_priority
J'ai beau faire : 
`event_priority(me, 0)
`
ou
`event_priority(2, 0)
`
Le joueur ne veut pas marcher dessus. :( 

Merci d'avance pour votre énorme soutien. :3

**Comment by Zer0zer0x** [comment]
Bonsoir,
J'ai bien update RME à l'instant.

J'ai toujours le même problème... :/
Est-ce normal ? ^^'

**Comment by xvw** [comment]
Non regarde dans ton éditeur si tu es bien en 1.2.0
