### ISSUE TITLE
[Doc] Les valeurs par défaut de Events_buzzer_properties ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#231]
Bonjour !
http://rmex.github.io/RMEDoc/#events_buzzer_properties

Je n'ai pas les valeurs par défaut sur cette section de la doc'...
Du coup c'est un peu embêtant.
Est-ce référencé ailleurs, dans la doc ? :)

Des bisous !

**Comment by xvw** [comment]
Il ny a pas de valeur par défaut.

**Comment by Zer0zer0x** [comment]
ha, dans EvEx ligne 1350, je vois : 
```
  def  setup_buzzer
    @buzz           = 0
    @buzz_amplitude = 0.1
    @buzz_length    = 16
  end

```

Je pensais donc que tant qu'on fait buzz(0) sans jamais utiliser events_buzzer_properties, c'étaient ces valeurs-là qui étaient employées.

**Comment by xvw** [comment]
et ce n'est pas le cas ?

**Comment by Zer0zer0x** [comment]
:3
