### ISSUE TITLE
SE et BGS

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#232]
Salut !
Cette issue comporte des questions et des suggestions...

Tout d'abord, 
Pourquoi une seule BGS ?
Pourquoi ne pas pouvoir en jouer plusieurs, sous la forme : 

`bgs_play(ID, blablablablablabla)`

(La BGS RPG Maker ayant pour ID "0", par exemple).
J'ai toujours trouvé ça nul de ne pouvoir en jouer qu'une... de devoir bricoler des trucs avec des SE à côté... :/

Ensuite : 
Comment fonctionne exactement la commande "Stopper l'SE" dans RPG Maker ?
Arrête-t-elle tous les SE en cours ?
Un seul "spécifique" ?
Si oui, lequel, le dernier joué ?

Si cette commande s'avère très très nulle, serait-il possible de rendre cette commande "Stopper le SE" plus précise, en pouvant aussi désigner des SE avec un ID ? :)

Des bisous.

**Comment by xvw** [comment]
Hélas, ça impliquerait trop de modifications, désolé ;)
