### ISSUE TITLE
Des questions sur ground?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#233]
Yo !
Je pense d'avance connaître la réponse...

Quand on utilise la commande ground, c'est super cool.
Mais elle ne prend pas en considération les autotiles de flotte.

http://img110.xooimage.com/files/b/7/c/issou-53bcf16.png

Du coup, au niveau des passabilités, c'est un peu ambigu.

Ce que je fais à l'état actuel : 
```
SL[:x_verif] = event_x(me)
SL[:y_verif] = event_y(me)

Si héros regarde vers le bas
SL[:y_verif] += 1
end #même si c'est du pseudo-code, on va faire genre

...

SL[:tile_a] = tile_id(SL[:x_verif], SL[:y_verif], 0)

If ground?(SL[:x_verif], SL[:y_verif]) or SL[:tile_a] >= 1552 and SL[:tile_a] <= 1663
# * ... Terre ferme
end #même si c'est du pseudo-code, on va faire genre
```

Non seulement je ne suis pas sûr de le faire de la meilleure façon qu'il soit, mais en plus c'est un peu cheum...

Bon, le problème c'est que si l'on voulait rajouter les autotiles de flotte, il faudrait être sûr que le maker ne s'amuse pas à en intervertir, et ainsi de suite...
Du coup j'imagine que tout est perdu. :(

Des bisous.

**Comment by BastienDuplessier** [comment]
Pour éviter de te prendre la tête, tu devrais utiliser soit les numéros de terrain, soit les zones.
De plus, j'ai pas trop compris ton soucis. Y'a pas les autotiles de flotte dans `ground?` ou alors ils y sont et tu ne les veux pas ?

**Comment by Zer0zer0x** [comment]
Oui : ils n'y sont pas.

Le problème des terrains tags, dans VX Ace, c'est que ça me stresse de les utiliser parce qu'y'en a que 8 (de 0 à 7).
Quant aux zones, c'est cool, mais il faut les mettre sur toutes les maps concernées et c'est un peu relou, surtout que d'autres s'en servent pour d'autres trucs et que du coup y'a un moment où ça peut finir par ne plus fit. :/

Voili voilou, des bisous !

**Comment by BastienDuplessier** [comment]
Je vois.
Du coup, tu pourrais nous aider en nous disant quoi ajouter à la commande `roof?` ?

En gros, actuellement la commande c'est ça :
```ruby
    def roof?(x, y)
      tile_id = tile_id(x, y, 0)
      tile_id.between?(4352, 4735) || tile_id.between?(5120, 5503) ||
      tile_id.between?(5888, 6271) || tile_id.between?(6656, 7039) ||
      tile_id.between?(7424, 7807)
    end
```
Ce serait cool si tu nous disais quels tiles ID nous ont échappés dans cette commande.

Merci à toi.

**Comment by Zer0zer0x** [comment]
Je pense qu'on en parlera sur Discord. :P
