### ISSUE TITLE
Des questions sur tile_id

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#234]
Salut !
tile_id c'est super cool, le problème c'est qu'à cause d'un truc très con dans RM (je présume), il nous retourne des valeurs un peu accablantes...
Ce serait possible de savoir les valeurs avec précision, de quoi correspond à quoi ?

Même avec juste des explications en texte... pour finir par en venir à produire des images pour la doc, peut-être ? (concernant ce point-là, je serais ravi de le faire).

Merci. :)

**Comment by xvw** [comment]
Ce lien est assez clair (je crois)
https://forums.rpgmakerweb.com/index.php?threads/autotile-tile-ids.2829/

**Comment by Zer0zer0x** [comment]
Oh putain, cool !
