### ISSUE TITLE
commande plafond?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#235]
Salut !
On a ground?
On a wall?
On en a d'autres encore.
Mais on n'a pas plafond?

Pour l'instant j'y vais comme un porc à coup de : 
`if SL[:tile_a] >= 5900 and SL[:tile_a] <= 7900`

Qui ne doit même pas être exhaustif (cette ligne a été rédigée y'a 2 ans)...

Ce serait possible de garder l'idée de côté de faire une commande plafond? :)
Merci d'avance. :3

**Comment by BastienDuplessier** [comment]
C'est quoi `plafond?`.

**Comment by Zer0zer0x** [comment]
Oh pardon...
En gros, une commande comme ground?, wall?, etc... mais pour ces autotiles-là : 
http://img110.xooimage.com/files/6/8/3/issue-53bcf18.png

Oups...
Et dire que j'avais fait une image pour illustrer ça...

Pardon de l'oubli !

**Comment by BastienDuplessier** [comment]
T'as essayé avec http://rmex.github.io/RMEDoc/#roof? ?

**Comment by Zer0zer0x** [comment]
Ah, non.
J'essaierai.
