### ISSUE TITLE
parallaxe_show_screenshot

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#238]
Salut ! =)

Je me demande si on pourrait créer une commande comme picture_show_screenshot MAIS pour passer un screenshot en parallaxe, ingame. :)

Merci d'avance pour votre réponse ! ^^

**Comment by xvw** [comment]
Hum tu as un "use case" précis ? J'ai du mal à voir l'utilité...

**Comment by Zer0zer0x** [comment]
On en a parlé avec Hinola.
Par exemple, pouvoir voir en "Transparence" l'étage du dessous quand on monte un escalier et qu'il y a du vide...
Si c'est trop imprécis je m'expliquerai mieux.

**Comment by xvw** [comment]
Mais avec ça, le héros serait aussi affiché non?

**Comment by Zer0zer0x** [comment]
Effectivement...
Pas si on active la transparence du héros au moment de prendre la screen. :3
Ce qui ferait une "Saccade" de 1 frame au lancement de la map quasi-imperceptible.

**Comment by xvw** [comment]
Je vais voir si je peux faire quelque chose :)
