### ISSUE TITLE
wait(60.2)

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#239]
Salut !
Quand je fais : 
`picture_move(1, 0, 0, 100, 100, 408.5, false)`

Ca fonctionne.

Quand je fais : 
`wait(408.5)`
Il est furieux que j'utilise une float.

JE SAIS qu'il existe .round, ou encore .to_i

La seule question que je me pose, et sur laquelle je chipote : pourquoi les floats ne marchent pas dans "wait" alors que l'on peut s'en servir dans des attentes de pictures ? :)

Des bisous.

**Comment by BastienDuplessier** [comment]
Dans picture_move, si tu mets le `wait_flag` à false, il n'utilise pas wait.
Si tu le met à true, ça va aussi planter.
En gros, wait attend un nombre N de fois. N étant un entier naturel positif.

**Comment by Zer0zer0x** [comment]
Mais c'est relou. :(

**Comment by BastienDuplessier** [comment]
Bah non.
On ne peut pas faire autrement. Dans wait, on a `n.times { Fiber.yield }`. Ce qui veut dire "On attend n fois".
T'as déjà essayé de faire quelque chose 60.2 fois ?

**Comment by xvw** [comment]
En gros, la notion de "temps" dans RPGMaker (et dans presque tous les logiciels qui ont une boucle de raffraichissement) est définie par des frames. Soit le nombre d'image affichée entre un état et son successeur. 
La frame étant l'unité de mesure la plus petite, il est impossible d'imaginer d'attendre "moins". Donc x.y frames, le 0.y est inaccessible.
