### ISSUE TITLE
déplacement négatifs dans les camera

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#240]
Pour recadrer la carte (malgré des valeurs négatives), proposée par @Zer0Zer0x

**Comment by Zer0zer0x** [comment]
Un "Aperçu" de ce qu'il se passerait si l'on plaçait la caméra en dehors de la map sur la gauche et qu'on la faisait "Revenir" sur le joueur...
http://img110.xooimage.com/files/3/5/d/lkqkjdljdsklqjd-53c07f8.gif
