### ISSUE TITLE
Spritesheet_neighborhood

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#241]
Possibilité de créer un voisinage de cartes

**Comment by Jauke** [comment]
Pourquoi "spritesheet" ? C'est pas plutôt "map_neighborhood" ?
C'est pour avoir plusieurs maps réunies en une seule ?
Tu le verrais intégré comment ?

**Comment by xvw** [comment]
Oué, map_neiqskdqkdqsdqsd. 
Pour les events, j'y pense justement, interdire les migration d'événements, ou alors autoriser les migrations pour seulement certains événements (à configurer et namespacer leurs id's)

**Comment by Jauke** [comment]
Si on voit deux maps sur le même écran, on pourra certainement voir deux events également...

**Comment by xvw** [comment]
Oui mais ils peuvent vivre indépendamment ?
