### ISSUE TITLE
[Question] Utilisation "Avancée" des SV

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#244]
Salut !

Quand je fais, dans un appel de script d'événement ayant pour ID 001...
```
SV[1] = "osef"
p "SV[1]"

```
La console me retourne :
`SV[1, 1]`

Cela signifie-t-il que je peux en fait utiliser les variables locales d'un événement à l'autre comme les interrupteurs locaux... voire d'une map à l'autre ? :D

Des bisous. :)

**Comment by BastienDuplessier** [comment]
Pour ta première question, `p "SV[1]"`, normalement ça doit afficher dans la console `SV[1]`
Ensuite, Normalement, oui, tu peux chopper les SV et SS de n'importe quel évent de n'importe quelle map, petit lien d'explication : https://github.com/RMEx/RME/wiki/Interrupteurs-locaux-et-variables-locales

Comme je pense avoir répondu à ta question, je me permets de fermer le ticket.

**Comment by Zer0zer0x** [comment]
Ce n'était pas dans un "Déplacer l'événement", mais bon, ne nous fâchons pas...
Ca m'a permis une découverte  incroyable. La révélation de ma vie.

Je vais pouvoir créer des interdépendances ultra cheums grâce à vous !!
