### ISSUE TITLE
... Retour à l'écran titre... :)

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#245]
J'ai créé une map "Splashscreens" sur laquelle je fais démarrer le jeu en affichant des splashscreens...
Premier lancement, nickel, tout va bien : 
http://img110.xooimage.com/files/4/6/0/boubouuu-53c8527.gif

Lancement depuis le menu... : 
http://img110.xooimage.com/files/a/f/c/boubouuuuuuuuu-53c852b.gif

Il reste la map floutée qui était en arrière-plan du Menu... Et elle passe par-dessus ma map "Splashscreens". On le remarque quand je rappelle l'écran titre, puisque ça efface même ma picture toute noire d'ID 001.

Ma map Splashscreens est toute noire aussi. Pas juste le "Damier" RM VX Ace.
Du coup, ça vient peut-être de RME... ou d'un script de merde que j'utilise.

C'est embêtant. :/

Des bizous.

**Comment by BastienDuplessier** [comment]
Tu pourrais tester ça sur un projet vierge avec juste RME stp ?
Je ne pense pas que RME touche à ce qui est concerné par ton problème.
J'vais quand même jeter un oeil au code pour être sur...

**Comment by Zer0zer0x** [comment]
ok gogogo
je te fais un rapport quand c bon

**Comment by Zer0zer0x** [comment]
Sur projet vierge je ne rencontre pas le problème.
En unsafe non plus.

Cheum.
Je regarderai de + près.

**Comment by BastienDuplessier** [comment]
Au pire, upload ton projet histoire qu'on regarde ça.

**Comment by Zer0zer0x** [comment]
Honnêtement, je pige pas ce qu'il se passe du tout.

**Comment by Zer0zer0x** [comment]
Autant pour moi, j'ai trouvé.

En fait, ma map de splashscreens était belle et bien transparente.
En la remplissant avec un tile noir à la place du "Damier" RM, ça corrige le souci...

Vraiment désolé.
Du coup, ça reste un "Bug" ou pas ? aha.

Lien d'une démo AVEC le bug.
Il faut maintenir Shift enfoncée pendant un bref moment, genre 4 secondes, sur l'écran noir au début du lancement du jeu.

https://www.dropbox.com/sh/52y0kmtowcjfpt9/AACo9BYvWUpTjYdFspf3jsiAa?dl=0

**Comment by BastienDuplessier** [comment]
Etant donné que RME n'est pas en cause je ne pense pas qu'on ait quelque chose à faire ici.
Content que tu aie pu régler ton souci.

**Comment by Zer0zer0x** [comment]
J'avais pas fait les bons tests sur projet vierge (c'est-à-dire avec une map transparente en map de tout début de jeu, la map appelée par le fichier CSV de SkipTitle.)

RME serait donc impliqué, en fait... hihii...

**Comment by BastienDuplessier** [comment]
Bon. Je vérifierais dans la semaine l'implication de RME dans ton problème.

**Comment by xvw** [comment]
@ZangtherRGSS3 du neuf ?

**Comment by BastienDuplessier** [comment]
Nope pas encore. J'essaye de voir ça quand j'aurais un moment pour bosser dessus :)

**Comment by Jauke** [comment]
Sujet évoqué et à méditer dans #258

**Comment by BastienDuplessier** [comment]
J'ai trouvé le soucis.
En gros, y'a un retour custom qui était fait au niveau du Game_End, le background n'était pas clean correctement.
Je vais pousser une solution très simple, basée sur la nouvelle commande : `reset`

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
