### ISSUE TITLE
Savoir si un événement en démarrage automatique est en train de tourner

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#246]
[Cette demande est ultra-personnelle, elle correspond à la création d'un système de mutex avec certains paramètres précis, pour les event makers. Mais surtout pour moi, en fait. L O L]

SALUT !

Serait-il possible de rajouter une commande dans RME pour savoir si un événement en démarrage automatique est en train de tourner ? Genre : is_automaticEV_running?
Ce serait super gentil ! :)

Des bisous !!
Bon courage !

**Comment by BastienDuplessier** [comment]
Tu peux le faire via une variable, non ?

**Comment by Zer0zer0x** [comment]
À rajouter à chaque EV en démarrage auto du projet ?
Désolé, mais c'est hors de question. :(

**Comment by Zer0zer0x** [comment]
À rajouter à chaque EV en démarrage auto du projet ?
Désolé, mais c'est hors de question, pour ma part. :(

C'est une source d'oublis, d'étourderies, de bugs ; en bref : l'horreur. :/

**Comment by Jauke** [comment]
Tu dois bien connaître les conditions dans lesquelles ton événement en mode automatique est en exécution ou non... N'oublie pas que tu peux récupérer par exemple la valeur du switch local d'un autre événement.

C'est quoi ton problème, plus précisément ?

**Comment by Zer0zer0x** [comment]
C'est Boubou qui voudrait créer un événement commun en démarrage automatique qu'on activerait que s'il n'existe pas d'autre événement en démarrage automatique qui tourne à un instant t, afin de bloquer certaines interactions entre le joueur et le jeu...

**Comment by Jauke** [comment]
Mais tu peux avoir plusieurs événements automatiques qui tournent en même temps...

**Comment by Zer0zer0x** [comment]
Sous 2k3, oui.
Plus sous Ace. :)

**Comment by Jauke** [comment]
A ta place j'aurais prévu d'avance un switch pour activer/désactiver la possibilité pour cet événement commun de se déclencher pendant chaque événement, j'imagine qui c'est un processus parallèle qui te pose problème...

**Comment by Zer0zer0x** [comment]
Je demande la possibilité d'envisager une nouvelle commande, pas qu'on m'apprenne à maker. Dsl.

**Comment by Zer0zer0x** [comment]
:'(

**Comment by Grimimi** [comment]
Je pense que l'idée peut être utile dans la construction de système complexes. 
En effet, je pense qu'on a souvent l'habitude de ne faire qu'un seul événement 
commun qui gère, un peu à la manière d'une machine à état, tous les embranchements
possibles. Cependant, je ne suis pas sur que ce soit du code idiomatique. Donc je 
propose d'écrire une commande qui permettrait de renvoyer l'événement automatique 
qui a la priorité sur les autres. 
Pas d'oppositions ?

**Comment by Jauke** [comment]
Sinon dans rm2k3 il me semble que tous les événements en mode automatique peuvent tourner ensemble comme des événements... automatiques en parallèle.

Sauf une flemme ou un oubli dans l’integration des modes automatiques, il y a une raison, un avantage à ce que le dernier mode automatique interromp le précédent ? Personnellement je pense que pouvoir configurer le moteur pour reprenne le comportement de 2k(3) ça serait pas mal. Je pourrais l’integrer à orms si j’y arrive sinon recommander RME avec orms si c’est intégré dans RME

sinon pour une commande renvoyant l’evenment en mode automatique prioritaire ça peut le faire

**Comment by Jauke** [comment]
et je déprécie clairement le fait qu’avec ce nouveau rm on ne puisse plus utiliser la technique de l’événement commun « attendre » en mode automatique, activable / desactivable quand on veut, genre, quand on veut gérer un moteur dynamique en processus parallèle et bloquer momentanément le joueur (très utilisé dans bogossstory)

Alors certes ça devrait fonctionner s’il s’agit exactement de faire mon exemple, mais il peut exister des cas où un autre événement en mode automatique vienne tout flinguer.

Ensuite pour les systèmes complexe qui doivent vraiment tout bloquer sauf son propre cours (menus, par exemple) se référer à #258

**Comment by Grimimi** [comment]
Oh, d'accord. Alors je ferme l'issue et je l'a retire du _pipe_ 1.3.0. 
Merci pour tes retours !

**Comment by Zer0xxxx** [comment]
Vraiment navré de faire remonter cette issue ! (il se trouve que je suis de nouveau confronté au problème).

@hyperaho Je n'ai pas tout compris...

![auto1](https://user-images.githubusercontent.com/36828641/38952305-6ad1ee5c-434b-11e8-9d18-ae997869dcbd.png)

![auto2](https://user-images.githubusercontent.com/36828641/38952307-6ce556ca-434b-11e8-89db-53e5e3175262.png)

![ingame](https://user-images.githubusercontent.com/36828641/38952309-6f264a8e-434b-11e8-88a9-ad92db885c33.png)

**Comment by Jauke** [comment]
Explique nous l'intérêt de mélanger deux modes automatiques et non un mode automatique et un processus parallèle comme tout le monde... Ce genre de problème se résous aisément en gérant bien ses événements à l'origine.

D'où le fait que je n'ai jamais rencontré ce problème, je veille à faire de la programmation qui coïncide avec les règles de base de RPG Maker, qui se vérifient aisément comme tu peux le constater.

**Comment by Zer0xxxxx** [comment]
@Jauke Parce que je n'aborde pas le problème pour _mes_ projets dont je contrôle l'intégralité du code mais de pouvoir intégrer mon code dans les projets des autres ; donc je n'ai pas de contrôle là-dessus.

**Comment by xvw** [comment]
stop stop stop. 
La conversation commence sérieusement à me saouler.
