### ISSUE TITLE
Comment fonctionne "Change resolution" ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#247]
(question)

Bonjour !
J'ai tenté, dans mon projet, d'exécuter de maintes manières la commande : 
` Graphics.resize_screen(30, 30)`

Sans succès. :(
Je n'arrive pas à dépasser les 640 * 480.
Cela me semble curieux...

Je n'appelle peut-être pas la bonne commande ?

Merci d'avance pour vos réponses. :'(

**Comment by Jauke** [comment]
T'as mis unsafe? a true dans SDK.rb ?

**Comment by xvw** [comment]
Il faut utiliser RME en Unsafe. 
Par contre, c'est destiné à construire des "interfaces graphique" grande. Je pense qu'Ingame c'est "dangereux". 
(Par contre, les panoramas sont fixés, je crois qu'il y a juste un soucis sur les transitions)

**Comment by Zer0zer0x** [comment]
Merci @HellperKK ! :)

**Comment by Zer0zer0x** [comment]
Psst...
On peut fermer cette issue, au fait. :3 
Merci à tous ! o/
