### ISSUE TITLE
Tout label L[:ahaha] est par défaut égal à "true" ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#251]
Salut !
J'ai l'étrange impression que les labels sont par défaut égaux à true...

Genre, si je fais une condition event : 

Condition : Script :  `L[:je_nexiste_pas_dans_ton_projet]`
`p "prout"`

"prout" s'affiche dans la console.

C'est moi qui fais des bêtises ? :3

**Comment by BastienDuplessier** [comment]
Si ma mémoire est exacte, ils sont tous à 0.
Seuls false et nil ont la "valeur" de false, tout le reste vaut true.
