### ISSUE TITLE
event_change_character et "character_name"

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#252]
yo !

J'aimerais éventuellement pouvoir utiliser la commande telle quelle : 
event_change_character(me, character_name, 0)

Et qu'elle considère tout simplement "character_name" comme "la valeur actuelle"...
En gros, je voudrais pouvoir utiliser cette commande juste pour modifier l'index, quand je n'ai besoin que de ça. :/

Une idée de comment le faire ? ça marche pas en laissant "character_name".

des bsx

**Comment by BastienDuplessier** [comment]
Tout simplement comme ça non ?
```event_change_character(me, event_character_name(me), 0)```

**Comment by Zer0zer0x** [comment]
GG !
J'ai toujours eu des problèmes avec "(me)" quand il s'agit de le placer correctement... x)

event_x(me), event_character_name(me) ...

Issue close. :3
