### ISSUE TITLE
Invenio et RME

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#253]
Bonjour.

J'ai acheté le script Invenio et l'une de ses fonctions pour tracer un chemin n'est pas compatible avec RME. Serait-il possible de m'éclairer, j'aimerais vraiment utiliser les fonctionnalités des deux scripts simultanément. 

Quand RME est après Invenio ;

https://www.noelshack.com/2018-04-2-1516707790-sans-titre.png

Quand RME est avant Invenio ;

https://www.noelshack.com/2018-04-2-1516707793-sans-titre2.png
https://www.noelshack.com/2018-04-2-1516707790-s.png

Merci.

**Comment by BastienDuplessier** [comment]
Ou est placé ce script dans l'ordre de chargement des scripts ?
S'il est en dessous de RME, place le donc au dessus.

**Comment by Zer0zer0x** [comment]
Comment indiqué, j'ai mis les messages d'erreurs selon si j'avais placé RME en-dessous & au-dessus.

**Comment by BastienDuplessier** [comment]
Ah ok, j'avais mal compris le sens de avant/après.
Envoie ton projet, on va débugger dessus.

**Comment by Zer0zer0x** [comment]
https://www.noelshack.com/2018-04-2-1516708360-event.png

Et c'est l'event. Je vais recréer la configuration sur un projet vierge avec le strict minimum.

**Comment by xvw** [comment]
tu peux donner la ligne 4107 de Evex stp ? (ce n'est pas tout à fait la même que celle sur le code source je pense, à cause des artefacts de RMEBuilder)

**Comment by Zer0zer0x** [comment]
Je t'envoie la configuration buggée en projet : pour le MDP, me contacter sur Discord (Boubou ou Raph).

Lien : https://www.dropbox.com/s/506349opwc5mpgp/Bug%20InvenioRME.zip?dl=0

Visiblement je peux arriver au résultat voulu avec une autre commande (voir map relou), mais ce n'est pas la plus optimale.

**Comment by Zer0zer0x** [comment]
En tant que Boubou, je trouve que la méthode utilise mon ami qui a posté cette issue à la base est vraiment immonde.

J'ai MP Zang' à ce sujet, il regarde de son côté. :3
