### ISSUE TITLE
commande high_walls?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#257]
Salut !
J'aimerais savoir s'il serait possible de créer une commande "high_wallls?" qui agirait comme wall?, mais pour les hauts de mur !

Ce serait génial (pour moi) ! :3
Merci d'avance à vous pour vos réponses, et bon courage !

**Comment by Jauke** [comment]
Non, tu peux le faire toi-même en checkant plusieurs tiles gros flemmard.

**Comment by Jauke** [comment]
Ah non je viens de réaliser x) ça b’e Pas déjà genre roof ?

**Comment by Jauke** [comment]
N’existe* fuck iPhone.

**Comment by Zer0zer0x** [comment]
Merde, j'suis un trizo, Zangther me l'avait déjà dit.

Oui, ça fonctionne nickel.
DSL.
