### ISSUE TITLE
RME next release

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#259]
Yo, on a actuellement beaucoup de choses dans le pipeline de RME 1.3.0, la dernière issue de @Jauke (#258) impliquerait un passage en version 2. Je propose donc que cette issue serve à discuter du périmètre de la prochaine relase de RME ?

**Comment by BastienDuplessier** [comment]
Je pense qu'on peut avancer les deux en même temps.
L'idéal pour moi serait de faire en sorte que le passage de la version 1.x vers 2.0 concerne uniquement cette nouvelle feature de Custom Scene.
A coté on pourrait continuer de réaliser des features/fixes sur les version 1.x en attendant le passage à la nouvelle version.

Dans l'ordre des choses, ce serait sympa d'avoir au moins un truc comme ça :
1.2 => 1.3 ... => 2.0

Donc dans l'idée, réaliser la plupart des issues que l'on a actuellement, réfléchir en même temps à l'implémentation de la nouvelle grosse feature, puis après avoir releasé les dernières versions 1.x, passer sur le dev intensif de la nouvelle feature et passer en 2.0.

**Comment by xvw** [comment]
Actuellement, j'ai l'impression qu'il y a "peu d'issues" qui sont des bugs réellement bloquants et ça représente quand même beaucoup de travail (spritesheet_neighborhood, spritesheet_pictures etc) et donc je me demande s'il ne serait pas plus stratégique de définir une version 2 en prenant en compte les propositions de @Jauke  (qui impliquent pas mal de travail) et de "filter" les issues actuelles pour ne garder que ce qui est nécessaire et utile. Ça permettra aussi de "faire passer la pilule Forge".

**Comment by Jauke** [comment]
Pour les spritesheet_picture qui sont assez chiante à faire elles trouveront leur sens dans la conception d'un CMS/CBS, donc on peut les compter pour la version 2. On peut faire une version 1.3 qui corriger/ajoute les petits trucs demandés, même peux nombreux, et garder le plus gros pour la version 2.

**Comment by BastienDuplessier** [comment]
Oui, y'a pas l'air d'avoir trop de truc très critiques. Du coup, les "grosses features" on pourrait les repousser, les "petites features" on les balance dans une 1.3.
Par contre, je suis pas trop chaud de tout fourrer dans la 2.0.

**Comment by acs-l** [comment]
Je pense que le passage d'une version à une autre et "*quoi intégrer dedans*" est quelque chose de relativement stérile. Pour moi ce sont des décisions qui doivent être prises par celui qui assure la communication autour de *RME* sur les différentes communautés (si ce rôle existe toujours).

De toute façon, ça ne revêt aucune importance à l'heure actuelle puisque le mécanisme pour facilement *builder* *RME* n'est pas encore disponible 😄.

---

À mon sens, c'est la gestion du projet dans sa globalité qui commence à devenir critique 🤒. Techniquement, il y a pas mal de nettoyage / archivage à faire, ainsi que la mise-en-place de deux-trois choses pour avoir des outils clairs et facilement utilisables par tous (si vous êtes disponibles, j'ai des propositions). Autrement, de manière plus général (et c'est ce qui m'interroge le plus), quel est l'objectif de *RME* ? *Être utilisé* ? *S'amuser* ?
