### ISSUE TITLE
Appel player_move_speed dans les déplacements

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#260]
Hello,
Dans une commande "Déplacer un événement : Héros", j'ai mis la commande suivante par appel de script : 
`player_move_speed(SV[1])`

J'ai l'impression que le contenu de SV[1] est mal interprété...
Étrangement, il me met la vitesse du joueur très lente, alors que SV[1] contient 4.

```SV[1] = player_move_speed
p SV[1]
{Déplacement}
```

Zut ! :/

Merci d'avance pour votre réponse.

**Comment by Grimimi** [comment]
Salut, après vérification du code. Il semble qu'en fait, il n' y a pas de bogue. 
Quand tu fais "déplacer le héros". Il considère que c'est le héros qui exécute 
le déplacement. De ce fait, il va considérer que l'événement courant est 0, ce 
qui est tout à fait normal ^^' 

Une bonne solution serait de faire dans ton événement `SV[0, 1] = ta-vitesse` .
