### ISSUE TITLE
Retirer use_reflection d'RME ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#267]
Salut !
Le titre de l'issue fait un peu peur...
En fait, je me demandais s'il ne serait pas mieux de faire d'use_reflection un autre script, à part entière, à installer depuis le RME Builder.

Je n'aime pas trop que ce soit "Imposé" dans RME. :(

Des bisous !!

**Comment by xvw** [comment]
Ça ne me dérange pas de supprimer use_reflection. Par contre, je ne vois pas en quoi il est ... "imposé".

**Comment by xvw** [comment]
Retirer le "use reflection" par défaut !

**Comment by Grimimi** [comment]
Coucou ! Après avoir testé, il me semble (et au vue du code... aussi) que le use_reflection n'est 
pas enclenché par défaut. Est-ce que tu n'aurais pas "oublié" dans un "map_onload" un 
`use_reflection` ? 
Merci pour tes retours !

**Comment by Zer0xxxx** [comment]
salut mec
j'vais t'faire une démo

**Comment by Zer0xxxx** [comment]
Bah écoute j'arrive pas à reproduire le problème que j'avais eu.
Tu peux refermer l'issue.

Je resterai vigilent et si j'ai le moindre truc, je ferai une démo !

**Comment by Grimimi** [comment]
Merci!
