### ISSUE TITLE
Gestion des interrupteurs locaux dans les déplacements ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#27]
o/
Je rencontre un petit soucis avec RME et sa gestion des interrupteurs locaux lorsque je veux directement faire un appel de script dans un déplacement d'event.

Concrètement, j'ai une page d'événement avec comme condition de déclenchement "L'interrupteur local A est activé". Il a une trajectoire prédéfinie (Via Déplacement => Personnalisé => Trajectoire...), dans laquelle j'ai mis l'appel de script suivant (espérant pouvoir clôturer cette page d'event, comme si le déplacement était un processus parallèle) : 
SS['A'] = false

Malheureusement, l'interrupteur local ne se désactive pas. :(
Merci de votre aide ! o/

PS: je tiens à remercier metahowl pour son aide de la dernière fois, ainsi que celle de Grim ! :D

**Comment by Grimimi** [comment]
Merci beaucoup pour avoir trouvé ce bogue qui a été corrigé :)

**Comment by Zer0zer0x** [comment]
Effectivement, tout fonctionne impec ! Merci beaucoup pour avoir trouvé comment corriger ce bogue. :)
