### ISSUE TITLE
Pouvoir effectuer les mêmes effets sur les parallaxes que les pictures

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#270]
Salut !

J'ai une nouvelle suggestion pour ce soir...
On peut "wave", "shake", "rotate", "mast... ouais nan c'est pas drôle en fait" des pictures.
Pourrait-on faire de même avec les parallaxes ?

Il me semble pourtant que c'était possible avec l'EE4...
Je me rappelle d'une démo de Grim avec une lune ultra kitsch reflétée dans l'eau... :)

Des bisous !

**Comment by xvw** [comment]
Pour le "shake" on pourrait, pour le reste, on ne peut pas, désolé :(

**Comment by Zer0xxxx** [comment]
Np np.
On en a parlé, et je pourrais très bien utiliser des pictures pour faire ce que je veux aussi.
