### ISSUE TITLE
import_variable et save_game

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#271]
Salut !
Pour la commande import_variable... serait-il possible d'aussi pouvoir fonctionner au "Nom de fichier" ?

Genre si je mets : SAUVEGARDE_BOOSTEE.rvdata2 dans le dossier de mon jeu, j'aimerais pouvoir faire : 
`import_variable("SAUVEGARDE_BOOSTEE.rvdata2", 42)`

Tout comme j'aimerais pouvoir faire : 
`save_game("SAUVEGARDE_BOOSTEE")`

Merci d'avance les amis, et à la prochaine !
Bye !

**Comment by xvw** [comment]
Autoriser les chaines de caractères comme "nom de sauvegarde"
