### ISSUE TITLE
Feature Request : text_pin

### ISSUE THREAD

**Issue by Princesseuh** [RMEx/RME#275]
Bonjour!

Pendant la [RPGMakerJam 2](https://itch.io/jam/rpgmakerjam2) j'ai fais [Picture of a Daydream](https://princesseuh.itch.io/picture-of-a-daydream) avec VXA et donc RME. 

Le jeu abuse des textes RME pour faire une fonction de "nom en haut des joueurs" (les "joueurs" étant réellement des évènements). Pour résumer rapidement comment je fais ça, j'utilise show_text pour créer le texte et j'update la position avec un map_onprogress qui ressemble à ça (Après suggestion de Zangther) : 

```
map_onprogress(1,7){
  text_position(1, event_screen_x(5) + 15, event_screen_y(5) - 35)
  text_position(2, event_screen_x(4) + 15, event_screen_y(4) - 35)
  text_position(3, event_screen_x(1) + 15, event_screen_y(1) - 35)
}
```
Ça marche pratiquement parfaitement mais on peut clairement voir un tout petit délai dans le repositionnement pendant un scrolling de caméra. [Voici le résultat en vidéo](https://gfycat.com/FluffyScratchyDegus). (J'ai essayé plusieurs façon avant ça, comme par-exemple un event en parallel mais cette façon s'est prouvé étant la meilleure rapidement)

J'en ai parlé à Joke et il a mentionné qu'une fonction `text_pin` comme il existe avec les pictures (picture_pin) réglerais le problème mais je dois avouer que je n'ai jamais utilisé picture_pin (ou même les pictures dans RPG Maker en général pour être honnête) donc je connais pas trop les implications.

Je sais pas si c'est idéal de fixer à une position comme peut-être que directement une fonction pour attacher un texte avec un event pourrait être utile?

Voilà voilà. Thoughts?

**Comment by Grimimi** [comment]
Effectivement ! C'est surprenant que ça ne soit pas déjà fait ! 
C'est dans le pipeline pour la prochaine release !
