### ISSUE TITLE
'tit soucis avec le tueur d'écran titre et les pictures, enfin, je crois

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#28]
J'ai l'impression qu'il y a encore de petits bugs avec le tueur d'écran titre et les pictures... peut-être que le soucis vient de moi, je ne suis qu'un newbie.
Ci-joint une petite démo (le système event du CTSS est cheum, mais seul Dieu peut me juger) avec des textes explicatifs dans la console RM, mais en gros, j'ai le ressenti que les images sont initialisées plutôt bizarrement à partir du "start_new_game".
=> https://www.dropbox.com/s/cq55fidcoc296bl/%5BIssue%20RME%5D%20pwet.rar?dl=0

**Comment by xvw** [comment]
Bon, alors... aha, j'ai testé (durant une de mes pauses), avec et sans le tueur d'écran titre, 
et je n'ai pas constaté de différence du tout. :x

**Comment by hyperaho** [comment]
Je n'ai pas d'erreur non plus. (avec ou sans le title screen)

**Comment by Zer0zer0x** [comment]
Je viens de voir ça avec Nuki, et effectivement, le soucis ne semble pas venir d'RME... j'ai copié/collé les events d'un projet où l'image tournait et s'affichait, et ça a marché alors que le code est littéralement le même partout. Oo

Du coup, je donne ma langue à la chatte.

**Comment by hyperaho** [comment]
C'est rigolo, parce que le processus parallèle se lance... mais pas le "picture_move". Il ne s'exécute "pas du tout"...

**Comment by hyperaho** [comment]
Lol, en fait... c'est de ta faute :P 
tu oublies le paramètre "wait_flag" dans picture_move.

**Comment by Zer0zer0x** [comment]
Oh merde ! x)
Merci. :P
