### ISSUE TITLE
pathfinder : avoid?

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#282]
Salut !
Pour le pathfinder...

Serait-il possible de créer un argument "avoid" afin de spécifier un élément dans le parcours à réaliser, qu'il faudrait éviter d'approcher de trop près... (une flamme, une zone du sol qui peut s'écrouler...).

Ce serait pour mes petits rats de laboratoire...

Avoid serait donc un argument qui pourrait être : 
- Un type de terrain
- Une zone de combat
- une zone RME
- un événement
- un tileID

**Comment by BastienDuplessier** [comment]
Perso, je suis pas chaud. Ça va ajouter de la complexité au niveau de la commande de pathfinding et ce n'est pas souhaitable.
Essaye de te débrouiller avec des events qui "bloquent" le passage durant le moveto.

Je laisse ouvert au cas où il y ait des avis contraires.

**Comment by Hinola** [comment]
Si c'est simplement pour bloquer, peut être qu'on peut bloquer certaines zones/case/terrains directement en agissant sur le event.passable?
Par exemple en donnant une liste de zones/case/terrains qui doivent être considérés comme non passable pour un évent en particulier

Donc rajouter un array de zones/case/terrains (un ou trois) dans Game_CharacterBase qui gérera ça et une commande qui va avec pour setter/getter ça, à utiliser avant la commande du pathfinding.

**Comment by Jauke** [comment]
Je peux faire ça sous rm2k3, ce n’est pas possible sous vxace? Vous savez, la petite case incompréhensible à cocher dans l’event genre « autoriser la superposition », erreur de traduction qui veut dire au contraire « interdire la superposition ».

Avec cette option cochée, deux événements ne peuvent plus se chevaucher (superposer) dans leur déplacement si ces trois conditions sont respectées :
- un des deux, ou les deux sont ont « interdire la superposition » de coché
- ils sont tous les deux dans la même couche (au dessous, ou au dessus... « au même niveau » c’est déjà comme si c’etait coché)
- si aucun des deux n’est en mode fantôme.

Cette option n’existe plus ?

Je m’en servais justement pour mapper des événements vides sous le héros en mode « interdire la superposition » pour définir les zones passables par le héros mais pas par les autres événements/monstres

**Comment by Jauke** [comment]
J’ai résumé en trois conditions de mémoire mais si ça se trouve je me suis trompé sur la seconde, faudra que je vérifie

**Comment by Jauke** [comment]
Si l’option n’existe plus on peut la reimplementer sur les évents (genre « event_forbid_superposition(id, *value) » voir le permettre pour les autres éléments (terrain, tile, etc.) si ça ne fout pas en l’air le pathfinder 

Pour le coup le forbid_superposition ne concerne pas que le pathfinder mais tous les déplacements, même ceux d’un évent qui se balade au pif sur la map. C’est mieux que « avoid »

**Comment by BastienDuplessier** [comment]
Oui, je préfère qu'on agisse "autour" du pathfinder pour ce genre de chose plutôt que direct dessus.

**Comment by Jauke** [comment]
Alors j'ai dis de la m*rde, alors je fais les tests qu'il faut pour ne plus en dire, attends. x)

**Comment by Jauke** [comment]
Alors : 
- Je confirme, la case à cocher s'appelle "Autoriser la superposition" dans rm2k3 trad 1.09b et fait bien l'inverse de ce qu'elle dit

- Je confirme, l'option n'existe plus dans VXAce, je pense qu'ils ont pas capté la faute de traduction dans RM2k3 (faute de trad qui doit remonter à l'original), ont voulu implémenter "Autoriser la superposition", l'ont appelé "Traverse tout", et... voilà comment on perd un "Interdire la superposition" utile, mais jamais utilisé à cause d'une erreur de traduction.

- J'ai mélangé le comportement par défaut des événements et celui du "Interdire la superposition" dans mon explication plus haut.

Je me corrige : 

- Les deux dernières conditions que j'ai cité devraient être celles par défaut.
- La première condition que j'ai cité suffit à décrire "Interdire la superposition"... loul.

"Interdire la superposition"... interdit la superposition dans tous les cas.

Et en vrai je n'ai jamais utilisé cette option, je préfère jouer avec le comportement de base des événements qui font qu'un événement sous le héros ne pourra pas chevaucher un autre événement sous le héros, idem pour les événements "au dessus du héros"... sauf si l'un des deux est en mode fantôme.

J'ai dû utiliser cette option une ou deux fois, je ne sais pas trop pourquoi, mais je confirme que j'ai déjà fait ce que demande @Zer0xxxx dans rm2k3... sans avoir eu besoin de cette option, en fait.

Alors @Zer0xxxx  si tu fais tes rats sous le héros, tu mappe des événements sous le héros là où tu ne veux pas que tes souris aillent, et basta.

Si le pathfinder ne considère pas le comportement de base du "déplacer événement" et rend possible la superposition de deux événements "sous le héros", ou deux événements "au dessus du héros"... Ce n'est plus une demande de feature mais une déclaration de bug (désolé j'ai pas vérifié)

**Comment by Zer0xxxx** [comment]
Honnêtement, je n'ai pas tout lu...
Pour ce qui est de "Interdire la superposition", ça existe dans VX Ace et se fait tout seul, en fait : 
Un événement ne PEUT PAS se déplacer sur un autre en "Sous le héros". SAUF, si cet événement est en "Sous le héros" ET "Mode fantôme". :)

Oui, je pourrais le faire avec des bidouilles.
Oui, c'est une demande assez chiante.

Oui, vous pouvez remettre ça à plus tard, ce n'est pas à moi de faire le décideur... Tout ça...
Et quoi qu'il en soit : bon courage pour la suite ! :)

**Comment by xvw** [comment]
Je pense que c'est trop spécifique pour être utile à RME.
