### ISSUE TITLE
Bug import_variable/import_switch/import_label

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#283]
Bonsoir!

Comme dit dans le titre, les 3 commandes pour récupérées les données d'une autre sauvegarde ne fonctionne pas. Pas de crash, mais pas de données récupérées non plus. 

Voilà mon code:
![capture](https://user-images.githubusercontent.com/15834672/36948931-f3d1a180-1fe1-11e8-906e-bc46b8850dc7.PNG)
Je vérifie si le fichier de sauvegarde existe, si c'est le cas, je récupère les valeurs voulu. Sinon je les met à jour et crée le fichier de sauvegarde.

Merci d'avance <3

**Comment by Grimimi** [comment]
Les commande d'importation renvoient la valeur. Il faudra donc faire quelque chose comme ça : 

```ruby 
V[6] = import_variable(1, 6)
```

est-ce que ça marche ?

**Comment by YendaHusk** [comment]
ça fonctionne 👍 Merci à toi!
