### ISSUE TITLE
item_name_to_ID

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#286]
Salut !

Serait-il possible de RECHERCHER l'ID d'un objet en fonction de son nom ?
Par exemple, une fonction : `item_name_to_ID("Potion")` qui me retournerait `1` ?

Merci d'avance pour vos retours. :)

**Comment by Grimimi** [comment]
Tu peux te servir de la base de données : 
```ruby 
VXACE_ITEM.find {|_, item| item.name == "Potion"}[0]
```

**Comment by Zer0xxxx** [comment]
Merci ! :)

**Comment by Zer0xxxx** [comment]
Et si je veux faire un truc du style : 
`VXACE_ITEM.find {|_, item| item.name == "#{Nanar_LightSystem["NanarLights"].torch_name}"}[0]`

?
(Ca ne fonctionne pas en l'état...)

Désolé d'être ennuyant. ^^'

**Comment by Grimimi** [comment]
```ruby
VXACE_ITEM.find {|_, item| item.name == Nanar_LightSystem["NanarLights"].torch_name}[0]
```
?

**Comment by Zer0xxxx** [comment]
J'avais déjà tenté cette écriture, et dans une condition, ça donne ce message d'erreur : 
http://img110.xooimage.com/files/1/5/a/pwet-5411b4d.png

Pareil que pour `VXACE_ITEM.find {|_, item| item.name == "#{Nanar_LightSystem["NanarLights"].torch_name}"}[0]`

**Comment by Grimimi** [comment]
Je ferme l'issue parce que l'objectif de cette rubrique n'est pas de 
faire du support à la conception de systèmes. Je t'invite à venir sur 
le discord dans la section support.

**Comment by Zer0xxxx** [comment]
Je comprends bien... Mais ma demande de base concernait l'ajout d'une commande "item_name_to_ID" :(

**Comment by Grimimi** [comment]
C'est une commande très spécifique qui peut, au moyen de la base de données, très 
facilement s'implémenter. Donc je ne pense pas que ce soit nécessaire dans RME.
