### ISSUE TITLE
Nouvelle commande: Fullscreen_mode? 

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#288]
Hello, serait-t'il possible d'ajouter plusieurs commande concernant le fullscreen ?
-Une pour vérifier si le jeu est en fullscreen.
-Une pour passer en fullscreen.
-Une pour passer en fenêtré.

Merci d'avance! :)

**Comment by xvw** [comment]
Est-ce que le script de Zeus FullScreen++ ne fait pas déjà parfaitement le travail ?

**Comment by YendaHusk** [comment]
Je viens de regarder, effectivement je ne connaissait pas ce script de Zeus. Après ça ne serais pas une bonne chose de l'ajouter à rme pour ne pas avoir à passé par un autre script ?

**Comment by xvw** [comment]
Dans la mesure où les deux scripts (RME et Fullscreen++) semblent compatibles, 
je ne suis pas sur que ça vaille la peine de réimplémenter quelque chose, potentiellement 
moins bien que Zeus81. Par contre, si tu vois des incompatibilités, n'hésite pas à venir faire une 
issue.
