### ISSUE TITLE
Nouvelle commande: in_editor?

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#289]
Rebonjour ! 
Je me demander si c'était aussi possible de savoir via une commande si le jeu a été lancé depuis l'exécutable ou directement depuis le logiciel ?
Cela doit déjà être implémenté dans rm vu que F9 et Ctrl sont impossible à utiliser lorsque l'on n'est pas dans l'éditeur.

Voilà voilà !

**Comment by xvw** [comment]
```ruby 
S[1] = $TEST
```

**Comment by YendaHusk** [comment]
Je ne connaissais pas, merci ! :)
