### ISSUE TITLE
Peut-on ajouter stop_all_events ?

### ISSUE THREAD

**Issue by CuddleFox** [RMEx/RME#290]
Je pense qu'une commande qui arrête tous les mouvements d'events serait pratique. Avec la possibilité de choisir si on arrête le héros avec ou non. Pour pouvoir programmer des systèmes qui s'affichent sur une map mais qui ne doivent pas permettre aux personnages de bouger ^^

**Comment by xvw** [comment]
Salut, merci de ta suggestion. 
Nous n'allons pas le faire sous la forme d'une commande mais via cette issue #258 pour favoriser la construction de systèmes complexes. C'est dans la roadmap pour la version après celle qui devrait sortir bientôt.
