### ISSUE TITLE
Erreur de classification dans la doc

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#296]
Il y a quelques petites erreurs dans la doc:
"import_variable_with_free_name" apparaît dans "Standards" et non dans "Sauvegardes"
"text_angle" apparaît dans "Standards" et non dans "Textes"
La commande Water? N'est pas présente dans la doc, ne devait-elle pas être ajouté lors de la 1.3.0 ?

**Comment by xvw** [comment]
Merci ! On essaie de corriger ça au plus vite ! 
Concernant la commande `water?` on l'a séparée en plusieurs commandes : https://github.com/RMEx/RME/pull/291

**Comment by BastienDuplessier** [comment]
Hello.
Concernant water?, on a décidé au final de ne pas la réaliser. C'est assez abstrait à définir comme commande. Certains auto-tiles peuvent changer d'un tileset à un autre et ne plus représenter de l'eau.
A la place nous avons ajouté les commandes `boat_passable?(x, y)`, `ship_passable?(x, y)` et `autotile_type(x, y, z)`.
Tu peux aussi utiliser les numéro de terrain dans l'outil d'édition de tileset pour indiquer qu'un tile est de l'eau.

**Comment by grrim** [comment]
Autre soucis : 
http://rmex.github.io/RMEDoc/#load_game_with_free_name le type ArgType est mauvais.

**Comment by grrim** [comment]
- [ ] "import_variable_with_free_name" apparaît dans "Standards" et non dans "Sauvegardes"
- [ ] "text_angle" apparaît dans "Standards"
- [ ] Retyper load_game_with_free_name

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
