### ISSUE TITLE
Lag massif depuis l'installation du script

### ISSUE THREAD

**Issue by CuddleFox** [RMEx/RME#297]
J'ai beaucoup trop de ralentissement depuis que je me sers de RME. Une map d'une trentaine d'events qui ne font rien divisent mes fps par 4. Même Effectus n'arrive plus à suivre.

Est-ce que c'est réglable ? Parce que je ne m'imagine pas retourner à l'event making classique, mais RME ralentit absolument tout.

**Comment by BastienDuplessier** [comment]
T'es vraiment sur que c'est RME le soucis ? Je vais effectuer une série de tests dans la semaine histoire d'être sur quand même.
Il nous faudrait aussi une démo pour qu'on puisse analyser la cause du soucis.

**Comment by BastienDuplessier** [comment]
(my bad pour le close, mauvaise manip)

**Comment by BastienDuplessier** [comment]
Envoie nous donc ces deux projets, l'un avec RME et le lag, l'autre sans RME et sans lag.
Ca nous permettra de répondre plus précisément à ton problème.

**Comment by hyperaho** [comment]
Je me permet de m'incruster dans la conversation pour plusieurs raisons.

1. J'ai dépensé 20$ pour acheter Effectus, je n'aurais pas dû, c'est une plaisanterie de mauvais goût.

> il a fallu enlever la limite de fps pour qu'il s'aperçoive qu'il était descendu de 120 à 60

2. Je suis ravi d'apprendre que RPGMaker VXace tourne à 120fps. Ce n'est pas du tout raccord avec l'implémentation du RGSS3... qui tourne, naturellement, à 60fps et absolument pas à 60. 
Le fait de modifier le "frame_rate" est complètement stupide parce que non seulement ça force, à la sortie de la boucle de raffraichissement un framerate faux et en plus, ça accelère tous les calculs relatifs au temps...

Après un rapide survol dans le code de RME, il existe effectivement des fonctionnalités qui peuvent ralentir le processus de jeu, par exemple, les effets de zooms, l'usage immodérés de capture d'écran ou l'invocation massive d'évènements issus de plusieurs maps différentes... mais "sur un projet vierge", RME ne consomme pas énormément de ressources en plus. 

Donc, ce que je te propose, c'est de partager une démonstration histoire que l'on puisse faire des benchmarks fins et que l'on puisse diagnostiquer des éventuels ralentissements (je ne doute pas de ta bonne foi). 
La diffusion d'une démo est vitale pour faciliter le développement parce que, je pense pouvoir affirmer que 90% de l'équipe de développement de RME utilisent des bêtes de combats (comme machine) et ne se rendent peut être pas compte des monstres qu'ils introduisent.

**Comment by CuddleFox** [comment]
Je vous enverrai le lien du projet lorsque j'aurais fini de l'uploader.

Je n'ai pas été clair, le projet qui ne ralentit pas est le projet de mon ami sur son ordinateur. Le problème, c'est qu'il y a une grosse chute de fps quel que soit le projet dès lors qu'on utilise RME avec des events. J'utilise mes arbres en events (car je ne peux pas faire autrement puisqu'ils sont grands et je ne me vois pas refaire toutes mes maps en parallax) et j'étais à 60fps avec Effectus, puis après l'installation d'RME sur la plupart de mes maps, je suis descendu à environ 15-20. Le fait que les lags soient aussi présent sur un projet vierge avec juste une map d'une trentaine d'events montre que ça ne vient pas de nos deux projets. Du moins ça n'a pas l'air. (Et j'ignorais que modifier la limite des fps était néfaste/inutile, je m'en excuse dans ce cas)

Et sinon je ne suis pas d'accord au sujet d'Effectus, qui se survend, mais qui marche bel et bien mieux que les autres anti-lags que j'ai utilisé ^^ Mais bien sûr qu'il ne vaut pas 20$, on en est loin, très très loin.

**Comment by CuddleFox** [comment]
Voici le lien du jeu : https://mega.nz/#!tXZgxAwR!-Faw2dpycB8LU1sLC_WmzPm9CBQUii8ZU_dYNrEFWsI

**Comment by BastienDuplessier** [comment]
Tu peux m'indiquer les maps qui posent problème stp ?

**Comment by CuddleFox** [comment]
Toutes celles où il y a beaucoup d'events.

**Comment by BastienDuplessier** [comment]
Je viens d'essayer les maps du début de ton projet et aussi Foret de Missing, aucun soucis, FPS entre 56 et 60.

**Comment by CuddleFox** [comment]
Moi non, je tourne à 15 max. Et j'étais à 60 avant. Essaie sur un pc moins puissant sûrement. Je n'ai pas une bête de course.

**Comment by BastienDuplessier** [comment]
Désolé, j'ai pas d'autre PC :/
Je laisse le relais à quelqu'un d'autre.

**Comment by YendaHusk** [comment]
Personnellement, j'ai testé deux trois map et je n'ai aucun lag, mais j'ai aussi un pc assez puissant donc à voir. CuddleFox, tu peux peut-être nous donner les caractéristiques de ton pc pour qu'on se fasse une idée.

**Comment by Zer0xxxx** [comment]
Et en virant use_reflection ?

**Comment by CuddleFox** [comment]
J'ai un processeur Intel(R) Pentium(R) CPU 2020M @ 2.40Ghz et 4Go de Ram.

Ça ne fonctionne pas Zer0.

**Comment by CuddleFox** [comment]
Est-ce que quelqu'un a une solution ?

**Comment by Ibiky** [comment]
Bonjour/soir, Effectivement je constate aucun problème avec mon PC actuel, mais quant je le teste avec un vieux PC qui tourne mal, j'ai effectivement une chute à 25/35 FPS alors que de base je suis à 60, j'ai aussi remarquer qu'il n'y à plus ce problème quant ont retire RME de la liste des script, mais j'ai aussi remarquer qu'il y à une masse d'autres script en désaccord avec RME, j'ai déjà vue des projets qui avais 100 scripts voir plus qui ne fonctionné plus à cause de RME et du coups ont venais dire que c'était à cause de ce script que cela ne fonctionner plus, alors quand réalité cela venais d'autre script dans le projet, après je n'ai pas de souci avec un projet vierge avec seulement RME sur aucune de mes machine, bien sur à un moment quant il y à trop d'évent à l'écran j'ai des pertes vue que je n'ai pas effectus.
Malheureusement pour toi je ne vois pas de solution à part tout faire ce que tu à fais avec seulement RME et Effectus, car certain de t'es script (comme ceux de Mox sont mal créer et touche à des choses qui ne devrais pas et donc il entre en conflit avec d'autre script sans comprendre pourquoi, j'avais ce problème avant maintenant je n'utilise que RME).

Cordialement Ibiky.

**Comment by xvw** [comment]
Il faut investiguer sur "pourquoi RME" ralentit les événements sans rien faire. ping @hyperaho ?

**Comment by xvw** [comment]
ping @hyperaho  2?

**Comment by Zer0xxxxx** [comment]
Salut !
Maintenant que j'y pense... Je vais regarder ta démo et **l'ensemble de ses scripts**.

Je ne cherche pas à dire que "C'est pas RME, c'est les autres", juste que ces derniers jours, j'ai cru remarquer que surcharger RM VX Ace de scripts (notamment du Yanfly et certaines réécritures des classes concernant les bitmaps) posait problème.

Comme je ne suis sûr de rien, je vais essayer de voir si les scripts qui sont installés **en plus de RME** ne posent pas de soucis dans la _cohabitation_ entre RME et ces derniers...

Je reviendrai à toi, en espérant que cette tentative s'avèrera fructueuse...

**Comment by BastienDuplessier** [comment]
On déterminera une bonne fois pour toutes si RME fait chuter les performances une fois qu'on aura notre outil de benchmark. Je ferme cette issue en attendant, pour le moment rien n'a jamais été prouvé.

**Comment by Zer0xxxxx** [comment]
Salut !
Après avoir disséqué l'intégralité de RME avec un copain on s'est rendu compte qu'en désactivant l'Event Extender, on n'avait plus de souci de lag.

On a donc disséqué l'Event Extender, et en virant les micro-événements on s'est rendu compte que ça ne rame plus.

http://paste.awesom.eu/KWHp&ln

**Comment by ImCaptainMorgan** [comment]
[[CLONE] RME disséqué.zip](https://github.com/RMEx/RME/files/2703379/CLONE.RME.disseque.zip)
j'avais aussi commencé à disséquer l'event extender mais finalement j'ai laissé tomber. :3
