### ISSUE TITLE
Problème chargement de save custom

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#298]
Crash du jeu lorsqu'on load une save custom.
![image](https://user-images.githubusercontent.com/15834672/37606413-b82626f0-2b95-11e8-8797-0d533ad7f407.png)
![image](https://user-images.githubusercontent.com/15834672/37606476-d617121e-2b95-11e8-87b9-a301200b968c.png)

**Comment by xvw** [comment]
tu as oublié des guillemets dans l'appel de script.
