### ISSUE TITLE
Nouvelle commande : Event_Overlap

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#299]
Serait-il possible d'ajouter une commande Event_Overlap pour autoriser les events à ce superposé.
Je m'explique, dans rm2k3, c'est possible de cocher une option pour qu'un event en déplacement aléatoire par exemple, puisse marcher sur un autre événement qui a lui aussi l'option de coché.
Dans Ace, c'est impossible, si on rempli une salle d'event qui se déplace aléatoirement, ils vont toujours attendres qu'une case sois libre avant de s'y déplacer. (Même si tout les events sont en mode "en dessous du héro".
Un espèce de "traverse tout" mais uniquement pour les events et non les décors.

**Comment by BastienDuplessier** [comment]
On va étudier ça. Merci de la proposition.

**Comment by BastienDuplessier** [comment]
J'ai terminé la commande, elle arrivera avec la prochaine version de RME.
L'issue sera fermée automatiquement quand le code sera fusionné avec la branche principale.
