### ISSUE TITLE
Formule de Dégats et RME

### ISSUE THREAD

**Issue by Celestiel** [RMEx/RME#3]
Les commandes RME ne fonctionent pas dans les formules de dégats. certaines commandes n'ont pas beaucoup de sens comme celles des images, beaucoup de données numeriques pouraient servir.

**Comment by hyperaho** [comment]
l'argument "v" correspond aux variables. Pourquoi tu ne t'en sers pas ?

**Comment by Celestiel** [comment]
En partant de cette question, je ne me sert même pas des commandes RME d'habitude et utilise directement la ligne de code qui fait l'effet voulu ce qui marche très bien :D

Pour ce qui est des V[] ce n'est tout simplement pas pratique. Il faudrait crée un evenement commun pour garder a jour les variables et retourner modifier cet evenement, utiliser une variables suplementaire pour chaque appel de fonction RME.

Mais je te l'accorde je vais toujours chercher les cas d'utilisation plus plus débile

**Comment by xvw** [comment]
Il ne faut pas oublier que le "binding" initial de l'évaluation de la formule de combat prend l'acteur en argument... donc a priori, tout est gerable :3
