### ISSUE TITLE
Fond blanc à la place de la map lors de la transition de démarrage de combat

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#30]
Re-bonsoir ! :)
Depuis la dernière MaJ de RME, lorsque je démarre un combat (avec le système de base et tout) dans un event, la transition se joue sur fond blanc.

À bientôt ! =)

**Comment by hyperaho** [comment]
C'est lié à l'usage de RME en "unsafe". 
Pour le moment, on ne prend pas ce genre de bogues en comptes...

**Comment by Zer0zer0x** [comment]
Bien vu ! ^^
Je n'ai pas besoin du mode unsafe, de toute façon. :)

**Comment by xvw** [comment]
C'était moi, désolé.
