### ISSUE TITLE
Commande pour connaître les passabilités directionnelles d'un tile

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#300]
Salut !
Existe-t-il une commande RME pour savoir si la case n'est pas passable vers le "Haut", le "Bas", la "Gauche", et/ou la "Droite" ?

Mercii ! :)

**Comment by YendaHusk** [comment]
[square_passable?(x, y, direction)](http://rmex.github.io/RMEDoc/#square_passable?)

**Comment by Zer0xxxx** [comment]
Mais... mais tu as raison !
