### ISSUE TITLE
Commande make_run_a_script

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#301]
Salut !

Serait-il envisageable de créer une commande "make_run_a_script(event_id, script)" qui permettrait de dire à un événement de balancer un appel de script... mais, ce depuis un événement commun, un événement au pif en processus parallèle... ?

Ce n'est pas vraiment pour RME à proprement parler, qui n'a pas besoin de cette feature pour tourner... (je crois ?)

J'y vois un potentiel besoin pour coupler RME à d'autres scripts qui nécessitent des appels pas toujours aussi bien designés que ceux d'RME...

Bref, inutile d'y voir une priorité absolue...

**Comment by BastienDuplessier** [comment]
Alors, ce qui est sur c'est qu'il n'y aura pas de commande dans ce genre.
Par contre, ce que tu peux faire même si c'est crade, c'est ton évent commun avec la commande `Script : eval(V[ID])` et autre part `V[ID] = "puts 'Salut'"`.

**Comment by xvw** [comment]
> J'y vois un potentiel besoin pour coupler RME à d'autres scripts qui nécessitent des appels pas 
> toujours aussi bien designés que ceux d'RME...

Franchement, je ne vois aucun cas d'usage... Si un script a une mauvaise API, il faut simplement wrapper son API dans une API plus propre. :)

**Comment by Zer0xxxx** [comment]
Je n'y avais même pas pensé.
Chouette !
