### ISSUE TITLE
does_a_path_exists?

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#303]
Bonjour !
Existe-t-il une commande dans RME permettant de savoir clairement si OUI ou NON il existe un chemin entre un événement A et un événement B ? :)

**Comment by BastienDuplessier** [comment]
Essaye la commande http://rmex.github.io/RMEDoc/#event_path_length
Peut être qu'elle va te renvoyer 0 ou un truc du genre.

**Comment by grrim** [comment]
Est-ce que ça résout le problème ?

**Comment by Ibiky** [comment]
Bonjour/soir, je profite de ce post pour dire que les commande player_path_length et event_path_length ne fonctionne pas, j'ai deux erreur en utilisant ces commandes : 

http://puu.sh/zQkZP/f341ec065b.png , en utilisant cette commande : `player_path_length(event_x(me), event_y(me))` ou celle-ci `event_path_length(me, player_x, player_y)`

http://puu.sh/zQl0J/450c180469.png , en utilisant cette commande : `player_path_length(event_x(me), event_y(me), false, true)`

http://puu.sh/zQl6T/12a4e73da9.png , en utilisant cette commande : `event_path_length(me,player_x, player_y, false, true)`

je ne pence pas que cela est normal, j'utilise la dernière version de RME.

**Comment by BastienDuplessier** [comment]
J'm'occupe de ça.

**Comment by BastienDuplessier** [comment]
Pour les deux premières, y'a une couille dans notre code. Sorry.
Pour les deux dernière, on s'est plutôt chié au niveau de la doc. La command n'a pas de "wait", étant donné qu'on calcule juste une longueur.

Je m'occupe de régler ces deux soucis.

**Comment by BastienDuplessier** [comment]
Autrement les commandes renvoient bien 0 si la destination n'est pas atteignable.

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
