### ISSUE TITLE
Nouvelle commande : Reset

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#304]
Hello, serait-t'il possible d'ajouter une nouvelle commande qui agit exactement comme la touche f12 ?
C'est-à-dire qui reset le jeu et renvoi vers l'écran titre.
Pourquoi ne pas utiliser directement la commande "call_title_screen" ou celle d'rm ? Car si on utilise le passeur d'écran titre, ça nous enverra à l'écran titre par défaut d'rm et non à la map que l'on a configuré.

**Comment by BastienDuplessier** [comment]
Je vais voir ce que je veux faire. Je ne sais pas si on peut exactement faire comme la touche F12 mais on va voir.

**Comment by xvw** [comment]
Il suffit de faire un "reset" et de couper tous les sons :)

**Comment by BastienDuplessier** [comment]
La commande se nommera `reset` et ne prendra aucun argument.
Son comportement sera de retourner à l'état initial.

**Comment by xvw** [comment]
parfait !

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
