### ISSUE TITLE
Ray-traceur 

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#306]
Ce tutoriel est vraiment super cool : 
https://rpgmakeralliance.com/d/84-systeme-dinfiltration-complet-avec-rme

Mais il pourrait être encore plus cool si RME intégrait un ray-traceur pour les zones virtuelles (et pourquoi pas les tiles). Je n'ai pas encore d'idée pour l'API mais je pense que l'ajout pourrait vraiment être un plus !

**Comment by BastienDuplessier** [comment]
Ca pourrait être cool en effet. Je crois que c'est ce dont j'ai besoin pour mon système de déplacement T-RPG pour matérialiser les cases libres autour du perso.

**Comment by BastienDuplessier** [comment]
Proposition de spec :
- `raytrace(ax, ay, bx, by)` : Renvoie un tableau contenant toutes les cases traversées par le segment AB (matérialisé par les coordonées xy de ses deux points)
@xvw On en avait parlé ensemble, qu'en penses tu ?

**Comment by xvw** [comment]
très bien.

**Comment by BastienDuplessier** [comment]
Développement terminé et fusionné dans la branche de dev. Il sera dispo avec la version 1.4 de RME
