### ISSUE TITLE
Enlever le texte automatiquement avec text_progressive

### ISSUE THREAD

**Issue by Princesseuh** [RMEx/RME#309]
Bonjour!

J'ai utilisé (encore une fois) RME pour la dernière jam de [RMA](https://rpgmakeralliance.com/), la [RPG Maker Games in 1 Hour](https://itch.io/jam/rpgmaker1hour) et voici mon jeu : [Magician's Assistant](https://princesseuh.itch.io/magicians-assistant) qui utilise `text_progressive` pour.. tout les dialogues. 

J'ai apprécié l'utilisation de la commande (surtout les options pour faire des trucs entre les caractères même si je l'ai pas utilisé pour ce projet) mais un truc que j'ai trouvé un peu dommage c'est que chaque fois que je voulais changer le texte je devais faire `text_change(1, "")` avant le `text_progressive` pour enlever le texte actuel parce-que il s'avère que `text_progressive` append au texte actuel plutôt que de le remplacer, ce que je ne trouve pas idéal (mais quand même intéressant)

Ma suggestion est donc que text_progressive par défaut enlève le texte mais qu'un paramètre soit disponible pour append au texte si besoin.

Voilà voilà

**Comment by xvw** [comment]
C'est implémenté. Ce sera présent dans la prochaine release de RME..
