### ISSUE TITLE
[Tueur d'écran titre] F12 en combat

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#31]
Coucou. :D 
J'ai l'impression que lorsque l'on appuie sur F12 en combat pour réinitialiser le jeu, il ne l'est pas de la même façon qu'hors des combats, avec le tueur d'écran titre (j'ai des bugs avec mon écran titre assez improbables uniquement dans les cas de figure où j'ai réinitialisé le projet avec F12 en combat... désolé d'être flou, je m'appliquerai à être précis si nécessaire). Je précise également que tous les redémarrages avec F12 suivant un redémarrage en combat me font avoir les mêmes bugs (je pense que c'est soit au niveau des inputs soit au niveau des interrupteurs).

**Comment by hyperaho** [comment]
Je n'aime pas demander ça, mais je pense qu'il nous faudrait une démo :/ désolé.

**Comment by Grimimi** [comment]
ping?
