### ISSUE TITLE
[Question] Déclencheurs personnalisés et événements communs

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#311]
SALU !
Y'a moyen d'utiliser cette feature pour un EV commun en processus parallèle ou démarrage auto ?

https://github.com/RMEx/RME/wiki/Déclencheurs-personnalisés

**Comment by xvw** [comment]
Ça ne fonctionne pas ?

**Comment by Zer0xxxx** [comment]
Nope.
![no](https://user-images.githubusercontent.com/36828641/38876647-2a12c92a-425d-11e8-9021-b6086a36cbf0.png)

RM te force à mettre un switch conditionnel sur les EV communs en démarrage auto et processus parallèle. Et là, du coup, l'event ne se lance que quand S[10] est activé...

Ce que je voudrais, c'est pouvoir "Ignorer" cet interrupteur conditionnel qui m'est imposé par RM et directement passer par le déclencheur personnalisé... :)

**Comment by Zer0xxxx** [comment]
Nope.

RM te force à mettre un switch conditionnel sur les EV communs en démarrage auto et processus parallèle.
Si je fais un EV commun avec comme interrupteur conditionnel "10", même si je mets le trigger dans mon EV commun, en première ligne, il ne se lancera que "10" est activé...
Il ignore tout bonnement le trigger tant que son interrupteur conditionnel imposé dans la BDD n'est pas sur true.

Ce que je voudrais, c'est pouvoir "Ignorer" cet interrupteur conditionnel qui m'est imposé par RM et directement passer par le déclencheur personnalisé... :)

**Comment by BastienDuplessier** [comment]
Je pense que tu devrais faire un interrupteur qui se met sur "true" au début du projet et dire que l'event se déclenche à ce moment là. Comme ça tu pourras utiliser ta condition spécifique.

**Comment by xvw** [comment]
Oui, effectivement, ils sont codés comme "interrupteur de base && custom trigger". La solution de BastienDuplessier est la bonne.

**Comment by Zer0xxxx** [comment]
Ah bon... Donc on a des déclencheurs personnalisés pour les événements, mais les événements communs, c'est historique, on n'y touche pas... :snif:
