### ISSUE TITLE
RME et DLL audio ?

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#314]
Bonjour !
Pour faire écho à mon issue #232 qui était encore à l'époque très lacunaire...

Je me demande si RME ne pourrait pas proposer une implémentation d'une DLL audio telle FMOD Ex, FMOD Studio... etc.

Ce qui nous mènerait à : 
- Channels audio multiples
**- Système d'audio standard d'RPG Maker toujours disponible et OK (pas d'incompatibilités).**
- Effets Spéciaux DSP

Et dans le meilleur des mondes, des commandes super simples à utiliser pour les effets spéciaux DSP, telles `BGM_distorsion` ; `BGM_chorus` ; `SE_distorsion`... et bien d'autres encore. 

Je sais que c'est une issue qui demande beaucoup de réflexion et de temps... que l'on touche à la frontière de ce que font des engine pro bien au-dessus d'RM...

J'espère que vous porterez un certain intérêt à ce genre d'extras.
Même si certains sont peut-être contre l'ajout de DLL dans un jeu RM...

PS : Un script le proposait déjà pour VX Ace, mais il présente de très nombreux dysfonctionnements... Il a tout bonnement refusé de démarrer sur mon Win10 Edition Familial (et s'est lancé pour le peu de configurer le Game.exe en mode compatibilité Windows 7, mais il refusait de mettre en branle les "Effets"...).
https://www.rpgmakercentral.com/topic/5259-audio-pump-up-fmod-ex-14/
Quelle tristesse !

EDIT : il semblerait en fait que ce script fonctionne bien et que ce soit mon gestionnaire d'archive qui ait fait une erreur à l'extraction... en passant par 7zip je n'ai plus d'étranges problèmes... très curieux.

Peut-être faudrait-il se pencher sur ce script pour être sûr que son bon fonctionnement est garanti ? + qu'il soit compatible RME ?
(Je veux bien investiguer).

**Comment by xvw** [comment]
Désolé, mais FMODEx n'est pas libre, et même si on arrivait à faire aussi bien que NagatoYuki (ce dont je doute), on ne pourrait, pas non plus, rendre la DLL libre (le reverse-engineering doit rester confiné), de ce fait, ça ne *fit* pas avec la philosophie de RME (qui est entierement libre)... désolé.

**Comment by Zer0xxxx** [comment]
ah ui...
Il doit bien exister une DLL libre, pourtant...

Mais bon, j'aimerais bien plus un pixel movement, dans un premier temps, qu'une gestion audio avancée. :)
