### ISSUE TITLE
Nouvelle commande : area_color

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#315]
Bonjour !

Pour faire echo à l'issue #312 ainsi qu'au commentaire que je me suis permis (évasivement) de poster dessus...

J'ai songé à une commande area_color, qui permettrait de donner une couleur à une zone virtuelle.
Avec l'alpha en prime (pour gérer l'opacité).

Ce serait chouette ! Notamment pour le debug (ou faire quelques effets extrêmement "lights" sur la map) !

**Comment by xvw** [comment]
Non. Désolé; La seule "zone" remplissable est la zone rectangulaire. De ce fait, les zones polygonales, circulaires, elliptiques ne seraient pas candidate à la couleur.
