### ISSUE TITLE
Erreur en affichant un texte vide centré

### ISSUE THREAD

**Issue by aureliendossantos** [RMEx/RME#316]
Créer un texte vide `""` aligné à gauche (origin = 0) fonctionne, par contre s'il est centré (origin = 1) ça fait ça : 

![](https://i.imgur.com/1ejaE1P.png)

Pour éviter l'erreur, je dois donc mettre un espace `" "` ou autre caractère.

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
