### ISSUE TITLE
Coquille dans la doc

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#320]
Salut !
Petite coquille dans la doc...
https://media.discordapp.net/attachments/344820694888218627/435929797139628054/unknown.png?width=1249&height=677

"On parcour" au lieu de "On parcourt". 

- http://rmex.github.io/RMEDoc/#tile_id

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
