### ISSUE TITLE
Les événements communs ignorent les déclencheurs personnalisés

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#321]
Bonjour !
Cet événement commun affiche "[PICS] Update" tant que l'interrupteur 5000 est pris en compte.
Il ne tient pas compte de la condition : 
```trigger{S[Boubou::Pics::SWITCH_FOR_UPDATE]}```

![qsmdlsqkdboubou](https://user-images.githubusercontent.com/36828641/38946560-1e06a6b4-433a-11e8-8d66-5494066d1bb7.png)

**Comment by Zer0xxxx** [comment]
Au passage, je viens de me dire qu'on pourrait écrire dans un événement commun (et seulement dans un événement commun) un trigger commençant par "Or" :  
`trigger{or S[4])}`

Pour qu'il se comporte de la façon suivante : 
`interrupteur conditionnel BDD | S[4]`

**Comment by xvw** [comment]
Pour ta seconde demande. Non, désolé.

**Comment by Zer0xxxx** [comment]
Je m'en doutais.
De toute façon c'était de la vilaine manipulation dans l'espoir qu'RME me permette tout de même de faire péter ce putain de switch conditionnel propre à la BDD. (Boubou est insistant...)

Mais bon, pas de souci. Hihi !

**Comment by xvw** [comment]
tu peux utiliser `ignore_left` normalement : https://github.com/RMEx/RME/wiki/D%C3%A9clencheurs-personnalis%C3%A9s#ignorer-la-condition-initiale

**Comment by Zer0xxxx** [comment]
Omg.
Ca m'apprendra à lire.
