### ISSUE TITLE
Nouvelle commande : window_windowskin

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#322]
Salut !
Je trouve ça super de pouvoir créer des fenêtres avec RME.

J'aimerais savoir si une commande : 
`window_windowskin(id, filename)`

serait envisageable ? :)

Afin de pouvoir aussi attribuer un windowskin à nos fenêtres RME !

**Comment by Zer0xxxx** [comment]
#323

**Comment by BastienDuplessier** [comment]
Développement fusionné dans la branche de dev, il sera disponible pour la version 1.4
