### ISSUE TITLE
Nouvelle commande : window_windowskin_tone

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#323]
Salut !
Je trouve ça super de pouvoir créer des fenêtres avec RME.

J'aimerais savoir si une commande :
window_windowskin_tone(id, tone())

serait envisageable ? :)

Afin de pouvoir aussi attribuer un tone aux (futurs ?) windowskins de nos fenêtres RME !
#322

**Comment by BastienDuplessier** [comment]
Alors, je viens d'un peu enquêter et visiblement y'a déjà une commande pour ça : http://rmex.github.io/RMEDoc/#windowskin_tone
Mais c'est pour changer le ton de toutes les window d'un coup (menus de base et window RME).

Je vais ajouter une commande pour en spécifier un manuellement.

**Comment by xvw** [comment]
Oui, c'est un peu "ennuyeux", je pense qu'il faudrait être capable de spécifier ce genre de paramètre pour l'intégralité des "windows", Menu, Combat, Message et RME. Qu'en penses-tu ?

**Comment by BastienDuplessier** [comment]
J'ai fait du code qui modifie directement `Window_Base`.
Je le push sous peu, tu pourras me dire si c'est ce à quoi tu pensais.

**Comment by BastienDuplessier** [comment]
Développement fusionné dans la branche de dev, il sera disponible pour la version 1.4
