### ISSUE TITLE
Nouvel argument pour les spritesheets : z-index

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#324]
Bonjour !
Je trouve que les spritesheets sont une très bonne idée !
Elles permettent la création de certains systèmes bien mieux que le permettent les pictures...

S'il est aisé de rajouter le z-index, je ferai un joli système (que je partagerai) !
Bouh !

**Comment by BastienDuplessier** [comment]
Je viens de regarder le code. Le `Sprite_Spritesheet` hérite de `Sprite_Picture`.
Visiblement, le z correspond à l'ID de la picture/spritesheet.
Donc je pense qu'on n'ajoutera pas un autre paramètre. @Jauke @xvw qu'est ce que vous en pensez ?
Ref : `Sprite_Picture`
```ruby
  #--------------------------------------------------------------------------
  # * Update Position
  #--------------------------------------------------------------------------
  def update_position
    self.x = @picture.x
    self.y = @picture.y
    self.z = @picture.number
  end
```

**Comment by xvw** [comment]
C'est implémenté. Ce sera présent dans la prochaine release de RME..
