### ISSUE TITLE
Nouvelle commande : fresh_window_id

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#325]
Salut !
Je ne vois pas de commande pour choper un id "fresh" sur les fenêtres RME...
Je vois "fresh" sur les pictures, les événements, les spritesheets...

Aurais-je raté quelque chose ?

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
