### ISSUE TITLE
Message d'erreur si : create_text_window(id, "", x, y, w, h)

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#326]
Bonjour !
La création d'une text_window avec pour `content` la valeur `""` retourne une erreur.

![errormess](https://user-images.githubusercontent.com/36828641/38985775-9f31bc70-43ca-11e8-816d-cb531dfa49c0.png)

Pareil avec des guillemets Anglais.

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
