### ISSUE TITLE
Nouvel argument pour les pictures : z-index

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#327]
Salut !
Je pense qu'il faudrait implémenter le z-index dans les pictures pour pouvoir créer des effets très chouettes sur les messages (comme un effet de brume sur le bas de sa boîte de dialogue) et ses propres fenêtres RME.

Comme nous le savons, si l'on spécifie un z-index supérieur à `199`, on passe au-dessus des fenêtres. :)

**Comment by Zer0xxxx** [comment]
Quand je vois que certains JV rétro avaient une commande "Modifier le ton de l'écran" qui ne concernait que la map... ça me donne des idées. :3 
https://youtu.be/V3cRmf6kKBE?list=PLQ58HYTDzLvL92US1q6csKkVmQN-4SeT-&t=55

**Comment by xvw** [comment]
C'est implémenté. Ce sera présent dans la prochaine release de RME..
