### ISSUE TITLE
[Bug] F9 et create_text_window

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#328]
Bonjour !
Dans un événement en Touche Action, je fais : `create_text_window(1, " ", 10, 10, 1000, 1000)`

Si j'appuie sur F9 pour ouvrir le menu de debug d'RM, puis que je le quitte, ma text_window disparaît...

**Comment by BastienDuplessier** [comment]
J'ai trouvé le soucis, je m'occupe de régler le soucis pour la prochaine release. L'issue sera fermée quand le code sera fusionné avec la branche de dev.

**Comment by BastienDuplessier** [comment]
Le code est fusionné dans la branche de dev, ce probleme sera réglé dans la version 1.4 de RME.
