### ISSUE TITLE
Nouvelle commande : spritesheet_animé_à_larret

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#329]
Bonjour !
Reproduire le système de "Animé à l'arrêt" pour les spritesheets ?
Du genre, une commande : 
`spritesheet_noidea(id, true, v, onrow, oncolumns, method)`

`true` étant le booleen qui définit si l'on est en animation à l'arrêt ou non.
`v` étant un nombre entier qui désigne le nombre de frames à attendre entre chaque sprite.
`onrow` étant un booléen nous permettant de savoir si l'on itère ou non sur les rangées.
`oncolumns` étant un booléen nous permettant de savoir si l'on itère ou non sur les colonnes.

`method` étant un argument qui peut modifier le fonctionnement de l'itération, ou proposer de faire des "Allers-Retours" plutôt que directement revenir au premier sprite quand on a fini de parcourir la sprite_sheet...

EDIT : 
Maintenant que j'y pense, il y a peut-être moyen de tout simplement adapter ce que Joke avait fait pour l'Épilogue d'Almost Heroic... Avec la commande picture_name... :)

(Ca me semble plutôt différent puisqu'on ne passe plus d'un nom de picture à un autre, ceci dit ! Mais ce doit être faisable.).
Je ne me suis pas encore penché là-dessus !

**Comment by xvw** [comment]
Pour faire un "animé à l'arrêt", il suffit d'utiliser la commande "next" dans une boucle avec un attendre X frames.
