### ISSUE TITLE
[Testeur de script] autocomplétion au mot 

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#33]
@xvw 
A implémenter

**Comment by Grimimi** [comment]
Je pense qu'il ne faut pas essayer de faire une "complétion parfaite", car comme vous l'avez initié, si j'autocomplete sur "thing", je dois passer par `eval`. Et donc si "thing" crée un effet de bord, les conséquences peuvent être lourde. Donc soit "on hardcode" les valeurs complètables, mais quoi qu'il en soit, on évite le "eval" pour compléter. 

Merci :)
