### ISSUE TITLE
Nouvelle commande : Retourner la valeur width/height d'une picture en pixels

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#330]
Bonjour !
Il existe une commande picture_width, mais elle sert à définir une width manuellement...
De même pour picture_height

Quand je fais : 
```
id = 1
picture_show(id, "NICS_Clef", 0, 0, 1, 100, 100, 0)

w = picture_width(id)
```

J'ai un message d'erreur : 
![errormess2](https://user-images.githubusercontent.com/36828641/38986965-7690f3fe-43ce-11e8-9283-4940ced89f18.png)

Il n'existe donc pas encore de commande pour le faire ? :)

**Comment by xvw** [comment]
Tu es sur d'être sur la dernière version de RME ?

**Comment by Zer0xxxx** [comment]
Je vérifie ça demain !

**Comment by Zer0xxxx** [comment]
g pas réussi à lancer RME Builder sous Win10, même avec la petite astuce donnée sur la page de RME Builder...

En revanche, je viens de constater que je suis sur la version 1.2.0 de RME. :x

**Comment by Zer0xxxx** [comment]
Je viens de tester avec RME 1.3.0
Le bug n'est plus d'actualité.
