### ISSUE TITLE
Nouvelle commande : forcer l'id de l'événement appelant un EV commun

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#331]
(Ou nouvel argument pour `call_common_event` ? `call_common_event(id, forced_id)` ? )

Salut !
Ce serait pour pouvoir injecter de temps en temps le code d'un événement commun dans un événement, dynamiquement (notamment pour un système de bruits de pas où même les événements sont concernés + diffusion d'un SE en "3D", réalisée en événement commun).

Je peux très bien le coder autrement...
Mais bon, j'ai songé à l'idée, qui reste bonne pour les petits event-makers... Je pense. :D

**Comment by BastienDuplessier** [comment]
Le `forced_id` c'est pour que dans l'event commun, le `me` renvoie vers le `forced_id` ? Ou alors il y a d'autres choses qui vont changer ?

**Comment by grrim** [comment]
Je suis contre. 
Si j'ai conçu la commande "call_common_event" pour être appelé dans l'évènement 
courant, c'est parce que la tête de lecture d'un autre évènement est difficilement 
accessible de l'extérieur. De ce fait, l'injection d'un évènement commun dans un 
autre évènement n'a pas de sens. Je clos et je retire cette demande de la milestone 
car elle n'a pas de sens et d'intérêt.  (Mais bravo @Zer0xxxx, histoire de ne pas te 
donner de raison d'être insuportable).

**Comment by Zer0xxxx** [comment]
lol
