### ISSUE TITLE
Plus de fonctionnalités pour switch_tileset

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#332]
Salut !
Actuellement, on peut utiliser la commande `switch_tileset(tileset_id)` pour changer d'ID de Tileset.

J'ai songé à une commande `jesaispascommentlanommer_tileset(filename, C)` qui permettrait carrément de changer le tileset A, B, C, D, ou E, voire les autotiles, indépendamment !

Qu'en pensez-vous ?

**Comment by xvw** [comment]
ça implique une réécriture complète de Spriteset_map. C'est beaucoup de modifications pour pas grand chose.
