### ISSUE TITLE
Nouvel argument pour les animations de combat : z-index

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#333]
(Pour les animations de combat lancées depuis des événements...)
Ce qui rejoint l'issue #150 

À moins qu'un z-index ne suffise pas pour répondre à la demande de Husk (qui est, à mon sens, une priorité).

(Ca m'amuserait bien de pouvoir combiner un script qui permet d'afficher plusieurs animations en même temps et un z-index.)

**Comment by xvw** [comment]
doublon avec #150
