### ISSUE TITLE
Blabla RME

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#335]
Bonjour !
Je propose la création d'un BLABLA pour RME, spécialement dans cette issue !!!

Ca me semble être une S-U-P-E-R I-D-É-E !!!!!!

**Comment by Zer0xxxx** [comment]
bonjour

**Comment by Zer0xxxx** [comment]
As-tu vu l'issue #322 ?

**Comment by Zer0xxxx** [comment]
Oh oui, elle est très chouette !
Que penses-tu de l'issue #310 ?

**Comment by Zer0xxxx** [comment]
Je trouve cette demande assez étrange.
Ce doit être pour faire un truc GRAVE STYLÉÉÉÉ

**Comment by Zer0xxxx** [comment]
Je pense qu'elle est, en fait, corollaire à l'issue #308 :)

**Comment by Zer0xxxx** [comment]
Ah bon ? Probablement dans l'idée de celui qui l'a ouverte, alors !!

**Comment by Zer0xxxx** [comment]
Oui. Il parait que c'est un utilisateur acharné d'RME.
La légende raconte qu'il est né dans un hôpital psychiatrique

**Comment by Zer0xxxx** [comment]
Quel brave type !

**Comment by Zer0xxxx** [comment]
Je trouve les issues de Yenda Husk très intéressantes, aussi !

**Comment by Zer0xxxx** [comment]
Oui, c'est un maker assez ancien. Trop peu de gens le connaissent, alors qu'il est plutôt bon !

**Comment by Zer0xxxx** [comment]
Ah ! Cela explique pourquoi il utilise lui aussi RME. :)

**Comment by Zer0xxxx** [comment]
Oui, parce que c'est un ancien, et qu'en plus il est bon !

**Comment by Zer0xxxx** [comment]
Deux critères élémentaires, mon cher Zer0xxxxxxxxx

**Comment by YendaHusk** [comment]
Je suis plutôt d’accord avec ce raisonnement !
