### ISSUE TITLE
Récupérer la valeur de message_height ?

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#345]
Salut !
Je ne peux pas écrire : 
```SL[:boubou_old_message_height] = message_height```

Qui me retourne le message d'erreur : 
Mauvais nombre d'arguments (0 au lieu de 1).

**Comment by BastienDuplessier** [comment]
C'est normal : http://rmex.github.io/RMEDoc/#message_height
Si tu veux pouvoir avoir la valeur, crée plutôt une issue qui demande cette nouvelle commande.
