### ISSUE TITLE
[Demo fournie] Bug RME et retour au bureau Windows

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#347]
Salut !
J'ai un curieux message d'erreur quand j'utilise le raccourci Windows + D... (pour revenir au bureau).

Démo fournie + Gif animé pour montrer ce que ça donne : 
[BOUBOU_GHOST.zip](https://github.com/RMEx/RME/files/1947568/BOUBOU_GHOST.zip)

![ghost](https://user-images.githubusercontent.com/36828641/39254099-9d0ff3b0-48a9-11e8-9ea7-6a2e405212ed.gif)

**Comment by Zer0xxxx** [comment]
C'est chouette le vélo.

**Comment by BastienDuplessier** [comment]
Bug trouvé. Le fix arrivera sous peu.

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
