### ISSUE TITLE
[Bug] Comportement de event_move

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#350]
Bonjour !
Le comportement des commandes event_move n'est pas exactement celui attendu par un event-maker. :/

![bugrme](https://user-images.githubusercontent.com/36828641/39401078-76410bfc-4b3d-11e8-9d43-c9b1f1fd45e2.png)

Là où RPG Maker ne lit que le dernier déplacement dans ce genre de cas, event_move essaie de jouer "Tous" les déplacements. Ca donne lieu à une saccade/un "Sursaut" plutôt inattendu et désagréable.

Il me semble qu'il en va de même si l'on utilise une commande RME durant le déplacement d'un événement (si celui-ci a été lancé depuis une commande RME).

Comme si event_move n'attendait pas que le character soit parfaitement positionné sur une case pour effectuer le déplacement... Et reste aussi ce problème de ne pas se comporter comme RPG Maker quand on lance, ligne après ligne, plusieurs déplacements dont on ne veut faire finir qu'un seul... :/

Ils n'ont pas les mêmes "Timings".

**Comment by BastienDuplessier** [comment]
Tu devrais utiliser les move routes dans ce cas.
Peut être qu'on devrait bosser une manière de les rendre plus utilisable via RME.

**Comment by Zer0xxxx** [comment]
![boubouuuu](https://user-images.githubusercontent.com/36828641/39401121-5c4dba28-4b3e-11e8-8efa-5bd0a38ae837.png)

Je voulais m'en servir pour faire un effet "Glisse" si un déplacement en diago échoue. :/

**Comment by BastienDuplessier** [comment]
T'as deux solutions. Soit tu utilises un "Attendre x frames". Soit tu utilises un Déplacer Event.

(Sinon le `.class == String` tu peux écrire ça `.is_a?(String)`)

**Comment by Zer0xxxx** [comment]
Je vais utiliser une vieille astuce de Joke, du coup.
Je trouve ça moins funny, mais bon. :/

( Oh, merci ! :) )

**Comment by Zer0xxxxx** [comment]
Salut !
Je me permets juste un petit ajout : 

Il suffit de boucler sur event_move?(id) jusqu'à ce qu'il retourne "false" pour simuler un waitflag.
