### ISSUE TITLE
Pas de wait_flag sur les commandes "event_move" ?

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#351]
Salut !
Je n'ai pas vu l'argument "wait_flag" sur les commandes event_move (comme `event_move_left`), dans la doc'...

**Comment by BastienDuplessier** [comment]
Normal, si tu veux avoir le flag wait, utilise les move_routes.

**Comment by Zer0xxxxx** [comment]
Salut !
Je me permets juste un petit ajout : 

Il suffit de boucler sur event_move?(id) jusqu'à ce qu'il retourne "false" pour simuler un waitflag.
