### ISSUE TITLE
[Nouvelle Commande ?] Pouvoir changer le nom d'un événement ingame

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#354]
Salut !
Quand on écrit `event_name(me) = "Couscous"`, le jeu plante.

Serait-il envisageable que cette utilisation de la commande devienne possible ? :)

![image](https://user-images.githubusercontent.com/36828641/39420966-44020c56-4c67-11e8-88ef-5a5425be3490.png)

**Comment by xvw** [comment]
oui. `event_name(me) == "Couscous"`.

**Comment by Zer0xxxx** [comment]
`event_name(me) == "Couscous"
p event_name(me)`

M'affiche `EV017`.

**Comment by xvw** [comment]
Je pense que c'est une mauvaise idée parce que le nom des événements est défini par l'éditeur. Donc il faudrait créer une couche de persistance complémentaire... 
Ce que je te propose, c'est d'utiliser un label local pour stocker le nom et tu pourrais faire, à l'usage, `SL[:name] || event_name(me)` histoire que si SL[:name] n'existe pas, ils prennent l'event_name. Ou alors, en début de ton événement : `SL[:name] ||= event_name(me)`.

Ça te va ?

**Comment by BastienDuplessier** [comment]
Je suis d'accord. On ne modifie pas les éléments définis dans l'éditeur.
Les variables et labels locaux sont là pour ce genre de choses.

**Comment by Zer0xxxx** [comment]
@xvw Oui !
D'autant que je peux faire `SL[:truc, id]` si jamais on veut lire la SL dans un événement, voir injecter une valeur...

Ok ok ! ^^
