### ISSUE TITLE
[Bug ?] event_at et événements superposés

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#355]
Salut !
Si je fais `p event_at(10,7)` et qu'il y a deux événements en 10, 7
cela me retourne seulement un ID : le plus élevé.

(Donc si l'événement d'ID 2 et l'événement d'ID 4 sont en 10,7 : `event_at(10,7)` retourne `4`)

Que dois-je faire pour obtenir un array contenant tous les ID d'événement sur des coordonnées X et Y ?
Un sélecteur ? (Ce qui est, en l'état, déjà fait).

event_at aura-t-il une option pour pouvoir retourner un array plutôt que le fixnum le plus élevé ? (qu'on puisse choisir entre le fonctionnement actuel et un fonctionnement plus "Abouti" si jamais il y a bel et bien deux événements sur les coordonnées x et y pointées). :)

**Comment by xvw** [comment]
Il faut utiliser un selecteur.
