### ISSUE TITLE
Comportement de call_common_event

### ISSUE THREAD

**Issue by Zer0xxxx** [RMEx/RME#357]
Salut !
Le comportement de

`L[:ss_reset_savage_mode] = true`
`call_common_event(2)`

n'est pas le même que celui de : 

![image](https://user-images.githubusercontent.com/36828641/39428978-ab39973c-4c89-11e8-90d3-948b866cb8c3.png)

Démo fournie : 
[rme__demo.zip](https://github.com/RMEx/RME/files/1960832/rme__demo.zip)

Il faut aller sur la Testmap de "GHOSTS" et parler au personnage avec un foulard vert.
Sa page 1 inclut le code RME, sa page 2 le code avec l'appel d'événement commun d'RPG Maker.

Je n'ai pas inclu dans la démo de quoi "Toggle" pour voir la différence entre le comportement de RME et celui de base d'RPG Maker, désolé, il faudra éditer un peu le jeu pour voir. :'(

**Comment by Jauke** [comment]
Je teste ça. ; )

**Comment by Jauke** [comment]
Pour bien montrer l'exemple avec ce genre de démo, je pense qu'il serait bien de les rendre autonome, c'est à dire ne pas avoir besoin des RTP des VXAce pour tester. ; )

**Comment by Zer0xxxx** [comment]
Vraiment désolé.
C'est vrai que, d'habitude, je fais des efforts pour les rendre autonomes à la main, (grâce à l'anti no such file de Krosk notamment)... Mais là je ne l'ai pas fait, c'est vrai. :/
Et il faudra que tu "Toggle" manuellement depuis l'éditeur de VX Ace, entre la page 1 et la page 2 du perso' à la cape verte. ^^'

**Comment by BastienDuplessier** [comment]
Tu pourrais expliciter aussi le comportement attendu et le comportement constaté ?
Ca nous aiderait à comprendre le pourquoi du comment. Merci.

**Comment by Zer0xxxx** [comment]
Le comportement attendu est que l'événement soit joué directement après la ligne du `call_common_event`, comme si le code était injecté précisément à cet endroit-là de l'événement...

Ca ne semble pas être le cas ici, puisque quand je le lance via la commande RME, cet événement commun s'exécute à la fin de mon événement (donc, après les TP, en fait). oO
Très étrange.

**Comment by BastienDuplessier** [comment]
En effet. Au niveau de RME, on prévoit le lancement de l’évent commun dès que possible.
Coté commande de base, l’évent est chargé et exécuté dans la foulée.
@xvw @Jauke 
Qu'est ce qu'on fait ? On laisse comme ça ? On change la commande ou alors on fait deux commandes distinctes ?

Perso, je serais pour deux commandes distinctes :
- `call_common_event` qui garde son comportement (à des fins de retro compatibilités), on précisera que l’évent commun sera exécuté dès que possible. 
- `run_commun_event` qui là va exécuter directement l’évent commun
Refs
`Game_Interpreter`
```ruby
  #--------------------------------------------------------------------------
  # * Common Event
  #--------------------------------------------------------------------------
  def command_117
    common_event = $data_common_events[@params[0]]
    if common_event
      child = Game_Interpreter.new(@depth + 1)
      child.setup(common_event.list, same_map? ? @event_id : 0)
      child.run
    end
  end
```
`RME.rb`
```ruby
  def call_common_event(id)
    $game_temp.reserve_common_event(id)
  end
```

**Comment by xvw** [comment]
j'aime bien ta proposition @BastienDuplessier

**Comment by BastienDuplessier** [comment]
C'est fait. La feature arrivera avec la v1.4
