### ISSUE TITLE
[Nouvelle Commande] ballooning?

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#360]
(Néologisme, lol)

Les balloons de RPG Maker VX Ace sont très chouettes !

En revanche, il n'y a pas moyen de savoir si une émoticône est en train de se jouer sur la map (ni de savoir si une émoticône est en train de se jouer sur un événement référencé par un ID, du coup)...

Je pensais donc à une commande `ballooning?` et `ballooning?(id)`. (Je vous laisse trouver un nom.)
En espérant que ce ne serait pas trop compliqué à écrire...

**Comment by BastienDuplessier** [comment]
C'est un besoin bien trop spécifique, on ne le fera pas.
Par contre, tu peux utiliser `event(id).balloon_id > 0` et tu aura ton info.
