### ISSUE TITLE
[Documentation] Area et Region_ID

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#361]
Bonjour !
Il est très fréquent pour moi de confondre `in_area?` et `region_id`.

Serait-il possible de "Compléter" un peu leur description ?

region_id(x, y)
`Renvoie l'ID de la région pointée par les coordonnées X,Y`
=> `Renvoie l'ID de la zone de combat pointée par les coordonnées X,Y`

------------------------------------------------

in_area?(area, x, y)
`Vérifie si le point référencé par X, Y est inscrit dans la zone passée en argument`
=> `Vérifie si le point référencé par X, Y est inscrit dans la zone virtuelle passée en argument`

**Comment by acs-l** [comment]
**Même commentaire** 😅 : [`#362`](https://github.com/RMEx/RME/issues/362#issuecomment-415994488)
