### ISSUE TITLE
[Documentation] Diverses coquilles

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#362]
Ne pas oublier #361 (s'il vous plait)...

Il y a certains points que j'ai omis : 

- Remplacer partout `X,Y` (en respectant la case) par `X, Y` ?
- Remplacer partout 'évènement' par 'événement' ? (les deux orthographes sont correctes).
- Je n'ai pas pris en considération les majuscules et les points...

J'ai commencé à relire chaque commande une à une.

J'ai déjà relu toutes les commandes **Standards** et **Carte**.

## Quand j'avais à relever des erreurs sur une commande et que je voyais passer de nouveau des erreurs sur des exemples, je l'ai signalé dans la foulée.).

Je propose de décomposer comme suit pour les coquilles que j'ai pu relever :

- Nom de la commande
- Description
- Arguments
- Exemples d'event making fournis

Si j'omets un point, c'est que je n'ai rien vu.

## Carte

----------------------------------

# map_id
Orthographe : 1  ;  Espace(s) manquant(s) : 1

DESCRIPTION : 
`qui est plus sur!`
=> `plus sûr !`

EXEMPLES D'EVENT MAKING FOURNIS :
`Il y a t-il quelqu'un sur la case [...]` (*Un événement à une position aléatoire, premier message*) => `y a-t-il`

`Il s'appelle \V[13]!` (*Un événement à une position aléatoire, troisième message*) => `Il s'appelle \V[13] !` 

----------------------------------

# map_name
Espace(s) manquant(s) : 1

EXEMPLES D'EVENT MAKING FOURNIS :
`Ses dimensions sont \C[3]\V[12]x\V[13]\C[0]!` (*Informations sur la carte, premier message*) => `Ses dimensions sont \C[3]\V[12]x\V[13]\C[0] !`

----------------------------------

# id_at(x,y)
Orthographe : 2  ;  Espace(s) manquant(s) : 1

EXEMPLES D'EVENT MAKING FOURNIS :
`il y a t-il` (_Un événement à une position aléatoire, premier message_) => `y a-t-il`
`Il s'appelle \V[13]!` (*idem, troisième message*) => `Il s'appelle \V[13] !` 

`a la région 1,` (_Faire apparaitre des événéments dans une région, premier commentaire_) => `à la région 1`

----------------------------------

# tile_id
Orthographe : 2

TITRE DE L'EXEMPLE D'EVENT MAKING FOURNI :
`Flash des tile du même ID sur une carte` => `des tiles`

EXEMPLES D'EVENT MAKING FOURNIS :
`tout les` (*Flash des tile du même ID sur une carte, premier commentaire*) => `tous les`
`On parcour` (*idem, troisième commentaire*) => `On parcourt`

----------------------------------

# set_tile_where(layer, id, new_id)
Douteux : 2 (?)

DESCRIPTION :
`tous les tile` => `tous les tiles` (?)
(Cette orthographe de "tiles" a été utilisée dans la description de `delete_tiles(layer, id)`, par exemple.)

ARGUMENTS :
`Numero` => `Numéro` (?)
(De même.)

----------------------------------

# region_id(x, y)
Espaces manquants : 2

EXEMPLES D'EVENT MAKING FOURNIS :
`la région 2!` (*Le joueur est sur la zone 2, premier et second messages*) => `la région 2 !`

----------------------------------

# square_passable?
Orthographe : 2

EXEMPLES D'EVENT MAKING FOURNIS :
`on stock`(*Clignotement de la case pointée par la souris en fonction de son type, quatrième et cinquième commentaires*) => `on stocke`

----------------------------------

# get_tileset_id
Espace(s)... _en trop_ : 1

DESCRIPTION :
`l' ID` => `l'ID`

----------------------------------

# map_width
Espace(s) manquant(s) : 2  ;  Orthographe : 1

EXEMPLES D'EVENT MAKING FOURNIS :
`sont \C[3]\V[12]x\V[13]\C[0]!` (*Informations sur la carte, premier message*) => `sont \C[3]\V[12]x\V[13]\C[0] !` 
`il y a t-il` (*Un événement à une position aléatoire, premier message*) => `y a-t-il`
`Il s'appelle \V[13]!` (idem, troisième message) => `Il s'appelle \V[13] !`

----------------------------------

# map_height
Mêmes erreurs que sur map_width

----------------------------------

# damage_floor?
Mêmes erreurs que sur square_passable?

----------------------------------

# get_random_square(*region_id)
Orthographe : 1

Même erreur que id_at(x,y) ; dans l'exemple _Faire apparaitre des événéments dans une région_

----------------------------------

# get_squares_by_tile(layer, tile_id)
Orthographe : 1

Même erreur que sur tile_id ; dans l'exemple _Flash des tile du même ID sur une carte_

----------------------------------

# get_squares_by_terrain(terrain_tag)
Coquille : 1  ;  Douteux : 2

DESCRIPTION :
`Renvoie un tableau de cases pour un terrain_tag donné donnée.` => `Renvoie un tableau de cases pour un terrain_tag donné.`

EXEMPLES D'EVENT MAKING FOURNIS :
`On récupère les cases pour le terrain_tag stocké à V[13]` (*Flash des cases du même terrain_tag, second commentaire*) => `dans V[13]` (?)

`initialize` (*idem, quatrième commentaire*) => `initialise` (?)

----------------------------------------

## Standards

----------------------------------------

# message(value, *face_name, *face_index, *position, *background)
Coquilles : 1  ;  Douteux : 1

ARGUMENTS
`value -> Message à afficer` => `afficher`
`*face_name` -> `Nom du faceset (peut être remplacé par nil pour ne pas en afficher), il faut utiliser pour afficher plusieurs lignes` => `Utiliser quoi ? Est-ce que ce jutsu incomplet a, par ailleurs, sa place dans la colonne de l'argument *face_name ?`

----------------------------------------

# choice(array, index_if_cancelled, *value, *face_name, *face_index, *position, *background)
Coquillles : 4  ;  même problème que sur `message` : 1

ARGUMENTS
`array -> List des possibilité, par exemple ['oui', 'non', 'autre']` => `Liste des possibilités`
`index_if_cancelled -> Valeur a attribuer` => `Valeur à attribuer`
`*value -> Message à afficer` => `Message à afficher`
Même problème sur `*face_name` que sur `message`.

----------------------------------------

# flash_square(x, y, color)
Même erreur ("À V[13]") que `get_squares_by_terrain(terrain_tag)` sur l'exemple d'event making *Flash des cases du même terrain_tag*

----------------------------------------

# unflash_square(x, y)
Douteux : 2

ARGUMENTS
`x -> Coordonnées` => `Coordonnée` (?)
`y -> Coordonnées` => `Coordonnée` (?)

----------------------------------------

# flash_rect(x, y, width, height, color)

De même que `flash_rect(x, y, width, height, color)`

----------------------------------------

# unflash_rect(x, y, width, height)

Mêmes erreurs sur _Flash des tile du même ID sur une carte_ ("On parcour" et "tout les tiles" + le titre de l'exemple)

----------------------------------------

# get 

Douteux : 1  ;  Orthographe : 2  ; Espace(s) manquant(s) : 1

La boucle de _Parcourir simplement un tableau en événement_ fonctionne-t-elle vraiment ?
Je ne vois pas de commande `Attendre`.

`Nécéssite` (_QTE généré aléatoirement avec choix de la taille de la combinaison_, premier commmentaire) => `Nécessite`

`Combien d'éléments dans la combinaison?` (idem, premier message) => `combinaison ?`

`Erf, entraîne toi !` (idem, dernier message) => `entraîne-toi !`

----------------------------------------

# windowskin_tone(*tone)

Douteux : 2

DESCRIPTION :
`windowSkin` => `Windowskin` (?)

ARGUMENTS :
`WindowSkin` => `Windowskin` (?)

----------------------------------------

# windowskin_opacity(*value)

Douteux : 1

De même que `windowskin_tone(*tone)` pour la partie DESCRIPTION.

----------------------------------------

# split_each_char(str)

Orthographe : 2 

ARGUMENTS :
`str -> Chaine a transformer` => `Chaîne à transformer`

----------------------------------------

# qte(key, time, *strict)

Orthographe : 1

EXEMPLES D'EVENT-MAKING FOURNIS :

_QTE extrèmement simple_ (titre de l'exemple) => `QTE extrêmement simple`

Mêmes erreurs que dans `get` pour _QTE infini généré aléatoirement_

----------------------------------------

# has_prefix?(string, prefix)

Orthographe : 6

DESCRIPTION :
`Renvoie true si une chaine à le préfix donné, false sinon.` => `chaîne a le préfixe`

ARGUMENTS :
`string -> La chaine de caractère à vérifier` => `chaîne`
`prefix -> Le préfix devant être contenu dans la chaine` => `préfixe devant être contenu dans la chaîne`

----------------------------------------

# has_suffix?(string, suffix)

Orthographe : 6

DESCRIPTION :
`Renvoie true si une chaine à le suffix donné, false sinon.` => `chaîne a le suffixe`

ARGUMENTS :
`string	-> La chaine de caractère à vérifier` => `chaîne de caractères à vérifier`
`suffix -> Le suffix devant être contenu dans la chaine` => `suffixe devant être contenu dans la chaîne`

----------------------------------------

# has_substring?(string, substring)

De même que `has_suffix?(string, suffix)`

----------------------------------------

# create_light_emitters(hash)

Je n'ai pas compris la doc de cette commande.

----------------------------------------

# menu_disabled?

Douteux : 1

DESCRIPTION :
`aux menus` => `au menu` (?) ... (il n'y en a qu'un ?)

----------------------------------------

# menu_enabled?

De même que `menu_disabled?`

----------------------------------------

# encounter_disabled?
Orthographe : 1

DESCRIPTION :
`Renvoie true si les rencontres sont désactivés, false sinon` => `désactivées`

----------------------------------------

# encounter_enabled?
Orthographe : 1

DESCRIPTION :
`Renvoie true si les rencontres sont activés, false sinon` => `activées`

----------------------------------------

# formation_disabled?
Orthographe : 1

DESCRIPTION :
`Renvoie true si les formations sont désactivés, false sinon` => `désactivées`

----------------------------------------

# formation_enabled?
Orthographe : 1

DESCRIPTION :
`Renvoie true si les formations sont activés, false sinon` => `activées`

----------------------------------------

# file_write(filename, content)
Orthographe : 2

DESCRIPTION :
`Ecrit une chaine de caractère dans un fichier. Si le fichier existe, son contenu est écrasé` => `chaîne de caractères`

----------------------------------------

**Comment by acs-l** [comment]
Est-ce que tu pourrais refaire une nouvelle **_issue_ pour chaque problème** (en respectant le nouveau _template_ : [`🇫🇷 • Mauvaise documentation`](https://github.com/RMEx/RME/issues/new?template=fr.documentation_issue.md)), s'il-te-plaît ? C'est plus facile pour moi de tracer les éléments à corriger de cette façon 😅.

---

Autrement, voici une petite astuce si tu veux rendre la lecture plus facile entre la précédente version de la documentation (`-`), et celle amendée de tes corrections (`+`) 😉 :

<pre>
```diff
- Ecrit une chaine de caractère dans un fichier. Si le fichier existe, son contenu est écrasé
+ Écrit une chaîne de caractères dans un fichier. Si le fichier existe, son précédent contenu est écrasé !
```
</pre>

Ce qui donne le rendu suivant :

```diff
- Ecrit une chaine de caractère dans un fichier. Si le fichier existe, son contenu est écrasé
+ Écrit une chaîne de caractères dans un fichier. Si le fichier existe, son précédent contenu est écrasé !
```
