### ISSUE TITLE
[Nouvelle commande] maths : abs

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#363]
Salut !
Une commande pour calculer la différence entre deux variables serait-elle possible ?

Définie comme : 
`difference(x, y) = | x - y |`

EDIT : 
Il s'agissait d'une confusion (je programmais un système où il était question de valeur absolue et de *Distance* entre deux points sur la map, sans éventuellement vouloir connaître l'orientation du vecteur que l'on pourrait tracer du point A au point B...

Pardon aux physiciens et matheux que j'ai pu, involontairement, insulter en n'utilisant pas les bons mots.)

**Comment by BastienDuplessier** [comment]
Tu parles bien de la valeur absolue de la différence ?

**Comment by xvw** [comment]
Je pense qu'une fonction "valeur absolue" suffit largement.

**Comment by Zer0xxxxx** [comment]
@BastienDuplessier Ah !
Oui, pardon !

C'est vrai que dans ce cas-là, je me fous un peu d'éventuellement savoir si "J'avance" ou "Recule" sur le plan cartésien, avec ce calcul de différence-là.

Pardon pour l'imprécision.

**Comment by BastienDuplessier** [comment]
Donc on va plutôt partir sur une fonction `abs(x)` qui va donner en retour la valeur absolue de x.

**Comment by Zer0xxxxx** [comment]
Oui !
Je m'étais mal exprimé.

**Comment by BastienDuplessier** [comment]
Les changements ont été fusionnés avec la branche de développement et arriveront avec la version 1.4 de RME.
