### ISSUE TITLE
[Question] Que fait actuellement le "Unsafe_mode" de RME ?

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#367]
Bonjour !
L'unsafe mode de RME permet donc de pouvoir utiliser `Resolution.change`, mais que permet-il de faire d'autre ? J'aimerais juste savoir, très brièvement, ce qu'apporte le "Unsafe" de RME, sans demande de support ni de documentation.

Est-il possible d'avoir un "Listing", très synthétique ? :) 

Merci d'avance pour votre réponse.

**Comment by BastienDuplessier** [comment]
Actuellement, rien d'autre.
