### ISSUE TITLE
[Documentation] Documenter distance_between ?

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#368]
Salut !
Quand je fais `p distance_between(:yolo, me, 0)` depuis un appel de script dans un événement, la console me retourne la distance... en pixels (si je change le flag pour `:square`, ça me fait un `squares_between`.)

Je vois les commandes `pixels_between`, `squares_between`, et `between` dans la doc', mais je ne vois pas `distance_between`.

L'appel de `distance_between` depuis un appel de script dans un événement est-il impropre ?
Je me sens bête d'avoir utilisé `between` (parce que dans mon cas, `distance_between` est bien plus adapté...), pour le coup. x)

EDIT ; Tiens, il y a aussi la commande `pixels_between` dont j'ignorais encore l'existence, qui appelle `distance_between` avec un flag `:pixel`...

Du coup, peut-être "Déprécier" `squares_between` et `pixels_between` et rediriger vers `distance_between` qui peut aussi bien faire l'un que l'autre ? (Ou au moins la documenter aussi ? ^^')

Pardon, j'ai du mal à comprendre. :x

**Comment by xvw** [comment]
distance_between est utilisée pour implémenter "pixels_between" et "squares_between". Elle n'est pas documentée parce que la bonne pratique est d'utiliser les deux autres.

**Comment by Zer0xxxxx** [comment]
Oké.
J'étais un peu perdu. Merci pour cette réponse.
