### ISSUE TITLE
Fonder un nouveau forum ? Donner de nouveau de la visibilité à l'ancien ?

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#369]
Salut !

Je réalise en ce moment de nombreux systèmes avec RME.
La question que je me pose actuellement est : où vais-je les partager, sous quelle forme, et comment, si l'envie m'en prend (ainsi que de faire des tutos) ?

Plutôt dans le wiki ?
Plutôt un forum (exclusivement RME) ?

**Comment by BastienDuplessier** [comment]
Question non appropriée à Github.
Tu devrais passer par Discord pour poser ces questions.
Autrement, tu peux tenir un blog et poster tes démos sur itch.io, puis diffuser tes tutos sur les diverses commu de making qui existent.
