### ISSUE TITLE
[Bug?] player_teleport ne fait que des fondus noirs ?

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#370]
Salut !

Quand je fais : 
`player_teleport(1, player_x, 9, 2)`

La téléportation se joue avec un fondu noir.
De même pour 
`player_teleport(1, player_x, 9, 1)`

et

`player_teleport(1, player_x, 9, 0)`

http://rmex.github.io/RMEDoc/#player_teleport

**Comment by BastienDuplessier** [comment]
`player_teleport(map_id, x, y, *direction, *fade_type)`
Le 4eme paramètre est la direction, pas le fade_type. Si tu ne veux pas changer de direction je t'invite à utiliser `player_direction` comme paramètre.
Attention avec les tonnes d'issues créées pour rien. Prends le temps de bien lire la documentation, de faire des tests et de poser des questions via le discord ou des gens pourront t'aider.
