### ISSUE TITLE
Retour à #366

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#371]
Bonjour !

Zangther a répondu brillamment concernant #366 pour ce qui est de pouvoir utiliser certaines fonctionnalités d'RPG Maker dans les noms des objets.

J'ai manqué de clarté et j'ai fait une seule issue pour deux problèmes : pour tout ce qui est "Renommer les objets ingame", quelle est votre réponse ?

EDIT : Il est vrai que grâce à la manip' proposée par Zangther, on peut tout de même stocker les noms des objets dans une variable et utiliser `\V[truc]`, ce qui reste une solution !

**Comment by BastienDuplessier** [comment]
Ce qui est dans la base de donnée est statique. La manière dont RPG maker gère les objets est directement liée à cette staticité. RME ne proposera pas une modification de ce système là.
Je pense que tu devrais plutôt regarder du coté des script d'objets dynamiques.
