### ISSUE TITLE
Nouvelle commande : area(x,y)

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#374]
Salut !
Cette commande me semble assez pénible puisque plusieurs zones peuvent se superposer. :( 
(Peut-être retourner un Array le cas échéant ?)

Je pensais à une commande `area(x,y)`, retournant la zone virtuelle -s'il y en a une- de coordonnée `x` et `y`.

**Comment by BastienDuplessier** [comment]
Si tu parles des zones RPG maker, elle ne peuvent pas se superposer.
Pour ce qui est des area RME, elles ne sont pas stockées. Donc pas de possibilité de faire cette commande.
