### ISSUE TITLE
Bug: Animation qui se stoppe brutalement.

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#382]
Je viens de trouver un bug assez gênant. 
Le fait d'invoquer un event via "invoke_event" pendant qu'une animation se joue, ça coupe net l'animation.
![buganimation1](https://user-images.githubusercontent.com/15834672/39809419-017e15a6-5382-11e8-9e5e-867b18e9bedb.gif)
(animation normal, le gif coupe net mais c'est une question de poids)
![buganimation2](https://user-images.githubusercontent.com/15834672/39809455-21a04cd2-5382-11e8-9829-f7c9a32ddf52.gif)
(animation avec invoke_event)

**Comment by BastienDuplessier** [comment]
J'ai trouvé la cause du bug et j'ai fixé le soucis.
Ca arrivera avec la v1.4.1
