### ISSUE TITLE
Error with call_common_event

### ISSUE THREAD

**Issue by LucasDevos** [RMEx/RME#384]
![image](https://user-images.githubusercontent.com/24318013/40446873-f52a6066-5ed0-11e8-8927-1d9a601a9289.png)

By replacing the common event call (using the RM command) by its RME counterpart in my system, I have this error.
I'm not sure what's the cause and it's not a problem for me since I can still use the basic RM command, I just wanted to let you know.

Also, common events called with the RME command seem to be called too late? See picture attached

![image](https://user-images.githubusercontent.com/24318013/40447330-7cae6266-5ed2-11e8-8165-43d65e5fb1ba.png)

**Comment by BastienDuplessier** [comment]
Yeah, that's something we already know.
`call_common_event(id)` will call the specified common event whenever it will be possible, usually at the end of the event.
In v1.4 there will be a command `include_common_event(id)` which will do the same as the classic event command : call the common event immediately.

**Comment by BastienDuplessier** [comment]
My bad did'nt see the first problem aha.
Can you give us more insight on what triggers the error ? 
Usually this means that you have an error in your script call.

**Comment by LucasDevos** [comment]
There's a lot going on in my system so I'll have to investigate. I have currently no idea on what may trigger the error - but I guess it is related to the difference between `call_common_event(id)` and the classic event command, as the latter causes no issue.

I'll update you if I somewhat manage to be more specific!

**Comment by BastienDuplessier** [comment]
Maybe you are using `me`. As the event is finished with `call_common_event(id)`, `me` might be nil at this time.

**Comment by BastienDuplessier** [comment]
As there's no news about this. I consider this issue closed.
Feel free to comment if you have any news.
