### ISSUE TITLE
[Documentation: erreur] Position par défaut de `camera_scroll_towards`

### ISSUE THREAD

**Issue by Hinola** [RMEx/RME#391]
### Localisation de l'erreur

- **Version de la documentation** : `1.4.0`
- **Localisation** :
  - *Commande*: `camera_scroll_towards(x, y, nb_steps, easing = :InLinear, position = :centered)`

Sur la doc la position par défaut de camera_scroll_towards est donné comme étant " haut gauche de l'écran "; mais ce n'est pas le cas dans la fonction :
```ruby
def camera_scroll_towards(x, y, nb_steps, easing = :InLinear, position = :centered)
```

Du coup je sais pas le quel est le mieux, entre corriger le script ou la doc.

**Comment by acs-l** [comment]
[**Commandes de caméra difficile à utiliser sécuritairement** `#276`](#276) : 
  - Changement de valeur par défaut effectué par @grrim (`position = :top_left` => `position = :centered`), mais pas répercuté dans la documentation;
  - Travail toujours en cours de @Jauke sur l'*issue*.

(Je laisse le soin à Zangther ou Joke de clôturer cette *issue* une fois que #276 sera clôturée elle aussi)
