### ISSUE TITLE
[Documentation] Ajout des différents types de transitions (`EasingFunction`)

### ISSUE THREAD

**Issue by aureliendossantos** [RMEx/RME#398]
Ce serait bien d'ajouter au wiki la liste des types de `ease`, actuellement c'est un peu difficile de les expliquer aux gens parce qu'on les trouve uniquement dans la recherche du serveur Discord.

Pour rappel il y a, d'après le message sur Discord : 

Linear
Quad
Cubic
Quart
Quint
Sine
Expo
Circ
Back
Elastic
Bounce
En ajoutant :In :Out ou :InOut devant.

**Comment by acs-l** [comment]
Devrait être résolu avec : [[RME] **Commands' documentation**](https://github.com/RMEx/RME/issues/264) (#264)

(Je clôturerai l'*issue* une fois que celle référencée sera terminée 😄)
