### ISSUE TITLE
Reintegrer le testeur de commandes

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#4]
Trouver une manière propre de réintégrer le testeur de commandes.
- [x] done

@Jauke

**Comment by Jauke** [comment]
On peut ré-intégrer le **SDK.Gui.rb** tel qu'il est dans le package.rb (il dépend de **Internal.rb**), jusqu'à maintenant je n'ai eu aucun problème avec, et si quelqu'un rencontre un problème ça me permettra d'avancer.

Le testeur de commandes re-fonctionnera.

**Comment by xvw** [comment]
do it :)
et fait une nouvelle version :)

**Comment by Jauke** [comment]
[x] done
