### ISSUE TITLE
[Outils de développement] Erreurs "Appel de script" non explicites

### ISSUE THREAD

**Issue by BastienDuplessier** [RMEx/RME#402]
Une chose très frustrante quand on utilise RME ce sont les erreurs dans les appels de script.
On se tape toujours du "error on line XXX in RME.rb", ligne qui correspond à la méthode `eval` liée à l'appel de script.
J'aimerais qu'on essaye de rendre les messages d'erreurs plus explicite en indiquant le contenu de la ligne, l'event concerné (ligne, page, event_id, map_id), et tout ce qu'on pourrait ajouter pour rendre les choses plus simples à debugger.

**Comment by xvw** [comment]
On avait un truc comme ça ... avant, MAIS, à la demande de @hyperaho ça avait été retiré... pour je ne sais plus quelle raison :/
