### ISSUE TITLE
Nouvelles commandes : Changer les passabilités dynamiquement

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#407]
Salut !

Je songeais à une commande permettant de changer la passabilité d'un tile... genre "Forcer" tous les tiles dont l'ID est 50, sur le layer 2, à passer en étoile. Ou en croix. Ou en rond...

Une telle commande serait-elle envisageable, même pour dans quelques années ?

**Comment by BastienDuplessier** [comment]
Je pense que tu devrais utiliser la commande [`set_tile_where`](http://rmex.github.io/RMEDoc/#set_tile_where "RMEdoc pour set_tile_where")
Ca te "force" à dupliquer certains tiles mais c'est encore la solution la plus simple pour régler ton problème. Je ne pense pas qu'on développera cette commande. Du moins pas dans l'immédiat.
