### ISSUE TITLE
Comportement de event_move_with ?

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#409]
Salut !
Lorsque je fais, dans un **processus parallèle** :
```
Script: event_move_with(0, [32])
Attendre 300 frames
```

Mon héros est alors définitivement freeze.

J'ai aussi essayé : 

```
Script: event_move_with(0, [32, 0])
Attendre 300 frames
```

Même résultat...

**Comment by BastienDuplessier** [comment]
Ok, donc y'avait deux choses.
1 : La commande ne prend pas un tableau d'éléments. Il faut les passer sans tableau `event_move_with(0, 32)`

2 : La commande faisait des move_route répétable par défaut. Elles sont désormais à usage unique.

Le fix arrivera avec la version 1.4.1
