### ISSUE TITLE
Appeler include_page depuis un processus parallèle...

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#416]
Salut !
Si, depuis une page en processus parallèle, je fais : 
`include_page(map_id, me, 4, true, true)`

Et que cette fameuse page '4' est en "Touche action", et contient le code : 

- téléporter l'équipe
- désactiver interrupteur 30
- désactiver interrupteur 25

Alors les lignes : 

- désactiver interrupteur 30
- désactiver interrupteur 25

Sont ignorées.

Pourtant, j'ai bien mis "context" à true... Donc je pensais que ma page allait se lancer exactement comme se lance tous les autres déclenchements que "Processus parallèle"... C'est-à-dire : exécuter toutes les actions, même si le trigger passe à false ou que l'on change de map.

:/

**Comment by BastienDuplessier** [comment]
Ok, j'ai réussi à reproduire. Je vais fixer ça.

**Comment by BastienDuplessier** [comment]
Au final, il ne s'agit pas d'un bug. J'ai investigué un peu et il se trouve que la commande se comporte exactement comme l'invocation d'un event commun. (cf la doc : Invoque une page (comme s'il s'agissait d'un évènement commun) d'un autre évènement)
Il se trouve que quand tu appelles dans un event un event commun (ou une page), et que dedans tu fais une téléportation, tout ce qui se trouve après sera ignoré.
Donc pas de soucis, je t'invite juste à mettre tout ce qui est à faire avant la téléportation.
