### ISSUE TITLE
[Problème] `choice` (la fenêtre d'options ne partage pas le même background que celle du message)

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#421]
### Configuration (lorsque le bug a été rencontré)

- **Version de RME** : `1.4.0`
- **Commande** : `choice`

---

### Description du bug

Si je fais : 
```ruby
choice(["oui", "non", "peut-être"], 1, "Test", nil, nil, 2, 1)
```

Le résultat est : 

![image](https://user-images.githubusercontent.com/38897000/43686400-5e1ddd54-98c5-11e8-951f-96cd2d7415b4.png)

#### Comportement attendu

Je m'attendais à ce que la fenêtre de choix soit également "Sombre", puisque j'ai précisé `1` en argument `background` sur la commande `choice`...

#### Étapes permettant de reproduire le problème

Utiliser l'appel de script suivant dans un événement en "`Touche action`": 
```ruby
choice(["oui", "non", "peut-être"], 1, "Test", nil, nil, 2, 1)
```

**Comment by xvw** [comment]
C'est le même comportement que la commande événementielle. 
Si tu fais un message et qu'en suite tu affiches un choix, peu importe le background que tu auras choisi, la fenêtre aura le WindowSkin par défaut.
