### ISSUE TITLE
Bug sur la commande message ?

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#422]
### Configuration (lorsque le bug a été rencontré)

- **Version de RME** : `1.4.0`
- **Commande** : `message`

---

### Description du bug

J'obtiens ce message d'erreur, et le jeu crash : 
![image](https://user-images.githubusercontent.com/38897000/43688444-1aa733ee-98e9-11e8-8e9f-26996429b8c1.png)

_(C'est pas moi qui ai nommé le script "XAVIER" sur ce projet RM, hihi...)_

#### Comportement actuel

> Si, dans un script en-dessous de RME, j'écris : 
```ruby
module BoubouCommands
  def cool_command
    Command.message("Cool !")
  end
  append_commands
end
```

Puis, que depuis un appel de script, je fais :
`cool_command`

Alors, j'obtiens le message d'erreur ci-dessus, et le jeu crash...
Pourtant, le script call est lancé par un événement, sur une map où il n'y a que lui. En touche action.

#### Comportement attendu

Que le message "Cool !" s'affiche.

#### Étapes permettant de reproduire le problème

Créer le petit script (module contenant la commande "`cool_command`").
Appeler `cool_command` depuis un appel de script dans un événement.

**Comment by Zer0xxxxx** [comment]
Salut !
J'ai trouvé une solution.

Il suffit de ne PAS utiliser `Command.`
Si on lance la commande depuis un appel de script depuis un événement, c'est OK. (Et je ne vois pas d'intérêt à lancer une commande semblable ailleurs).

Par exemple, j'ai fait ça : 

```ruby
module BoubouCommandsForCorbeau
# * ... :v

    def verbose_get_item(id = 0, amount = 0, pos = 2, background = 1, string = "Vous avez obtenu #{amount} #{item_name(id)}")
        if amount != 0 and id != 0
            blablabla = item_name(id)
            message_height(1)
            if amount > 1
                 message(string + "s !", nil, nil, pos, background)
            else
                message(string + " !", nil, nil, pos, background)
            end
            message_height(4)
            give_item(id, amount)
        end
    end    
    
append_commands

end```

**Comment by BastienDuplessier** [comment]
Yo. Du coup, on peut fermer cette issue ?

**Comment by Zer0xxxxx** [comment]
Je ferme l'issue pour le moment.

**Comment by acs-l** [comment]
Je ne pense pas que le problème vienne de l'invocation de la commande via `Command`. Je regarderai ça plus tard.
