### ISSUE TITLE
Bug sur picture_show_screenshot

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#423]
### Configuration (lorsque le bug a été rencontré)

- **Version de RME** : `1.4.1`
- **Commande** : `picture_show_screenshot`

---

### Description du bug

`picture_show_screenshot` est buggué...

#### Comportement actuel

> Salut ! Si j'utilise cette portion de script dans un événement en touche action : 
```ruby
picture_show_screenshot(100, 544/2, 416/2, 1, 100, 100, 76)
picture_move(100, 544/2, 416/2, 150, 150, 180, false, 0)
wait(180)
```

La première fois, ça fonctionne super !
Maintenant, je déplace mon joueur et vais parler au même événement en étant ailleurs sur l'écran et... C'est toujours le screenshot précédent qui est affiché. :/
Je pensais résoudre le souci par l'ajout de cette commande à la fin de mon appel de script : 
`picture_erase(100)`

Que nenni ! En faisant cela, la picture ne s'affiche plus du tout au prochain appel d'exactement la même portion de script !

#### Comportement attendu

Je pense que `picture_show_screenshot` devrait prendre un nouveau screenshot à chaque utilisation de la commande.

#### Étapes permettant de reproduire le problème

Utiliser plusieurs fois la portion de script suivante, en changeant son joueur de place entre les différents appels : 

```ruby
picture_show_screenshot(100, 544/2, 416/2, 1, 100, 100, 76)
picture_move(100, 544/2, 416/2, 150, 150, 180, false, 0)
wait(180)
```

ou encore : 

```ruby
picture_show_screenshot(100, 544/2, 416/2, 1, 100, 100, 76)
picture_move(100, 544/2, 416/2, 150, 150, 180, false, 0)
wait(180)
picture_erase(100)
```

**Comment by Zer0xxxxx** [comment]
https://image.ibb.co/mpSz0e/boubou_toutcasser.gif

**Comment by acs-l** [comment]
De mon point de vue, il y a une mauvaise gestion du cache au niveau des `Sprite_Picture` ([`#swap_cache`](https://github.com/RMEx/RME/blob/master/src/EvEx.rb#L4154)), et ça aboutit à ton problème.

En fait, chaque `Sprite_Picture` (qui gère l'affichage d'une image) est associé à une instance de `Game_Picture` (qui elle définit structurellement l'image). En utilisant une deuxième fois la commande `picture_show_screenshot`, tu modifies bien l'objet `Game_Picture`; mais l'objet `Sprite_Picture` qui l'englobe n'a aucun moyen de savoir que ce premier a été modifié. Du point de vue de `Sprite_Picture` rien n'a changé. Il t'affiche donc l'image qu'il a déjà affiché auparavant.

---

**Deux solutions** : 
1. Tu forces manuellement le rafraîchissement de l'objet `Sprite_Picture` avant chaque appel à `picture_show_screenshot`
```ruby
def erase_picture_sprite(id_picture)
  SceneManager.scene
              .instance_variable_get(:@spriteset)
              .instance_variable_get(:@picture_sprites)[id_picture] = nil
end

# Example d'utilisation
erase_picture_sprite(100)
picture_show_screenshot(100, 544/2, 416/2, 1, 100, 100, 76)
picture_move(100, 544/2, 416/2, 150, 150, 180, false, 0)
wait(180)
```

2. Tu ajoutes un nouveau script avec le palliatif suivant (qui sera plus ou moins celui qui sera ajouté à **RME**)
```ruby
class Game_Picture

  alias_method :old_show, :show
  def show(name, origin, x, y, zoom_x, zoom_y, opacity, blend_type)
    old_show(name, origin, x, y, zoom_x, zoom_y, opacity, blend_type)
    @update_sprite = true
  end

  def update_sprite?
    @update_sprite
  end

  def sprite_updated
    @update_sprite = false
  end

end


class Sprite_Picture

  def swap_cache
    if :screenshot.eql? @picture.name
      return self.bitmap unless @picture.update_sprite?
      @picture.sprite_updated
      return Graphics.snap_to_bitmap.clone
    end
    return Cache.swap(@picture.name)
  end

end
```

**Comment by Zer0xxxxx** [comment]
Super !
Merci beaucoup !
