### ISSUE TITLE
nouvelle commande : is_tile_id?(tile_id, x, y)

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#430]
Salut !
Je songeais à une commande sous la forme : 

`is_tile_id?(tile_id, x, y)`

Qui permettrait, par exemple, d'écrire : 
`is_tile_id?(95, player_x, player_y)`

Et retournerait "True" si la case sur laquelle se situe le joueur contient bien une case où l'on retrouvait le tile ayant pour ID 95.

# Pourquoi pas la commande `tile_id` ?

`tile_id` est une chouette commande, mais elle demande un argument `layer`. Alors que la commande à laquelle je pense, `is_tile_id?`, se débrouillerait sans. Ce sont deux commandes distinctes.
Il me semble que RPG Maker est conçu de sorte qu'aucun tile n'ait le même ID qu'un autre de tout le Tileset.

On peut donc "Inférer" à quel layer il appartient par la lecture de son ID...

Ou tout simplement d'abord vérifier la présence du `tile_id` "95" sur le layer 0, puis le 1, puis le 2 ? (c'est ce que je fais actuellement avec un filtre qui est probablement pas très joliment utilisé... : `any?`)

Pensez-vous que cette commande pourrait être chouette ?

Merci d'avance pour vos réponses. :)

**Comment by BastienDuplessier** [comment]
Perso, je ne pense pas que cette commande serait utile. Si tu sais ce que tu cherches, cible directement le layer que tu veux. Sinon, boucle sur les layers `[0,1,2]` C'est faisable en une ligne.
