### ISSUE TITLE
[Nouvelles Commandes] : `event_lock_direction` et `event_direction_locked?`

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#431]
#### Objectif des deux commandes

J'aurais besoin d'une commande permettant :
- d'**activer ou** de **désactiver la "_Direction fixe_"** d'un ou plusieurs événements;
- de **savoir si un événement est en "_Direction fixe_"** ou non.

#### Syntaxe de la commande

- [ ] `event_lock_direction(ids, value)` : active (`value = true`) ou désactive (`value = false`) la "_Direction fixe_" des événements;
- [ ] `event_direction_locked?(id)` : retourne `true` si la "_Direction fixe_" est activée pour l'événement; `false` autrement.

Voir aussi : [la commande `event_through`](http://rmex.github.io/RMEDoc/#event_through)

**Comment by Zer0xxxxx** [comment]
Salut !
Peut-être également créer des commandes pour "Animer à l'arrêt", et "Marche animée" ?

**Comment by BastienDuplessier** [comment]
Cf : https://github.com/RMEx/RME/issues/442
`event_direction_fix(id) : Bool` : Renvoie la valeur
`event_direction_fix(id, value)` : Définit la valeur
