### ISSUE TITLE
[Mis-à-jour de commande] `picture_opacity` (retourner l'opacité d'une image)

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#433]
#### Objectif de la commande

La commande `picture_opacity(ids, opacity, *duration, *wait_flag, *ease)` actuelle permet de modifier l'opacité d'une ou plusieurs images.

J'aimerai disposer d'une commande me permettant de récupérer l'opacité actuelle d'une image sans pour autant la modifier.

#### Syntaxe de la commande

- [ ] `picture_opacity(ids)` : retourne la valeur d'opacité actuelle des images (*pictures*)

*Exemple :*
```ruby
# Supposons que nous avons trois images d'affichés avec les propriétés suivantes :
#  - (id : `1`, opacity : `255`)
#  - (id : `2`, opacity : `0`)
#  - (id : `3`, opacity : `200`)

picture_opacity(1)
# -> Devrait retourner : [255]

picture_opacity([1, 2, 3])
# -> Devrait retourner : [255, 0, 200]
```

**Comment by BastienDuplessier** [comment]
Je ne pense pas qu'on puisse qualifier ça de soucis.
La commande est documentée comme "Change l'opacité d'une image", c'est ce qu'elle fait. Donc pas d'incohérence de ce coté là.

Par contre, c'est vrai qu'on pourrait implémenter le comportement "get" comme pas mal d'autres commandes.
