### ISSUE TITLE
[Nouvelle commande] `map_editor_name`

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#434]
#### Objectif de la commande

La commande `map_name` actuelle renvoie le champ `Nom affiché` de la carte (**et pas celui du dessus !**) :
![image](https://user-images.githubusercontent.com/38897000/44572549-6a8dce00-a784-11e8-90aa-c2a93340686b.png)

L'idée serait de créer une nouvelle commande permettant d'avoir le nom de la carte (*map*) utilisée dans l'éditeur (champ `Nom`).

#### Syntaxe de la commande

- [ ] `map_editor_name(id)` : retourne le nom de la carte d'identifiant `id`, telle qu'utilisée dans l'éditeur.

**Comment by BastienDuplessier** [comment]
Visiblement ce nom n'est pas récupérable en jeu.
Je laisse ouvert au cas ou quelqu'un ait une idée mais y'a des chances qu'on n'implémente pas ça.

**Comment by xvw** [comment]
@Zer0xxxxx  tu peux utiliser la base de données étendue.
`VXACE_MAP[id].name`
