### ISSUE TITLE
[Mise-à-jour de commande] `map_name` (récupérer le nom de n'importe quelle map)

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#435]
#### Objectif de la commande

Pouvoir obtenir le "`Nom affiché`" de n'importe quelle carte (*map*), et pas seulement de la carte courante (*fonctionnement actuelle de la commande `map_name`*).

#### Syntaxe de la commande

- [ ] *`map_name(id)`* : retourne la valeur du champ "`Nom affiché`" (telle que déclaré dans l'éditeur) pour la carte d'identifiant (`id`)

**Comment by xvw** [comment]
Il suffit d'utiliser la base de données étendue.
https://github.com/RMEx/RME/wiki/Base-de-donn%C3%A9es-extensible
