### ISSUE TITLE
[Nouvelle commande] `event_trigger` (ajout du comportement _get_)

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#439]
#### Objectif de la commande

Retourner le type de déclenchement de l'événement :
- `0` : l'événement se déclenche avec la **touche action**;
- `1` : l'événement se déclenche au **contact du héros**;
- `2` : l'événement se déclenche **automatiquement**;
- `3` : l'événement se déclenche en **processus parallèle**.

#### Syntaxe de la commande

- [ ] `event_trigger(ids)` : retourne le mode de déclenchement de l'événement (*telle que défini pour sa page actuelle*)

---

**Commande existante** (comportement _set_) : [`event_trigger(ids, mode)`](http://rmex.github.io/RMEDoc/#event_trigger)

**Comment by xvw** [comment]
http://rmex.github.io/RMEDoc/#event_trigger
