### ISSUE TITLE
[Nouvelles commandes] `Window_spritesheet`

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#440]
### Définition des commandes

> Cette demande risque d'être confuse. Je n'ai pas vraiment d'idée de comment formuler la demande, ni de comment celle-ci pourrait être implémentée...

#### Objectif des commandes

J'aimerai pouvoir intégrer des _spritesheets_ dans les fenêtres (_windows_).
Ceci me permettrait de personnaliser le contenu de mes fenêtres en ajoutant par exemple :
- des images;
- des icônes animées;
- des textes animés;
- ...

Voire pouvoir créer des fenêtres intégralement constituées de _spritesheets_.

**Comment by BastienDuplessier** [comment]
Pour moi c'est non.
Les fenêtres sont déjà assez difficiles à utiliser comme ça.
Si les spritesheets RME ne peuvent pas se placer par dessus des fenêtres, je te conseille d'utiliser tes propres windows via les scripts.

Si quelqu'un pense qu'on devrait ajouter cette feature quand même (et veut l'implémenter) je le laisserais réouvrir l'issue.
