### ISSUE TITLE
[Nouvelles commandes] `event_enable_stepping_animation` et `event_stepping_animation_enabled?`

### ISSUE THREAD

**Issue by acs-l** [RMEx/RME#441]
#### Objectif des deux commandes

J'aurais besoin d'une commande permettant :
- d'**activer** ou de **désactiver** le fait qu'un ou plusieurs **événements soient "_Animés à l'arrêt_"**;
- de **savoir si un événement est "_Animé à l'arrêt_"** ou non.

#### Syntaxe de la commande

- [ ] `event_enable_stepping_animation(ids, value)` : active (`value = true`) ou désactive (`value = false`) le fait que les événements soient "_Animés à l'arrêt_";
- [ ] `event_stepping_animation_enabled?(id)` : retourne `true` si l'événement est "_Animé à l'arrêt_"; `false` autrement.

**Comment by BastienDuplessier** [comment]
Cf : https://github.com/RMEx/RME/issues/442
`event_step_animation(id) : Bool` : Renvoie la valeur
`event_step_animation(id, value)` : Définit la valeur
