### ISSUE TITLE
[Nouvelles commandes] `event_enable_walking_animation` et `event_walking_animation_enabled?`

### ISSUE THREAD

**Issue by acs-l** [RMEx/RME#442]
#### Objectif des deux commandes

J'aurais besoin d'une commande permettant :
- d'**activer ou** de **désactiver la "_Marche animée_"** d'un ou plusieurs événements;
- de **savoir si un événement est en "_Marche animée_"** ou non.

#### Syntaxe de la commande

- [ ] `event_enable_walking_animation(ids, value)` : active (`value = true`) ou désactive (`value = false`) la "_Direction fixe_" des événements;
- [ ] `event_walking_animation_enabled?(id)` : retourne `true` si la "_Marche animée_" est activée pour l'événement; `false` autrement.

**Comment by BastienDuplessier** [comment]
On va garder le comportement pour la plupart des autres commandes :
`event_enable_walking_animation(id) : Bool` : Retourne la valeur
`event_enable_walking_animation(id, value)` : Définit la valeur.

Sinon ça fait des noms trop verbeux.
