### ISSUE TITLE
Rendre RME plus modulable ?

### ISSUE THREAD

**Issue by ImCaptainMorgan** [RMEx/RME#445]
(je n'ai rien compris au système de formulaires désolé)

RME est un merveilleux projet
néanmoins je pense qu'il faudrait le rendre moins monolithique

par exemple : pouvoir choisir par soi-même si l'on utilise les contrôles Input de RME ou non

### Inputs
RM est déjà suffisamment chiant avec son module Input à moitié caché... et pour ma part je suis trop habitué à Input Ultimate de Zeus, ou parfois l'implémentation de XInput de Lone Wolf

### Easing
j'utilise pour ma part mes propres easing et il est quelque peu dommage qu'RME se montre turbulent sur TOUS les déplacements d'rPG maker. Peut-être envisager un "Proc" désactivable pour le easing ?

Voilà c'est tout ce a quoi je pensais :)
je pense qu'il serait bon de rélféchir à rendre progressivement RME plus modulable, notamment sur ces points-là qui sortent un peu de simplement "ajouter" des commandes et fonctionnalités... :)

**Comment by grrim** [comment]
Bonjour. 
Actuellement, je pense que RME n'est plus réellement maintenu. 
Je comprend l'intérêt d'une proposition "modulaire" de RME, c'est 
d'ailleurs comme ça qu'il aurait dût être pensé. 
En l'état, je pense que c'est beaucroup beaucoup de travail car ça 
impliquerait une réécriture (presque) totale de RME.

**Comment by ImCaptainMorgan** [comment]
je veux bien entamer un fork de RME le rendant plus modulable...
aurais-je le soutien de la "RME team" si je me lance dans ce projet?

**Comment by xvw** [comment]
Pour ma part, le projet est open-source et possède une licence non restrictive. Tu peux donc forker/faire des PR sur RME, fais ce qu'il te plait.
