### ISSUE TITLE
Fonctionnement de game_window_rect

### ISSUE THREAD

**Issue by CuddleFox** [RMEx/RME#446]
Salut.
C'est pas vraiment une proposition de commande, puisque c'est un problème qui peut être résolu sans une nouvelle commande (mais une commande pour ça ferait du bien)

J'ai aucune idée de comment fonctionne game_window_rect, visiblement c'est pas un array, car "get" envoi un message d'erreur. Est-ce qu'il est possible de prendre l'une des 4 valeurs renvoyées par game_window_rect individuellement, et si ce n'est pas possible, est-ce qu'il serait possible de rajouter 4 commandes, deux pour les valeurs des x&y du coin haut gauche et 2 pour le coin bas droit de la fenêtre de jeu ?

A la base, je comptais m'en servir pour faire chercher au joueur quelque chose sur son écran avec la fenêtre de jeu.

Merci pour vos réponses.

**Comment by Hinola** [comment]
C'est un rectangle, de la classe Rect (Inclus dans la librairie de jeu de base)
Tu accèdes aux valeurs simplement : 
game_window_rect.x
game_window_rect.y
game_window_rect.width
game_window_rect.height

**Comment by CuddleFox** [comment]
D'accord, merci beaucoup.
Est-ce qu'il serait possible de modifier la description dans l'aide alors ? ^^

**Comment by Hinola** [comment]
Tu peux donner un lien de l'aide dont tu parles ?
Merci

**Comment by CuddleFox** [comment]
http://rmex.github.io/RMEDoc/#game_window_rect

**Comment by BastienDuplessier** [comment]
Si tu le souhaites, tu peux réaliser une pull-request pour ajouter cette info dans la doc. Si tu le fais, on validera et fusionnera avec la branche principale.
