### ISSUE TITLE
pixels_between(idA, idB)

### ISSUE THREAD

**Issue by Zer0xxxxx** [RMEx/RME#448]
Bonjour !
Sur quel "point" du sprite se base pixels_between ?

J'ai l'impression qu'elle se sert du coin haut-droite et du coup elle donne des mesures plutôt faussées quand je cherche à faire des choses précises avec...

Serait-il envisageable de préciser les points d'origine des deux événements avec cette commande ?

Merciii !

**Comment by grrim** [comment]
Non.
