### ISSUE TITLE
Orms + text_profile

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#473]
### Configuration (lorsque le bug a été rencontré)

- **Version de RME** : `2.1.0`
- **Commande** : `text_profile`
- *Autres scripts  : `Orms`

---

A l'heure actuelle, lorsque l'on affiche un text via la commande `text_show`, il est possible de spécifier le profile du text avec ceux qui sont inscrit dans le fichier `ITextProfile.csv`.

Lorsque l'option `bitmap_font` de Orms est activé, les profils sont totalement ignorés. Normal, puisqu'il sont inutile et incompatible avec la font en bitmap généré par Orms.

Néanmoins, cela rend impossible le fait d'utiliser des couleurs dans les textes générés par `text_show`, mais reste possible dans les autres textes via la commande rm `\C[x]`

Du coup je me demander si il exister une autre façon d'appliquer une couleur au texte ou si c'était possible de fixer ça autrement ? @BilouMaster 

Merci !

**Comment by xvw** [comment]
Bonjour, je pense que ça concerne ORMS et pas vraiment RME. Il vaudrait mieux ouvrir le ticket sur le repo ORMS.

**Comment by BilouMaster** [comment]
A l'avenir merci de ne pas ouvrir des issues concernant des souhaits d'inter-compatibilité ORMS / RME. Ni sur RME, ni sur ORMS. Les deux scripts sont indépendants et le resteront.
