### ISSUE TITLE
Proposition d'effet à l'écran

### ISSUE THREAD

**Issue by Bliaxx** [RMEx/RME#480]
#### Command's purpose

La commande appliquerait un effet "bug" à l'écran, pour illustrer mes propos je vous mets un aperçu de l'effet de la potentiel commande : 

![maxresdefault](https://user-images.githubusercontent.com/67436831/85779797-44d90380-b724-11ea-9374-36d711099cb8.jpg)

#### Command's syntax

screen_bug(amplitude) / amplitude = il faudra rentrer un chiffre qui définira le degré de l'effet à l'écran.

**Comment by BilouMaster** [comment]
La définition de la feature est un peu fantasque, mais surtout en fait c'est difficilement faisable comme effet, l'effet bug, surtout celui représenté dans ton exemple de tutoriel photoshop dans la mesure où il s'agit d'une manipulation sur les couches (décalage de couche R  par rapport à GB), ce qui est impossible  dans le RGSS3.

L'application de décalages aléatoires au sens d'un effet d'ondulation destroy en revanche est possible mais alors c'est trop spécifique comme effet et il faut encore combiner avec des ressources (images à ajouter) pour obtenir un effet convainquant.

Les effets d'écrans actuels sont rigolos mais alors, plutôt dépréciés... Je ne pense pas qu'on s'amusera à implémenter encore des choses basées sur le principe qu'on emploie actuellement, l'effort d'optimisation a beau être présente, le ralentissement du moteur de jeu (game.exe) reste trop conséquent.

Il vaudrait mieux pour toi de comprendre comment orms et rme fonctionnent pour essayer de créer un script tout à fait  indépendant, toi-même, qui t'aidera à compléter des effets "à la main" ou bien rechercher du côté du travail de Zeus81 et autres scripteurs audacieux qui ont également tâté dans les effets d'écrans.

Romain68 aka Noiracide sur Twitter avait réalisé de bons effets dans ses jeux RPG Maker, mais c'est qu'il est un bon graphiste plein d'idées et doté d'une bonne intuition dans son travail de direction artistique.

**Comment by Bliaxx** [comment]
Oui je comprends, puis je me doute que Rpg Maker ne supportera que trop difficilement ce genre d'effet ^^ Mais merci à toi d'avoir répondu !

**Comment by BilouMaster** [comment]
Je me rappelle avoir codé un script très court reproduisant un effet d'ondulation sur l'écran, juste un zoom de l'écran qui oscille différemment en largeur et en hauteur. Vraiment parfois c'est facile et ne demande une ou deux opération lourde par frame, parfois ça en demande une floppée et voilà ça laggue. Juste pour dire c'est très facile à faire, mais le game.exe/rgss3 est trop mal fichu pour aller bien loin.

**Comment by Bliaxx** [comment]
Oui je me doutais bien qu'il fallait jouer avec des zoom différent de l'écran pour reproduire un certain décalage de pixel, mais après quand on veut l'appliquer sur une grande séquence de jeu ça commence à faire lourd effectivement pour RM

**Comment by BilouMaster** [comment]
Le plus gros manque c'est l'impossibilité de faire shaders sous RM vxace. xvw a déjà fait des prouesses en réécrivant le get pixel "en mieux" mais ça reste une opération lourde (actuellement employée dans les commandes d'action de clic sur les Pictures... l'option qui permet de détecter qu'on clique bien ou survole bien l'image en elle-même et non des pixels transparents).

On peut déjà se féliciter pour ce genre de bidouilles mais c'est encore loin d'être aussi performant que les méthodes employées dans le développement logiciel actuel.

**Comment by xvw** [comment]
ca ne dérange pas si je ferme l'issue?

**Comment by Bliaxx** [comment]
Non du tout.
