### ISSUE TITLE
Plus de choses à afficher ? 

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#53]
Bonjour,

Malgré les nombreuses choses pouvant déjà être affiché via les commandes RME, je trouve dommage de voir certaines choses manquantes. Pourquoi ne pas créer une série de commandes équivalentes à celles pour les images mais pour les icônes ou les facesets ? ça pourrait laisser plus de possibilités aux utilisateurs. De plus, pourquoi ne pas envisager de créer une commande permet de "fragmenté" une image(et de stocker une partie d'elle dans une variable par exemple), un peu à la manière des Tiles ou des charsets (ce qui permuter d'avoir de nouvelles possibilités de trier les images). Voilà quelques idées qui me traînent dans ma tête, j'espère qu'elles pourront vous aider.

Cordialement, Spyrojojo

**Comment by Jauke** [comment]
Pour se faire, je comptais implémenter des commandes type `picture_spritesheet` pour pouvoir découper l'image et passer d'une frame à l'autre. Pour récupérer un face ensuite je pense qu'il est possible (?) de donner un chemin relatif type '../faces/bidule'.

Sinon on peut imaginer des commandes `face`, `character`, `icon` à utiliser pour le nom de l'image d'un `picture_show` ou `picture_name`, genre, faire : `picture_show(1, icon(5), 30, 50)`...

Il y a 41 commandes différentes pour les pictures, ça serait embêtant d'en faire autant pour chaque autre élément, et embêtant d'avoir moins de possibilités, donc je propose qu'on réfléchisse de manière à étendre le potentiel des pictures plutôt que de faire des clones de chaque commande.

**Comment by xvw** [comment]
La commande follower n'est pas ambigüe, elle permet juste de référencer quelque chose qui à la bonne forme (renvoyer un game_character). 
Pour picture_spritesheet, il faut trouver une sémantique adéquate pour éviter de tomber dans les travers de l'ancienne commande "picture_text" qui provoquait des lags assez insuportables.

**Comment by Spyrojojo** [comment]
Modifier l'argument "name" pour le renvoyé sur un autre élément que des images ? pas bête, je n'y avais pas pensé et ... en effet ça éviterez de faire des commandes doublon. 

Jauke => "je comptais implémenter des commandes type picture_spritesheet pour pouvoir découper l'image et passer d'une frame à l'autre.". Hate de voir ça :+1:  est surtout de pouvoir les utilisé.

En tout cas j’espère vous avoir donner d'éventuel petite idées.

**Comment by xvw** [comment]
Picture_spritesheet me semble la meilleure approche

**Comment by Grimimi** [comment]
Comme les issues qu'il ne me restait que 1 seule issue, 
j'ai démarré celle-ci ! Je pense avoir le temps de finir ce weekend !
