### ISSUE TITLE
Prob' Camera_move

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#54]
Pour commencer, je ne suis pas sûr de me servir de la commande correctement

Exemple : 
camera_move_on(event_x(34), event_y(34))
[cutscene]
camera_move_on(player_x, player_y)

J'ai alors deux problèmes.
=> La caméra n'a pas de déplacement en diagonale
=> La caméra ne revient même pas toujours sur le joueur... :/

Merci de votre aide ! o/

**Comment by Grimimi** [comment]
Je ne comprend pas le problème 2. 
J'ai fait quelques essais et pourtant la camera se déplace toujours sur le joueur.

**Comment by Grimimi** [comment]
pour revenir sur le héros, tu peux te servir de "camera_change_focus(0)", ne pas hésiter à locker/unlocker la caméra. 
Concernant les déplacements en diagonnale, c'est un peu ennuyeux à coder. Surtout que pour qu'ils soient "jolis" ils faut que le scrolling point soit%45° (donc seulement sur des diagonales du focus actuel)
