### ISSUE TITLE
[RME builder] lol

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#55]
http://img110.xooimage.com/files/f/5/b/ti91511f16e5dfdf4...ze_distr-4cc30ed.jpg
(Au démarrage, pas sur mon PC)

**Comment by hyperaho** [comment]
A noter que cette issue aurait plus sa place dans RMEBuilder que RME. 
Je suis surpris de voir que @xvw n'a pas mis le README à jours. Mais malheureusement, à cause d'un problème lié à Ruby, RMEBuilder ne peut construire un rvdata2 (ou se lancer) si dans un des chemins il y a un caratctère spécial (un e accent par exemple). 

De plus, RMEBuilder ne fonctionne pas sous Windows 10. C'est balo

**Comment by xvw** [comment]
Oui, c'est modifié : http://rmex.github.io/RMEBuilder/
