### ISSUE TITLE
[Idée] Génération procédurale (de donjon)

### ISSUE THREAD

**Issue by BastienDuplessier** [RMEx/RME#56]
VX et VXace ont un générateur de donjon. Malheureusement c'est un peu du caca (donjon très basiques, vides, sans réel chemin à suivre pour arriver au bout).
Je pense qu'il serait intéressant de poser des bases pour permettre de faire de la génération procédurale de donjon comme n'importe quel RogueLike. En ajout à ça, permettre la génération de map en dehors du jeu (export en rvdata2) pour une utilisation en tant que créateur de donjons.

C'est juste une idée pour le moment. Je n'ai pas l'intention de la réaliser (tout du moins pas dans l'immédiat). L'interet est déjà de savoir si cela s'intégrerait bien dans RME, peut être réaliser une spec de ce que cette feature devrait faire, comment et réfléchir à une amorce de réalisation ?

**Comment by xvw** [comment]
Je pense que l'idée est intéressante, ne serait-ce que par sa thématique mais telle qu'elle est 
présentée actuellement, elle ne s'inscrit pas dans RME. 

### Pourquoi 
-  Je pense que la génération de *rvdata2* (connu de l'éditeur) doit être obligatoirement lié à des projets externes. (Sauf, par exemple, un self-updater de RME); 
-  On s'éloigne un peu trop du postulat initial de RME. 

### Comment rendre cette idée valide
L'idée n'est tout de même pas à jeter. On pourrait imaginer des outils pour altérer, "in game" la 
structure même d'une carte, ce qui est déjà plus ou moins possible via les commandes de
modification du tileset. On pourrait réfléchir à un SDK "ingame" pour générer des cartes à la volées. Mais je ne suis pas sur qu'il s'agisse d'une priorité :) 

Merci.
