### ISSUE TITLE
[Petite question] Les appels de page ont l'air gourmand...

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#58]
Bonjour.
J'ai voulu faire des events "tiroirs" (RPZ Joke sisi). Autrement dit, des events en processus parallèle qui appellent assez fréquemment certaines de leurs propres pages correspondant à certaines fonctionnalités.

Avec un event, ça le fait, mais quand je le copie/colle en 3 ou 4 exemplaires sur une map... grosse chute de FPS. C'est limite si les FPS descendent de 10 à chaque nouveau C/c de cet event à partir de ce seuil-là.

Est-ce normal ou est-ce que la commande "include_page" est encore en "phase d'optimisation" (ou quelque chose qui sonne comme ça) ? :D 
Il me semble déjà avoir eu des problèmes avec l'Event Extender, à l'époque, où "trop" d'appels de page faisaient simplement planter le jeu.

EDIT:
J'ai refait exactement le même code sans les appels de page et il n'y a plus aucun lag... :/
Je pense donc pouvoir établir un constat comme quoi ils sont (trop) gourmands.

Le soucis intervient à partir du moment que plusieurs événements appellent leurs propres pages trop fréquemment...

**Comment by xvw** [comment]
Merci :) ping @Grimimi

**Comment by Zer0zer0x** [comment]
https://www.dropbox.com/sh/lnz5c0f242rsqsr/AAD9_Dwh9xuuiF7FjXU3eHDra?dl=0
Pouet.

**Comment by Zer0zer0x** [comment]
Bump!
En tout cas, je tiens à vous dire que je vous félicite beaucoup sur le travail que vous faites avec RME. :)
C'est très agréable de s'en servir.
Voilà, bisous. Et bonne chance pour l'amélioration de ce point que j'ai abordé, ça a l'air prise de tête. ^^'

**Comment by Grimimi** [comment]
Fixed ! 
Les appels de pages sont plus performants. (Srutout quand ils sont sur la même carte) (néhsite pas a commenter)
