### ISSUE TITLE
[CTSS] Commande event "Retourner à l'écran titre"

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#59]
Pwêt.
Avec le killer d'écran titre, j'ai constaté (rapidos) qu'utiliser la commande event "Retourner à l'écran titre" faisait revenir sur l'écran titre de base. :v 
Des bisous.

**Comment by Spyrojojo** [comment]
C'est normal, le "tueur" d'écran titre ne sert qu'a le faire sauté, pas a le supprimé

**Comment by BastienDuplessier** [comment]
C'est assez pratique quand on veut faire un petit splash screen par exemple. Le petit évent qui va bien, puis aller à l'écran titre :A
