### ISSUE TITLE
[Demande de modification de commande, le 9/29/15]

### ISSUE THREAD

**Issue by Dylou** [RMEx/RME#62]
Bonjour/soir à tous ! Comme l'indique le titre de l'issue, je fais cette demande pour modifier la commande move_to . De telle sorte à ce qu'on peut choisir si le move_to ne se déplace que sur des cases passables ou non :)

Voilà en espérant avoir été clair et précis :)

                     Cordialement,  Dylan/Waikiki

**Comment by Jauke** [comment]
Bonjour,

Théoriquement, le `move_to` ne déplace que sur les cases passables, sauf si l'événement ou héros est en mode fantôme.

S'il ne tient pas compte du mode fantôme, y'a un souci.

**Comment by xvw** [comment]
non il ne tient pas compte du mode fantôme, parce que sinon, il refuserait "d'essayer" de se rendre à une destination.

**Comment by Jauke** [comment]
S'il est en mode fantôme, il est sensé pouvoir se rendre à n'importe quelle destination sans se préoccuper des obstacles... non ?

**Comment by xvw** [comment]
non parce que le chemin est calculé en utilisant la méthode passable? de game_map, pas du caractère.

**Comment by Jauke** [comment]
Et donc... est-ce que vous avez bien fait de faire avec le Game_Map ? :p

**Comment by xvw** [comment]
Il faut en discuter :) qu'en penses tu ? 
Pour le moment il y a des priorités.

**Comment by Dylou** [comment]
Donc ducoup ? :)

**Comment by Grimimi** [comment]
Dans un premier temps, tu peux t'en tirer "algorithiquement". Par exemple, tu peux utiliser les deux côté adjacent à ton angle droit pour calculer un chemin? (Si ton character est fantômatique ça marche bien) : 
```
coeff_x = | character_x - destination_x |
coeff_y = | character_x - destination_y |
compteur = 0 
boucle 
    si compteur == coeff_x
        sortir de la boucle 
    fin condition 
    si character_x > destination_x
       faire un pas à gauche
    sinon 
       faire un pas à droite
    fin_condition 
fin_boucle
compteur = 0 
boucle 
    si compteur == coeff_y
        sortir de la boucle 
    fin condition 
    si character_y > destination_y
       faire un pas vers le haut
    sinon 
       faire un pas vers le bas
    fin_condition 
fin_boucle
```

Comme ton personnage est "en mode fantôme", cependant, le chemin le plus court sera toujours l'hypothénus entre ton personnage et la destination. Tu peux donc t'en tirer très facilement t'en tirer avec une fonction affine (facile à faire aussi) :)

**Comment by xvw** [comment]
Non, tu n'as pas compris Grim (et moi non plus au passage). 
Ce que Dylou voudrait, c'est que même en mode fantôme, l'évènement se déplace uniquement sur les cases passables. 

Donc de mon point de vue, la solution "simple" serait simplement, de mettre l'évènement en mode non fantôme avant le déplacement, et de le remettre en fantôme après. Non?
