### ISSUE TITLE
Petit prob' avec l'argument "me" dans un appel de script inclus à un déplacement de perso

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#63]
Pour des raisons à la con (insérer un script dans un déplacement d'event), j'ai dû faire tenir ma condition sur une seule ligne : 
{déplacements de 6 carreaux}
script: SV[1] += 1
script: if SV[1] >= 12 / 6 and squares_between(me, 0) > 3 then SS['A'] = false end

In game, RM coince sur le "me". Peut-être que c'est ma faute, c'est très cheum ce que j'ai fait...
Merci de votre aide. ^^

EDIT:
Il semblerait que, n'importe quelle portion de script contenant "me" dans un déplacement déconne.

Par exemple : 
move_to(me, player_x, player_y) ne fonctionnera pas...

RE-EDIT:
En fait, j'ai l'impression que tous les arguments RME déconnent... "player_x" et "player_y" faisant partir en vrille RM aussi.

**Comment by al-blues** [comment]
##### L'appel de script effectué lors de la définition d'une trajectoire suit un chemin différent de celui définit dans la page d'un événement. 
Même si cet appel est déjà bel et bien intercepté par RME (`EvEx.rb` > `Game_CharacterBase.eval()`), son évaluation n'inclue pas encore les commandes. De fait, tu ne peux pas bénéficier du mécanisme te permettant d'omettre l'espace nom sous lequel les commandes sont définies.

En ce qui concerne l'utilisation de la méthode `me`, celle-ci est définie dans l'interpréteur (Game_Interpreter) relié à l'event (Game_Event). Or un appel de script définis dans une trajectoire n'est pas évalué par l'interpréteur mais par l'event lui-même. Du coup, on ne peut pas disposer des informations présentes dans l'interpréteur; il faudrait définir la méthode `me` dans la classe Game_Event:

```ruby
class Game_Event
  def me; @id; end
end
```
(Rajoute ceci dans un script _temporaire_ à part si tu veux que ton exemple fonctionne, le temps que ce problème soit corrigé dans RME)


> Il faudrait certainement revoir le cas `ROUTE_SCRIPT` de la méthode `process_move_command(command)` (classe Game_Character). Malheureusement, je ne connais pas assez RM :S.




Si tu veux disposer des commandes RME dans l'état actuel des choses (c'est-à-dire sans avoir à modifier manuellement certains scripts ou attendre la sortie d'un patch), il faut que tu préfixes l'appel auxdites commandes par `Command`.
```ruby
SV[1] += 1
SV[1] >= 12 / 6 and Command.squares_between(me, 0) > 3 then SS['A'] = false end
```

(Idem pour les commandes `player_x` et `player_y` qui deviennent respectivement `Command.player_x` et `Command.player_y`)

--
##### Futilité
Ruby est assez expressif et arbore une syntaxe proche du langage naturel, tu peux donc exprimer ta condition de la manière suivante:
```ruby
<action> if <condition>
```

Ce qui donne (désolé, je parenthèse à l'extrême :():
```ruby
SS['A'] = true if ((SV[1] >= 2) and (Command.squares_between(me, 0) > 3))
```

**Comment by xvw** [comment]
A noter que l'on peut se servir du solveur de portée via : c(:command_name, arg1, arg2, ..., argX)

**Comment by Zer0zer0x** [comment]
J'apprécie énormément cette "futilité" qui m'a fait me sentir bête ! :) 
Merci Al_blues (et tkt pas, j'ai réadapté l'event en conséquenes, hihihi). :D 
Bonne chance pour vous en sortir avec ce problème. ^^'
