### ISSUE TITLE
"wall?" ne fonctionne que sur les pieds de mur...

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#64]
Autrement dit : 
http://img110.xooimage.com/files/3/b/3/verif-4cf87d4.png

Ca parait con, non ?

**Comment by BastienDuplessier** [comment]
Personnellement ça me parait logique.
Un mur est un mur. Un "dessus" est un dessus. Non ?

**Comment by Zer0zer0x** [comment]
Le dessus fait partie du mur.
Le soucis c'est que je voulais me servir de Wall pour deux raisons (et peut-être plus dans l'avenir) : 
_ Permettre de vérifier si un mur sépare le joueur d'un "garde" (dans un système d'infi, par exemple).
_ Vérifier si le joueur est dans un couloir et calculer à quel point celui-ci est étroit (pour un petit trip de diffusion de lumière).

Selon les perspectives et les angles... ça finit rarement possible, vu que ce qui va être présent en majorité et qui va le plus vadrouiller un peu partout dans la map... ce sont les dessus (dans mon style de mapping). :'(

**Comment by BastienDuplessier** [comment]
T'as pas moyen d'utiliser les ID de tiles pour ça ?

**Comment by xvw** [comment]
Oui, wall? ne fonctionne que pour les pieds de murs et c'est comme ça qu'elle a été pensée ;)
