### ISSUE TITLE
move_to un peu dur d'oreille...

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#65]
À moins que le soucis vienne de moi ?
http://image.noelshack.com/fichiers/2015/41/1444000206-move-to.gif

**Comment by xvw** [comment]
La commande move_to est assez ennuyante... c'est une des plus utilisée mais une des plus lourde aussi.

**Comment by Grimimi** [comment]
Je pense qu'ici, le soucis vient de la détection du clique, pas de move_to.

**Comment by Zer0zer0x** [comment]
Je ne pense pas.

**Comment by xvw** [comment]
Est ce que ce soucis est toujours d'actualité ou alors je peux fermer?

**Comment by Ibiky** [comment]
Salut pour te répondre oui c'est toujours d'actualité et depuis un long moment même, en voila un petit exemple : http://puu.sh/p8VnJ/6db9821a9e.gif si plus d'information, n'hésiter pas à me demander en cas le code : http://puu.sh/p8VrE/ab49a3bb69.png
