### ISSUE TITLE
Soucis avec les arguments W et H de la commande create_text_window

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#66]
Bonjour, les argument W et H qui peuvent calculé automatiquement la taille de la commande create_text_window a un léger soucis. Quand ont modifie la taille de la police de base de RM (via Font.default_size = 20 par exemple) la taille de la fenetre ne s'adapte pas a la nouvelle "taille" de la police,

**Comment by xvw** [comment]
Euh une fenêtre déjà créée ou à sa création?

**Comment by Spyrojojo** [comment]
a sa création. 
j'ai donc en appel de script : 

SL[:content] = ["Pêcheur :", "ça ne mord pas ici !"]
SL[:x] = event_screen_x(me)
SL[:y] = event_screen_y(me) - 70 - SL[:hauteur]
create_text_window(15, SL[:content], SL[:x], SL[:y])

et en jeu ça donne ça : (en sachant que j'ai mis Font.default_size = 10 dans un nouveau script)
http://image.noelshack.com/fichiers/2015/41/1444228984-capture-d-ecran-2015-10-07-16-41-59.png

PS : j'ai volontairement mis une police de texte miniature pour bien voir le soucis,

**Comment by xvw** [comment]
Dès que je repasse sur Windows je m'en occupe ;) kiss.

**Comment by Spyrojojo** [comment]
ça marche :D merci

**Comment by xvw** [comment]
En fait, comme je te l'avais dit IRL, le profil par défaut utilise le text_profile de la base de données par défaut. Pas celui des bitmaps ;)
