### ISSUE TITLE
Quelques petites remarques.

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#68]
Ci dessous quelques petites remarques et erreurs que j'ai pu repérer sur RME

- Pas de description ici : [`create_horizotal_commands_window`](http://rmex.github.io/RMEDoc/#create_horizontal_commands_window)

- La commande RME : [`window_opacity`](http://rmex.github.io/RMEDoc/#window_opacity), ne fonctionne pas (aucun changement d'opacité durant son utilisation).

- Pourquoi ne pas ajouter l'argument d'opacité dans la création des Windows et des Textfields ?

- Pourquoi ne pas ajouter à la commande : [`textfield_text_show`](http://rmex.github.io/RMEDoc/#textfield_text_show) un argument pour choisir de l'activer ou non dès sa création ?

- Certaines commandes comme picture_x peuvent renvoyer une valeur (ici la position X de l'image) si aucune valeur n'a été précisée. Cependant certaines commandes ne semblent pas avoir cette "option" :
  -[`picture_scroll_x`](http://rmex.github.io/RMEDoc/#picture_scroll_x)
  -[`picture_scroll_y`](http://rmex.github.io/RMEDoc/#picture_scroll_y)
  -[`text_opacity`](http://rmex.github.io/RMEDoc/#text_opacity)
  -[`text_move`](http://rmex.github.io/RMEDoc/#text_move) (à compléter avec une commande `text_move?` ?).
  -[`text_profile`](http://rmex.github.io/RMEDoc/#text_profile)
  -[`window_content`](http://rmex.github.io/RMEDoc/#window_content)
  -[`parallax_scroll_x`](http://rmex.github.io/RMEDoc/#parallax_scroll_x)
  -[`parallax_scroll_y`](http://rmex.github.io/RMEDoc/#parallax_scroll_y)
  -[`parallax_autoscroll_x`](http://rmex.github.io/RMEDoc/#parallax_autoscroll_x)
  -[`parallax_autoscroll_y`](http://rmex.github.io/RMEDoc/#parallax_autoscroll_y)
  -[`parallax_zoom_x`](http://rmex.github.io/RMEDoc/#parallax_zoom_x)
  -[`parallax_zoom_y`](http://rmex.github.io/RMEDoc/#parallax_zoom_y)
  -[`parallax_opacity`](http://rmex.github.io/RMEDoc/#parallax_opacity)

- Pourquoi ne pas avoir fait une commande `text_angle` (qui est disponible pour les pictures) ?

- La commande [`window_moveto`](http://rmex.github.io/RMEDoc/#window_moveto) permet de modifier la position des window mais les commandes qui peuvent le faire de maniére indépendante ne renvoient que la valeur sans possibilité de la modifier (comme peu le faire `picture_x` ou `picture_y`)
  -[`window_x`](http://rmex.github.io/RMEDoc/#window_x)
  -[`window_y`](http://rmex.github.io/RMEDoc/#window_y)

- Pas mal de commandes (particulièrement au niveau des images) n'ont pas de sélecteur est restent avec une possibilité de simple id (trop de commandes a lister )

Voila pour aujourd’hui, je me doute bien que ces remarques ne sons pas primordiales au fonctionnement et au contenu de RME, mais je pense qu'il est bon de signaler ce genre de choses.

Bonne journée a vous.

<img src="https://johncena.me/static/img/cenalogo.png" align="left" height="112" width="127" alt="Jaen Meichl Othorgarhpe/snxyate" />

**Comment by xvw** [comment]
- [ ] fix description `create_horizotal_commands_window`
- [ ] fix `window_opacity`
- [ ] Opacité pour la création d'une fenêtre
- [ ] Opacité pour la création d'un textfield
- [ ] Activation à la création d'un textfield 
- [ ] `picture_scroll_x/y` retournant une valeur si rien n'est donné
- [ ] Implémenter `text_move?` 
- [ ] `text_opacity/profile`renvoi sa valeur si rien n'est donné 
- [ ] `window_content` renvoi sa valeur si rien d'est donné 
- [ ] `parallax_*` renvoi sa valeur si rien n'est donné
- [ ] Implémenter `text_angle`
- [ ] `window_x/window_y` permettant de modifier leur x ou y 


> Pas mal de commandes (particulièrement au niveau des images) n'ont pas de sélecteur est restent avec une possibilité de simple id (trop de commandes a lister )

Je pense que c'est lié au fait que certaines commandes ne peuvent pas fonctionner avec un sélécteur non?

**Comment by Spyrojojo** [comment]
Merci d'avoir était a l'écoute.
Pour les ID je ne sais pas je ne m'y connais pas suffisamment. Comme je les précisé, ce ne sont que des choses que j'ai juger bon de signalé

**Comment by Grimimi** [comment]
`Opacité pour la création d'une fenêtre`
C'est assez ennuyant étant donnée l'aspect "fortement polymorphique" des commandes de fenêtres. Pour ma part, je ne l'implémenterai pas car ces commandes "prennent déjà trop d'arguments". Deplus rien n'empêche d'ajouter une ligne `window_opacity(x, 200)` par exemple.

**Comment by Spyrojojo** [comment]
Ok merci :D. 
Bonne journée à vous.
