### ISSUE TITLE
[Incompatibilité] Victor's Scripts - MultiFrame

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#69]
J'ai un problème de compatibilité avec RME, sur un script de Victor, son script multiframe, le script fonctionne, mais lorsque RME est installé, l'apparence du héro est décalé de sa hitbox, du coup les collision se font sur un perso "invisible".

Le lien du projet : http://www.mediafire.com/download/f86i3474qy37en9/MultiFrame.rar

**Comment by BastienDuplessier** [comment]
Le problème est du au zoom. L'update du zoom est appellé après l'update_src (aliassé dans le script de victor). Dans un premier temps, Voici un patch qui permet de skipper le zoom pour les sprites concernées. @xvw @Jauke Vous pensez que ça vaut le coup de régler le problème autrement ou non ?

```ruby
#==============================================================================
# ** Sprite_Character
#------------------------------------------------------------------------------
#  This sprite is used to display characters. It observes an instance of the
# Game_Character class and automatically changes sprite state.
#==============================================================================

class Sprite_Character
  alias :patch_victor_update_zooms :update_zooms
  #--------------------------------------------------------------------------
  # * Frame Update zoom
  #--------------------------------------------------------------------------
  def update_zooms
    patch_victor_update_zooms unless @character_name[/\[F(\d+)\]/i]
  end
end
```

**Comment by xvw** [comment]
C'est bon, mais pour moi, la meilleure manière de raisonner est simplement de ne pas utiliser un script de Victor...

**Comment by BastienDuplessier** [comment]
Pas faux, plus qu'a avoir une feature similaire dans RME :D Tu peux close si tu n'as plus rien à ajouter.
