### ISSUE TITLE
Déclencheurs personnalisés

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#70]
Bonsoir, j'ai un problème avec les déclencheurs perso, j'ai suivi le tutoriel mais le jeu crash toujours.
![event](https://cloud.githubusercontent.com/assets/15834672/11166347/d38d7f5a-8b2f-11e5-9e5d-5f45109e93c2.PNG)
![capturfsdfe](https://cloud.githubusercontent.com/assets/15834672/11166348/dcf6fcc4-8b2f-11e5-84fe-bf77683d56f1.PNG)
Pouvais-vous m'expliquez mon erreur ?

**Comment by xvw** [comment]
SV[10] == 1 ?

**Comment by YendaHusk** [comment]
Non plus, le même crash. =/

**Comment by Grimimi** [comment]
Je n'ai pas pu tester, mais se pourrait-il qu'il faille (malgré ce qu'en dit la documentation), utiliser `trigger{|id| SV[10] == 1}` (où id référence l'Event Id) ?

**Comment by YendaHusk** [comment]
Toujours pareil. C'est vraiment bizarre que ça ne fonctionne pas.

**Comment by Grimimi** [comment]
Tu peux faire une MAJ de RME t(trigger{....} et trigger{|id| .... } devraient fonctionner maintenant). Merci.

**Comment by YendaHusk** [comment]
Je peut faire la mise à jour manuellement ? Je suis sous W10 et RMEBuilder ne fonctionne pas dessus

**Comment by xvw** [comment]
Oui.

**Comment by xvw** [comment]
@YendaHusk ce problème est fixé ou le bogue persiste ?

**Comment by YendaHusk** [comment]
C'est fixé grace à la mise à jour, mais il faut utilisé la commande trigger{|id| SV[10] == 1}

**Comment by xvw** [comment]
Yes thanks !
