### ISSUE TITLE
Commande manquante ?

### ISSUE THREAD

**Issue by Spyrojojo** [RMEx/RME#71]
Bonsoir,

J'ai pu remarquer en bossant sur mon projet qu'une commande intéressante était absente, a savoir : text_clear. celle si existe pour les images et les parallaxes mais pas pour les textes.

Cordialement, Spyrojojo.

**Comment by Grimimi** [comment]
Effectivement, peut être peux-tu l'implémenter ?

**Comment by Spyrojojo** [comment]
Un bon moment que je n'est pas touché au Code de RME, mais j'accepte de tenté le coup :D

**Comment by Spyrojojo** [comment]
La commande en question viens d'être proposé. Encore désolé d'avoir du le faire sur 2 proposition (1 pour la commande, l'autre pour la doc),je n'est toujours pas trouvé le moyen de modifier 2 fichier sur la même pull request

**Comment by Grimimi** [comment]
La documentation leur a été générée
