### ISSUE TITLE
POURQUOI CA MARCHE PAS

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#74]
event_ox(me, event_x + 30)
event_oy(me, event_y + 30)

PAKONTAN

**Comment by Zer0zer0x** [comment]
POURQUOI VOUS REPONDEZ PAS ? SALES JUIFS DE MERDE !!!

**Comment by Grimimi** [comment]
```ruby
event_ox(me, event_x(me) + 30)
event_oy(me, event_y(me) + 30)
```

**Comment by Zer0zer0x** [comment]
Oops. My bad...
À chaque fois j'oublie le "(me)". :v 
L'habitude de plus souvent utiliser "player_x" que "event_x".

Merci.
