### ISSUE TITLE
[Demande de modification de commande, le 12/1/15]

### ISSUE THREAD

**Issue by Dylou** [RMEx/RME#76]
Bonjour/soir à tous ! Comme l'indique le titre de l'issue, je fais cette demande pour modifier la 
commande picture_zoom_x . De telle sorte à ce qu'on peut choisir la direction du zoom (par exemple je veut que ma barre de vie charge vers la gauche ou la droite)

Voilà en espérant avoir été clair et précis :)

              Cordialement,  Dylan/Waikiki

**Comment by Dylou** [comment]
Up

**Comment by hyperaho** [comment]
Bon, ça a été fermé donc je suppose que ce n'est plus d'actualité, mais pour faire ce genre de chose, il suffit simplement de de changer l'axe X ou Y (si zoom_y) de l'image. 
C'est beaucoup trop futile pour mériter une modification sur la commande. 
De plus, ce serait fort aimable d'éviter de faire des "Up" sur une issu. Non seulement, après 2h c'est complètement idiot, mais on n'est pas sur un forum où des dizaines de messages sont postés par jours. 
Merci.
