### ISSUE TITLE
idée pour RME

### ISSUE THREAD

**Issue by Ellyalael** [RMEx/RME#77]
Bonjour ou bonsoir ^^

Alors voilà, j'aimerai pouvoir utiliser les refferences iconset en image individuel?
En gros, afficher une icone du jeu sur l'écran à partir de sa reference d'iconeset?

L'idée viens pour un A-RPG, j'aimerai afficher des icones sur l'écran dans un premier temps.
Surtout je voudrais configurer l'animation de l'attaque en fonction de l'arme équiper.
Je voudrais que si le héro s'équipe d'une arme, ce sera cet arme, cet iconset qui apparaitra lors de l'animation.
Cela évitera de faire une animation par icone de jeu.

j'espère que vous pourrais le faire, si c pas possible, je vous en serais reconnaissante de me le dire. Sur RM mon pseudo c Kingdommangas, voilà merci d'avance ^^.

**Comment by xvw** [comment]
ping :P
