### ISSUE TITLE
Utiliser avec précision la commande tile_id

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#78]
Yo !
J'aimerais savoir comment utiliser une condition avec la commande tile_id pour exprimer "Si le square est compris dans cet ensemble de Tiles..." (préférant ne pas passer par le contraire, bien que ça semble  faire moins de tiles à compter).

http://img110.xooimage.com/files/f/6/3/edit-4e409a5.png
Couche A du TileSet RTP "004: Donjon"

Le soucis est que, je dois mal utiliser la commande, puisqu'elle me retourne des nombres un peu farfelus...

Merci de votre aide. :)

{Image éditée à 18h10 le 29 janv 2016}

EDIT:
Certes, avec ground? c'est déjà bien plus agréable...

**Comment by xvw** [comment]
`[tile1,tile2, ... tileX].include?(tile_id(x, y))`
Même si pour ce genre de chose, je préfèrerais largement utiliser les région.
