### ISSUE TITLE
[BUG:RME-02/06/15] Condition De Page

### ISSUE THREAD

**Issue by Celestiel** [RMEx/RME#8]
IMG+Projet https://www.dropbox.com/sh/xvs95tozmbgehg8/AABWk63xBJNzcJtWkNJnBc42a?dl=0
Mauvais positionement de l'mage de l'event lors du changement de page
Varie en fonction de l'image de départ et de la methode d'activation (dans le cas de l'image mal coupé).

Note sur l'image
Terre, place occupé par le chara 
Neige, place de l'event 
Note sur le projet
Activer l'interupteur 1

**Comment by xvw** [comment]
@Jauke  ? Tu en penses quoi?

**Comment by Jauke** [comment]
Celestiel, tu as bien la dernière version de RME ? (1.0.1)

Sinon, fais un "update RME" + "build" sur ton projet avec RMEBuilder, et dis nous si le problème persiste.

Je regarde ce soir.

**Comment by Celestiel** [comment]
je n'utilise pas builder, j'utilise toujours le projet de test qui se trouve sur github. et la date entre [] correspond au jour ou j'ai téléchargé cette version (souvent le jour même)

**Comment by Jauke** [comment]
Problème réglé, merci Celestiel !
