### ISSUE TITLE
[Demo fournie] Collide ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#80]
Est-ce normal... ?
http://www.aht.li/2819441/wut.gif

La porte est censée s'ouvrir si elle entre en collision avec le pot... ce qui marche très bien, sauf dans le cas où il est projeté dans la mauvaise direction depuis la case pile devant.

Par ailleurs, j'aimerais bien savoir quel sélecteur utiliser pour ce que j'ai tenté de faire à la page 2 de ces derniers (sur la map). Merci ! :)

Touche pour jeter un pot : D (touche "Z" d'RPG Maker)

Lien de la démo :
https://www.dropbox.com/s/yiscqozautmiqfl/DemoCollide.rar

**Comment by xvw** [comment]
Je ne peux pas tester ta démo. Par contre, si j'étais toi, je créerais ce qui s'appel un Mutex 
pour éviter que la condition soit respectée "trop vite". 
En gros, ce qui se passe, c'est que tu téléportes ton événement et il est donc "en collision".
Il y a deux solutions. La première serait que tu crées un interrupteur au moment du téléport qui sera
activé qu'une seule fois que le pot est partit. Soit tu changes la direction du pots. (Dans cet exemple, 
vers le bas). 

Comme je ne peux pas ouvrir ta démo, essayes d'être plus explicite sur ton "sélécteur". Merci.

**Comment by Zer0zer0x** [comment]
J'avais déjà fait le Mutex, mais mal ! ^^
Maintenant ça marche, merci beaucoup ! :)

Par contre, ça, ça ne marche pas... (et c'est pourtant exactement le même code pour la porte).
http://img110.xooimage.com/files/9/6/4/selecteur-4e42ab0.png

**Comment by Zer0zer0x** [comment]
Il semblerait que le mode de déclenchement (partagé entre Processus Parallèle et Démarrage automatique) influence énormément...
