### ISSUE TITLE
Petit bug sur l'animation "Buzz"

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#81]
Si le menu est ouvert pendant l'animation "Buzz"... le jeu plante à la fermeture de ce dernier. Tout du moins, ça le fait quand l'anim se joue sur le héros.

**Comment by BastienDuplessier** [comment]
Je vais voir si je peux m'en occuper ce soir.

**Comment by xvw** [comment]
ping ?

**Comment by Zer0zer0x** [comment]
pong !

**Comment by xvw** [comment]
fixed
