### ISSUE TITLE
Manipulation de l'IconSet

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#82]
Yoh

Est-il possible d'afficher l'icône d'un objet sous forme de picture avec RME selon l'ID d'un objet ou l'index de l'icone ?

Merci. :)

**Comment by xvw** [comment]
@BastienDuplessier @Jauke @Grimimi @mspawn @hyperaho no Windows. Quelqu'un pour le faire ? 
On en avait parlé et une issue en fait référence.

**Comment by xvw** [comment]
doublon avec #77
