### ISSUE TITLE
Problème SkipTitle et GameOver

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#83]
Le Game Over (tout du moins la commande "Game Over" event) avec Skip_title renvoie tout de même vers l'écran titre RM

**Comment by xvw** [comment]
Oui parce que le SkipTitle ne "casse" pas l'écran titre pour permettre de faire des splash screens simplement. 
Il faut implémenter son propre Game Over :)

**Comment by xvw** [comment]
comme relaté précédemment, par toi.
