### ISSUE TITLE
RME : évènements mal positionnés sur l'écran

### ISSUE THREAD

**Issue by Ibiky** [RMEx/RME#84]
Bonjour/soir, je me suis rendu compte, il y a peu, d'une mise à jour RME. Je me retrouve complètement coincé avec mes évènements décalés vers le bas de 16 pixel comme le montre cette image :

http://puu.sh/nBMFt/717a4711e8.png

merci bien à vous de résoudre, si possible, ce problème quelque peu dérangeant.
Cordialement.

**Comment by xvw** [comment]
Maybe 246453839f09d4f7116546958d7b799ad3d45f1f
ping @jauke, @Grimimi

**Comment by BastienDuplessier** [comment]
Normalement c'est réglé avec la nouvelle version.

**Comment by Ibiky** [comment]
merci bien de votre rapidité pour résoudre ce problème, continuez comme cela vous êtes des génies.

**Comment by xvw** [comment]
Merci a Zangther et Joke :) (merci d'avoir relayé le fail). Bonne continuation pour ton projet et 
n'hésite pas à venir en parler sur le Slack ;) 
On ne mord pas :P
