### ISSUE TITLE
Re-penser la commande "move_to"

### ISSUE THREAD

**Issue by xvw** [RMEx/RME#85]
La commande Move_to est un peu trop monolithique. Il faudrait la transformer. 
Actuellement, dans le module Pathfinder, on renvoie un objet RPG::MoveRoute. En gros, il faudrait fragmenter la méthode en 2. La première qui calcul le hash nécéssaire et la seconde qui transforme ce hash en MoveRoute. 

De ce fait, on pourrait avoir deux commandes : create_path(event, x, y), perform_path(path, event). 
perform_path renvoyant "true" ou "false". De ce fait, si depuis la création du chemin, l'évènément devant
se déplacer s'est déplacé depuis la première coordonnées, on cherche si sa case courante est dans le hash. Si non, on renvoi false, si oui, on execute le path depuis la nouvelle case, et on renvoie true. 

Ce qu'il faut faire : 
- Modifier le module Pathfinder 
- create_path(event, x, y) : Hash 
- perform_path(path, event, wait_flag = true) : Bool (+ side effect) 
- move_to(event, x, y, wait_flag = true) : Bool = create_path + perform_path
- path_length(path) 

voila. 
J'espère que quelqu'un pourra s'en charger en modifiant bien Game_character(Base)(je sais plus), Pathfinder, les commandes et en générant la doc :D 
Merci !

**Comment by Ibiky** [comment]
Salut, désoler du dérangement, il faut réellement changer la commande move_to ou simplement la corrigé en attendant car si notre personnage ce cogne à un mur ou qu'il est dans un angle entre deux mur, il ne ce déplace plus, ce qui peu fortement pauser de gros problème.
