### ISSUE TITLE
RME : problème de zone avec create_rect_area

### ISSUE THREAD

**Issue by Ibiky** [RMEx/RME#86]
Comme demandé par Nuki, je fais un issue plus détaillée sur le sujet que j'ai rencontré. 
J'ai réussi à reproduire un des plus gros problème que je n'arrive pas exactement à expliquer, 
J'ai fais un gif: http://puu.sh/nNuKu/61ea95ef5b.gif 
Donc, on voit bien que quand l'event se trouve au centre de la map, pas de problème, mais dès qu'il se retrouve exactement  en (14 , 9) (et cela ne fonctionne que ici) il y a une diagonale qui s'ajoute sans explication
Je peux fournir plus d'informations à la demande.

**Comment by xvw** [comment]
ping @Jauke @Grimimi @BastienDuplessier

**Comment by xvw** [comment]
re? ( @Jauke, @Grimimi, @BastienDuplessier )

**Comment by xvw** [comment]
Bon, le soucis est avec "create_polygon_area" et non "create_rect_area".
Je pense qu'en fait, il vient du fait que tu fais des choses très imprécises, ce qui crée des trous dans la zones. Tu ne peux pas simplement t'en tirer en utilisant la nouvelle commande http://rmex.github.io/RMEDoc/#between qui donne la distance entre deux points.

**Comment by Ibiky** [comment]
oui désoler je me suis trompé de commande (XD en plus dans mon gif on vois bien que c'est polygon) 

j'ai résolu mon problème avec les images, mais j'étais tout de même intriguer par le fait que des zone de trous apparaisse subitement sens prévenir, si ce n'ai pas possible de réparer cela, pas de souci, je n'utilise plus la commande suite a ce problème et d'autre qui apparaisse sans prévenir sans explication et jamais de la m^me façon.
