### ISSUE TITLE
[Demande d'ajout de commande, le 3/28/16]

### ISSUE THREAD

**Issue by Dylou** [RMEx/RME#87]
Bonjour/soir à tous ! Comme l'indique le titre de l'issue, je fais cette issue pour demander d'ajouter une commande RME qui permettrait de supprimer tous les tiles de la même ID qui se trouve sur la map en une seule commande par exemple: "delete_tile(id)"

Voilà en espérant avoir été clair et précis :)

                         Cordialement,  Dylan/Waikiki

**Comment by Ibiky** [comment]
UP, effectivement cette commande me serait utile aussi

**Comment by xvw** [comment]
done http://rmex.github.io/RMEDoc/#delete_tiles 
et au passage : http://rmex.github.io/RMEDoc/#set_tile_where
