### ISSUE TITLE
RME : Petit bug avec le camera_zoom

### ISSUE THREAD

**Issue by Ibiky** [RMEx/RME#88]
Bonjour/soir a vous, en aidant quelqu'un pour un petit tuto d'utilisation de la commande "camera_zoom" pendant un zoom de 200 j'ai afficher un choix à un évent pour dézoomer ou non et revenir a la normal, pendant ce choix un petit bug est apparue je vous l'aise voir : 

http://puu.sh/oIdzk/cba19fd446.jpg

voila espérant que cela peut être réparable.

**Comment by xvw** [comment]
ping @Jauke

**Comment by xvw** [comment]
Salut, j'ai essayé de reproduire ton bogue et je n'ai pas réussi :( Peut être que pour l'éviter, tu pourrais simplement, une fois que le choix est fait, laisser un petit temps d'attente histoire que le zoom se lance quand le menu est fermé ? (pour ma part je n'ai pas eu ce soucis ceci dit)

**Comment by Jauke** [comment]
@xvw : Le bug pourrait bien apparaître uniquement pour la boîte de dialogue des choix... Tu as essayé ?

Ibiky, tu utilise un script en particulier pour les choix ?

S'il y a effectivement un bug, et que j'ai la flemme de corriger, le problème peut se trouver dans `EvEx.rb`, entre les lignes 4185 et 4195 :

```
    #--------------------------------------------------------------------------
    # * Collects all visible windows
    #--------------------------------------------------------------------------
    def collect_visible_windows
      scene = SceneManager.scene
      scene.instance_variables.collect do |varname|
        scene.instance_variable_get(varname)
      end.select do |ivar|
        ivar.is_a?(Window) && !ivar.disposed? && ivar.visible
      end
    end
```

Cette fonction sert à collecter toutes les fenêtres visibles, justement pour ne pas que le zoom soit traité sur ces dernières. S'il y a un bien un bug avec la fenêtre de choix, c'est qu'elle n'est pas collectée dans cette fonction. (Mais ça m'étonnerait un peu, franchement)

**Comment by xvw** [comment]
Dans le sens où j'arrive pas à le reproduire ...

**Comment by Jauke** [comment]
Alors j'aurais tendance à rejoindre ton idée... placer un "attendre" quelque part ?
Il faut qu'on voie le code événementiel.

**Comment by Ibiky** [comment]
je ne sais pas si cela aidera grand chose, ce que j'ai fais : 

http://puu.sh/oOdrj/2b606342dd.png

http://puu.sh/oOdo0/bc4c7558c2.png

**Comment by xvw** [comment]
Est-ce que le soucis persiste ?

**Comment by xvw** [comment]
J'ai réussi à reproduire le soucis "dans la démo fournie", mais en copiant/collant l'événement, je n'ai pas le soucis. 
Peut être qu'il faudrait réinstaller RPGMaker ?

**Comment by Ibiky** [comment]
j'utilise le RM de Steam qui et le même que le crack que j'ai aussi en cas, du coups je vois pas comment résoudre juste en réinstallant RM.

**Comment by xvw** [comment]
Le soucis doit venir de la DLL...
