### ISSUE TITLE
[Résolu] Bug mise à jour RME

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#89]
Salut !
J'ai update RME via RME Builder aujourd'hui, or, à présent, lorsque je lance le projet, il m'affiche l'erreur :
"Script '-SDK.rb' line 184: TypeError occured.
superclass mismatch for class Version_Label"

Merci. :)

**Comment by xvw** [comment]
réessaie un add/build, ça vient peut être d'un soucis de connection :/

**Comment by Zer0zer0x** [comment]
http://puu.sh/oKZsB/b0872d5240.png
Même erreur... :/

**Comment by Zer0zer0x** [comment]
Oh... hihi, je viens de remarquer quelque chose de curieux.
http://puu.sh/oKZJ9/8ae51456d7.png

Peut-être est-ce de ma faute (soucis avec le build schema).
En tout cas, j'ai tout viré et repris les choses de 0.

Curieux. Mais soucis résolu. :)
My bad.

**Comment by xvw** [comment]
Nice !
