### ISSUE TITLE
RME : Ajouter une option au text_show

### ISSUE THREAD

**Issue by Ibiky** [RMEx/RME#90]
Bonjour/soir à vous.

Voila ma demande est simple la j'aimerais si possible afficher un text en text_show mais qu'il agisse comme un text de base en évènement RM en avancent, en cas comme cela : 

http://puu.sh/pzxWd/f8296e48d8.gif

**Comment by xvw** [comment]
Voila : http://rmex.github.io/RMEDoc/#text_progressive
