### ISSUE TITLE
Commande pour imprimer ce qui est affiché à l'écran ?

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#91]
( Je n'arrive pas à charger la documentation RME chez moi... :( 
Peut-être, est-ce donc une double issue ! )

Salut !
J'aimerais savoir si une commande pour imprimer ce qui est affiché à l'écran existe dans RME ou si ce serait envisageable de l'implémenter. :)

Merci !

**Comment by xvw** [comment]
Non désolé, je pense que RME n'est plus maintenu...

**Comment by Zer0zer0x** [comment]
:(

**Comment by xvw** [comment]
Hélas :(

**Comment by Zer0zer0x** [comment]
Quelle solitude, Xavier, je ne te reconnais plus... :(
