### ISSUE TITLE
Rendre plus flexible la commande actor_change_appear

### ISSUE THREAD

**Issue by Zer0zer0x** [RMEx/RME#92]
Yoh !
J'aimerais savoir s'il est possible de réajuster la commande "actor_change_appear"... dans le sens où l'on ne peut pas pointer directement vers l'ID d'un autre héros, par exemple.

A moins que j'ai mal compris, je ne peux pas clairement formuler : "Héros 1 => Prend l'apparence de Héros 2" (ID de la base de données du projet RM).

Bisous. :)

**Comment by xvw** [comment]
> A moins que j'ai mal compris, je ne peux pas clairement formuler : "Héros 1 => Prend l'apparence de Héros 2" (ID de la base de données du projet RM).

```ruby
actor_change_appear(
   id, 
   actor_character_name(autre_id), 
   actor_character_index(autre_id), 
   actor_face_name(autre_id), 
   actor_face_index(autre_id)
)
```
