### ISSUE TITLE
Problème Suppression Event

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/RME#98]
Salut c'est encore moi. :)
J'ai remarqué quelque chose via mon projet actuel qui est plutôt dérangent, j'ignore si c'est un bug d'rm, d'rme ou si c'est normal.
Lorsque je supprime un event in-game via la commande "erase_event" ou la commande classique d'rm, celui-ci disparaît bien, mais est plus ou moins toujours présent, je m'explique :
J'ai un système qui utilise un "once_event" via le nom des events, hors il détecte toujours les events, qui son sensé être supprimer, se qui est plutôt embêtant.
De plus, j'utilise des invocations d'event via la commande "invoke_event" en utilisant la commande "fresh_event_id" pour l'id du nouveau event. Le problème, c'est que si par exemple l'event 10 s'est fait supprimer, le "fresh_event" le compte toujours comme existant et attribut donc l'id 11 au nouveau event.
Ce n'est pas très gênant sauf que pour mon système, il se peut que beaucoup d'event se fasse invoquer et supprimer, mais rendu aux alentours de l'id 80, cela ralenti considérablement le jeu et cela empire au fur et à mesure.
Voilà, avez-vous une solution ? Est-ce réellement un bug ou c'est moi qui m'y prend mal ?
Merci d'avance.

**Comment by xvw** [comment]
Dans la nouvelle version (qui est sortie à l'instant) tout semble "plus performant".
